const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Timer,
		C3.Behaviors.Tween,
		C3.Behaviors.Follow,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Plugins.gamepad,
		C3.Plugins.Particles,
		C3.Plugins.NinePatch,
		C3.Plugins.Touch,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.gamepad.Cnds.OnAnyButtonDown,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Follow.Acts.SetEnabled,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Behaviors.Follow.Acts.SetMaxDelay,
		C3.Behaviors.Follow.Acts.SetDelay,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.OnLoadFailed,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{BoundToLayout: 0},
	{PlayerCollider: 0},
	{ScrollTo: 0},
	{Background: 0},
	{Solid: 0},
	{GroundCollider: 0},
	{Timer: 0},
	{Tween: 0},
	{Follow: 0},
	{Ghost: 0},
	{SpawnPoint: 0},
	{Sine: 0},
	{GoldenSkull: 0},
	{Keyboard: 0},
	{PlayerTextures: 0},
	{Якорь: 0},
	{Score: 0},
	{Fade: 0},
	{Gamepad: 0},
	{Dust: 0},
	{GroundTextures: 0},
	{Shockwave: 0},
	{Impact: 0},
	{GhostParticles: 0},
	{SkullParticles: 0},
	{Hit: 0},
	{Fire: 0},
	{Flare: 0},
	{Instructions: 0},
	{TextBox: 0},
	{Тач: 0},
	{GamePush: 0},
	{Спрайт: 0},
	{bleft: 0},
	{ОбУстройстве: 0},
	{pngwingcom: 0},
	{bright: 0},
	{bjump: 0},
	{a34c3a4a94944276eb82f0bfbf: 0},
	{Аудио: 0},
	{bsound: 0},
	{play: 0},
	{record: 0},
	{sound: 0},
	{ReadInstructions: 0},
	{Delay: 0}
];

self.InstanceType = {
	PlayerCollider: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	GroundCollider: class extends self.ISpriteInstance {},
	Ghost: class extends self.ISpriteInstance {},
	SpawnPoint: class extends self.ISpriteInstance {},
	GoldenSkull: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	PlayerTextures: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	Fade: class extends self.ITiledBackgroundInstance {},
	Gamepad: class extends self.IInstance {},
	Dust: class extends self.IParticlesInstance {},
	GroundTextures: class extends self.ISpriteInstance {},
	Shockwave: class extends self.ISpriteInstance {},
	Impact: class extends self.ISpriteInstance {},
	GhostParticles: class extends self.IParticlesInstance {},
	SkullParticles: class extends self.IParticlesInstance {},
	Hit: class extends self.ISpriteInstance {},
	Fire: class extends self.ISpriteInstance {},
	Flare: class extends self.ISpriteInstance {},
	Instructions: class extends self.ITextInstance {},
	TextBox: class extends self.IWorldInstance {},
	Тач: class extends self.IInstance {},
	GamePush: class extends self.IInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	bleft: class extends self.ISpriteInstance {},
	ОбУстройстве: class extends self.IInstance {},
	pngwingcom: class extends self.ISpriteInstance {},
	bright: class extends self.ISpriteInstance {},
	bjump: class extends self.ISpriteInstance {},
	a34c3a4a94944276eb82f0bfbf: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	bsound: class extends self.ISpriteInstance {}
}