const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.Physics,
		C3.Behaviors.Tween,
		C3.Behaviors.destroy,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pin,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.ApplyImpulseToward,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Spritefont2.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{Logo: 0},
	{Sine: 0},
	{NewRecord: 0},
	{Play: 0},
	{Background: 0},
	{Physics: 0},
	{Tween: 0},
	{DestroyOutsideLayout: 0},
	{Ball: 0},
	{MoveTo: 0},
	{Board: 0},
	{Pin: 0},
	{Circle: 0},
	{CircleTriggers: 0},
	{Dot: 0},
	{Net: 0},
	{PointParticles: 0},
	{Audio: 0},
	{BestScore: 0},
	{LocalStorage: 0},
	{Score: 0},
	{TextBestScore: 0},
	{Touch: 0},
	{FadeEffect: 0},
	{HighScore: 0},
	{ShotTrajectoryX: 0},
	{ShotTrajectoryY: 0},
	{ShotActive: 0},
	{Lose: 0},
	{Win: 0},
	{ShownScore: 0}
];

self.InstanceType = {
	Logo: class extends self.ISpriteInstance {},
	NewRecord: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	Ball: class extends self.ISpriteInstance {},
	Board: class extends self.ISpriteInstance {},
	Circle: class extends self.ISpriteInstance {},
	CircleTriggers: class extends self.ISpriteInstance {},
	Dot: class extends self.ISpriteInstance {},
	Net: class extends self.ISpriteInstance {},
	PointParticles: class extends self.IParticlesInstance {},
	Audio: class extends self.IInstance {},
	BestScore: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	Score: class extends self.ISpriteFontInstance {},
	TextBestScore: class extends self.ISpriteFontInstance {},
	Touch: class extends self.IInstance {},
	FadeEffect: class extends self.ITiledBackgroundInstance {}
}