const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Car,
		C3.Behaviors.wrap,
		C3.Plugins.Photon,
		C3.Plugins.Function,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.TextBox,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Behaviors.LOS,
		C3.Plugins.Browser,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.NinePatch,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Photon.Exps.ActorNameByNr,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Function.Acts.SetReturnValue,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Photon.Exps.MyActorNr,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Car.Cnds.IsMoving,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Car.Acts.SimulateControl,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Photon.Cnds.onEvent,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Photon.Exps.EventData,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.Photon.Acts.raiseEvent,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Browser.Acts.ExecJs,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Photon.Acts.setMyActorName,
		C3.Plugins.Photon.Acts.connect,
		C3.Plugins.Photon.Cnds.onJoinedLobby,
		C3.Plugins.Photon.Acts.joinRandomRoom,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Photon.Cnds.onJoinRandomRoomNoMatchFound,
		C3.Plugins.Photon.Acts.createRoom,
		C3.Plugins.Photon.Cnds.onJoinRoom,
		C3.Plugins.Photon.Exps.MyRoomName,
		C3.Plugins.Photon.Cnds.onActorLeave,
		C3.Plugins.Photon.Exps.ActorNr,
		C3.Plugins.Photon.Cnds.onError,
		C3.Plugins.Photon.Exps.ErrorMessage,
		C3.Plugins.Photon.Exps.ErrorCode,
		C3.Plugins.Photon.Cnds.onDisconnected,
		C3.Plugins.Browser.Cnds.OnPageHidden,
		C3.Plugins.Photon.Acts.disconnect,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.Scroll,
		C3.Behaviors.Car.Acts.SetMaxSpeed,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.Touch.Exps.AbsoluteX,
		C3.Plugins.Touch.Exps.AbsoluteY,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Function.Exps.ReturnValue,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Photon.Acts.reset,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Plugins.Audio.Acts.SetListenerObject,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Behaviors.Car.Acts.SetSpeed,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.NinePatch.Acts.SetSize
	];
};
self.C3_JsPropNameTable = [
	{type: 0},
	{speed: 0},
	{actorNr: 0},
	{local: 0},
	{Name: 0},
	{Falling: 0},
	{health: 0},
	{ang: 0},
	{Alive: 0},
	{Killer_ID: 0},
	{signal: 0},
	{Sine: 0},
	{Car: 0},
	{Wrap: 0},
	{Jets: 0},
	{bg: 0},
	{Photon: 0},
	{Function: 0},
	{Log: 0},
	{Mouse: 0},
	{tmpArr: 0},
	{FishLabel: 0},
	{WrongLayoutWarn: 0},
	{Touch: 0},
	{Pin: 0},
	{TextBox: 0},
	{Keyboard: 0},
	{ID: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Fade: 0},
	{fire: 0},
	{shoot: 0},
	{healthBar: 0},
	{healthBarTop: 0},
	{Explosion: 0},
	{Flame: 0},
	{Clouds: 0},
	{px1: 0},
	{px2: 0},
	{FG: 0},
	{Col_death: 0},
	{Col_bounce: 0},
	{Rotate: 0},
	{smoke: 0},
	{Radar: 0},
	{dots: 0},
	{ashes: 0},
	{Buildings: 0},
	{misslieST: 0},
	{LineOfSight: 0},
	{misslieRD: 0},
	{missle: 0},
	{missline: 0},
	{smoke2: 0},
	{Controllaer: 0},
	{State: 0},
	{touchDetec: 0},
	{Weapons_Btn: 0},
	{Bgmenu: 0},
	{Statuc: 0},
	{Btn: 0},
	{Browser: 0},
	{box_tx: 0},
	{Dark: 0},
	{Data: 0},
	{Info: 0},
	{Missile_dot: 0},
	{Title: 0},
	{photonIcon: 0},
	{items: 0},
	{Of: 0},
	{weaponCount: 0},
	{itemDots: 0},
	{Dictionary: 0},
	{LocalStorage: 0},
	{Action: 0},
	{toggle_btn: 0},
	{Audio: 0},
	{orange: 0},
	{logo: 0},
	{ve: 0},
	{Guide01: 0},
	{RDmissile: 0},
	{STmissile: 0},
	{chaling: 0},
	{Dies: 0},
	{Kills: 0},
	{Game: 0},
	{Zoom: 0},
	{jet_type: 0}
];

self.InstanceType = {
	Jets: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	Photon: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Log: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	tmpArr: class extends self.IArrayInstance {},
	FishLabel: class extends self.ITextInstance {},
	WrongLayoutWarn: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	TextBox: class extends self.ITextInputInstance {},
	Keyboard: class extends self.IInstance {},
	fire: class extends self.ISpriteInstance {},
	shoot: class extends self.ISpriteInstance {},
	healthBar: class extends self.ITiledBackgroundInstance {},
	healthBarTop: class extends self.ITiledBackgroundInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Flame: class extends self.ISpriteInstance {},
	Clouds: class extends self.ITiledBackgroundInstance {},
	px1: class extends self.ITiledBackgroundInstance {},
	px2: class extends self.ITiledBackgroundInstance {},
	FG: class extends self.ITiledBackgroundInstance {},
	Col_death: class extends self.ITiledBackgroundInstance {},
	Col_bounce: class extends self.ITiledBackgroundInstance {},
	smoke: class extends self.ISpriteInstance {},
	Radar: class extends self.ISpriteInstance {},
	dots: class extends self.ISpriteInstance {},
	ashes: class extends self.ISpriteInstance {},
	Buildings: class extends self.ISpriteInstance {},
	misslieST: class extends self.ISpriteInstance {},
	misslieRD: class extends self.ISpriteInstance {},
	missline: class extends self.ITiledBackgroundInstance {},
	smoke2: class extends self.ISpriteInstance {},
	Controllaer: class extends self.ISpriteInstance {},
	touchDetec: class extends self.ITiledBackgroundInstance {},
	Weapons_Btn: class extends self.ISpriteInstance {},
	Bgmenu: class extends self.ISpriteInstance {},
	Btn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	box_tx: class extends self.ISpriteInstance {},
	Dark: class extends self.ITiledBackgroundInstance {},
	Info: class extends self.ITextInstance {},
	Missile_dot: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	photonIcon: class extends self.ISpriteInstance {},
	items: class extends self.ISpriteInstance {},
	weaponCount: class extends self.ITextInstance {},
	itemDots: class extends self.ISpriteInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	LocalStorage: class extends self.IInstance {},
	toggle_btn: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	orange: class extends self.IWorldInstance {},
	logo: class extends self.ISpriteInstance {},
	ve: class extends self.ISpriteInstance {},
	Guide01: class extends self.ISpriteInstance {}
}