const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.LOS,
		C3.Behaviors.Turret,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Particles,
		C3.Behaviors.Physics,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{fone: 0},
	{Твёрдый: 0},
	{OD34SV: 0},
	{base1: 0},
	{block_pol: 0},
	{Текст: 0},
	{ПолеЗрения: 0},
	{Турель: 0},
	{base1_pushka: 0},
	{base2: 0},
	{base2_pushka: 0},
	{txt1_base1: 0},
	{zaryad: 0},
	{ДвижениеК: 0},
	{pushka_base1: 0},
	{shit_base1: 0},
	{shit_base2: 0},
	{txt1_base2: 0},
	{pushka_base2: 0},
	{Поворот: 0},
	{OD34SV2: 0},
	{type: 0},
	{nm_upgrade: 0},
	{Пуля: 0},
	{shar_red: 0},
	{punkt1: 0},
	{OQ5HHX: 0},
	{base1_pulya_update: 0},
	{base2_pulya_update: 0},
	{Синусоида: 0},
	{pushka1: 0},
	{pngwingcom3: 0},
	{pngwingcom4: 0},
	{shar_blue: 0},
	{spawner: 0},
	{giant_zamok: 0},
	{txt_timer_giant: 0},
	{polosa_split: 0},
	{polosa_weapon: 0},
	{polosa_giant: 0},
	{polosa_weapon1: 0},
	{polosa_weapon2: 0},
	{polosa_weapon3: 0},
	{polosa_weapon4: 0},
	{polosa_giant1: 0},
	{polosa_giant2: 0},
	{polosa_giant3: 0},
	{polosa_giant4: 0},
	{txt2: 0},
	{base2_pulya: 0},
	{base1_pulya: 0},
	{punkt2: 0},
	{punkt3: 0},
	{punkt4: 0},
	{punkt5: 0},
	{punkt6: 0},
	{punkt7: 0},
	{punkt8: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{pushka2: 0},
	{pushka3: 0},
	{txt_timer_resp: 0},
	{Аудио: 0},
	{punkt9: 0},
	{punkt10red: 0},
	{punkt11blue: 0},
	{punkt12: 0},
	{punkt_pushk1: 0},
	{punkt_pushk2: 0},
	{punkt_pushk3: 0},
	{SHIT_RED: 0},
	{SHIT_BLUE: 0},
	{Тач: 0},
	{txt_winner: 0},
	{txt_logo1: 0},
	{txt_logo2: 0},
	{СледитьЗа: 0},
	{camera: 0},
	{"5pers_golova": 0},
	{hp: 0},
	{razmer: 0},
	{Платформер: 0},
	{pers1_red: 0},
	{pers2_red: 0},
	{pers3_red: 0},
	{pers4_red: 0},
	{pers1_blue: 0},
	{pers2_blue: 0},
	{pers3_blue: 0},
	{pers4_blue: 0},
	{spray_red_dead: 0},
	{spray_blue_dead: 0},
	{Физика: 0},
	{raketa_red: 0},
	{spray_red_popadanie: 0},
	{spray_blue_popadanie: 0},
	{raketa_blue: 0},
	{polosa_upgrade_red: 0},
	{polosa_upgrade_blue: 0},
	{attack_base_red: 0},
	{attack_base_blue: 0},
	{blue: 0},
	{red: 0},
	{base_red_shit_timer: 0},
	{base_red_shit_colvo: 0},
	{base_red_hp: 0},
	{base_blue_shit_timer: 0},
	{base_blue_shit_colvo: 0},
	{base_blue_hp: 0},
	{giant_block_timer: 0},
	{timer_resp: 0},
	{win: 0}
];

self.InstanceType = {
	fone: class extends self.ISpriteInstance {},
	OD34SV: class extends self.ISpriteInstance {},
	base1: class extends self.ISpriteInstance {},
	block_pol: class extends self.ITiledBackgroundInstance {},
	Текст: class extends self.ITextInstance {},
	base1_pushka: class extends self.ISpriteInstance {},
	base2: class extends self.ISpriteInstance {},
	base2_pushka: class extends self.ISpriteInstance {},
	txt1_base1: class extends self.ITextInstance {},
	pushka_base1: class extends self.ISpriteInstance {},
	shit_base1: class extends self.ISpriteInstance {},
	shit_base2: class extends self.ISpriteInstance {},
	txt1_base2: class extends self.ITextInstance {},
	pushka_base2: class extends self.ISpriteInstance {},
	OD34SV2: class extends self.ISpriteInstance {},
	shar_red: class extends self.ISpriteInstance {},
	punkt1: class extends self.ISpriteInstance {},
	OQ5HHX: class extends self.ISpriteInstance {},
	base1_pulya_update: class extends self.ISpriteInstance {},
	base2_pulya_update: class extends self.ISpriteInstance {},
	pushka1: class extends self.ISpriteInstance {},
	pngwingcom3: class extends self.ISpriteInstance {},
	pngwingcom4: class extends self.ISpriteInstance {},
	shar_blue: class extends self.ISpriteInstance {},
	spawner: class extends self.ISpriteInstance {},
	giant_zamok: class extends self.ISpriteInstance {},
	txt_timer_giant: class extends self.ITextInstance {},
	polosa_split: class extends self.ISpriteInstance {},
	polosa_weapon: class extends self.ISpriteInstance {},
	polosa_giant: class extends self.ISpriteInstance {},
	polosa_weapon1: class extends self.ISpriteInstance {},
	polosa_weapon2: class extends self.ISpriteInstance {},
	polosa_weapon3: class extends self.ISpriteInstance {},
	polosa_weapon4: class extends self.ISpriteInstance {},
	polosa_giant1: class extends self.ISpriteInstance {},
	polosa_giant2: class extends self.ISpriteInstance {},
	polosa_giant3: class extends self.ISpriteInstance {},
	polosa_giant4: class extends self.ISpriteInstance {},
	txt2: class extends self.ITextInstance {},
	base2_pulya: class extends self.ISpriteInstance {},
	base1_pulya: class extends self.ISpriteInstance {},
	punkt2: class extends self.ISpriteInstance {},
	punkt3: class extends self.ISpriteInstance {},
	punkt4: class extends self.ISpriteInstance {},
	punkt5: class extends self.ISpriteInstance {},
	punkt6: class extends self.ISpriteInstance {},
	punkt7: class extends self.ISpriteInstance {},
	punkt8: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	pushka2: class extends self.ISpriteInstance {},
	pushka3: class extends self.ISpriteInstance {},
	txt_timer_resp: class extends self.ITextInstance {},
	Аудио: class extends self.IInstance {},
	punkt9: class extends self.ISpriteInstance {},
	punkt10red: class extends self.ISpriteInstance {},
	punkt11blue: class extends self.ISpriteInstance {},
	punkt12: class extends self.ISpriteInstance {},
	punkt_pushk1: class extends self.ISpriteInstance {},
	punkt_pushk2: class extends self.ISpriteInstance {},
	punkt_pushk3: class extends self.ISpriteInstance {},
	SHIT_RED: class extends self.ISpriteInstance {},
	SHIT_BLUE: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	txt_winner: class extends self.ITextInstance {},
	txt_logo1: class extends self.ITextInstance {},
	txt_logo2: class extends self.ITextInstance {},
	camera: class extends self.ISpriteInstance {},
	_5pers_golova: class extends self.ISpriteInstance {},
	pers1_red: class extends self.ISpriteInstance {},
	pers2_red: class extends self.ISpriteInstance {},
	pers3_red: class extends self.ISpriteInstance {},
	pers4_red: class extends self.ISpriteInstance {},
	pers1_blue: class extends self.ISpriteInstance {},
	pers2_blue: class extends self.ISpriteInstance {},
	pers3_blue: class extends self.ISpriteInstance {},
	pers4_blue: class extends self.ISpriteInstance {},
	spray_red_dead: class extends self.IParticlesInstance {},
	spray_blue_dead: class extends self.IParticlesInstance {},
	raketa_red: class extends self.ISpriteInstance {},
	spray_red_popadanie: class extends self.IParticlesInstance {},
	spray_blue_popadanie: class extends self.IParticlesInstance {},
	raketa_blue: class extends self.ISpriteInstance {},
	polosa_upgrade_red: class extends self.ISpriteInstance {},
	polosa_upgrade_blue: class extends self.ISpriteInstance {},
	attack_base_red: class extends self.ISpriteInstance {},
	attack_base_blue: class extends self.ISpriteInstance {},
	blue: class extends self.ISpriteInstance {},
	red: class extends self.ISpriteInstance {}
}