const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Behaviors.Fade,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.Persist,
		C3.Plugins.TiledBg,
		C3.Behaviors.bound,
		C3.Behaviors.Pin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Physics,
		C3.Behaviors.LOS,
		C3.Behaviors.Rotate,
		C3.Behaviors.scrollto,
		C3.Plugins.LocalStorage,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Spritefont2.Exps.TextWidth,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Behaviors.Physics.Cnds.CompareVelocity
	];
};
self.C3_JsPropNameTable = [
	{GameTittle: 0},
	{Touch: 0},
	{Audio: 0},
	{Browser: 0},
	{Fade: 0},
	{SoundUI: 0},
	{Keyboard: 0},
	{RotateScreen: 0},
	{Sine: 0},
	{Grass1: 0},
	{MenuRod: 0},
	{WaterSplash: 0},
	{BloodParticles: 0},
	{SmokeEffect: 0},
	{ElectroEffect: 0},
	{CompanyLogo: 0},
	{PlayButtonMenu: 0},
	{MenuDock: 0},
	{MenuBackground: 0},
	{GameLand: 0},
	{MenuCloud1: 0},
	{MenuCloud2: 0},
	{Sine2: 0},
	{MenuWater1: 0},
	{MenuWater2: 0},
	{CatHeadMenu: 0},
	{CatBodyMenu: 0},
	{CatTailMenu: 0},
	{CatArm1Menu: 0},
	{CatArm1Menu2: 0},
	{CatShotgunMenu: 0},
	{MenuShadowCat: 0},
	{GameDock: 0},
	{Persist: 0},
	{GameCloud1: 0},
	{GameCloud2: 0},
	{GameSun: 0},
	{ShopFront: 0},
	{ShopBack: 0},
	{GameWaterUp: 0},
	{GameWaterFront: 0},
	{GameSkyBackground: 0},
	{GameWater: 0},
	{BoundToLayout: 0},
	{Hook: 0},
	{Pin: 0},
	{RodLine: 0},
	{CoinUI: 0},
	{MaxDistance: 0},
	{HookDistance: 0},
	{CoinFont: 0},
	{GameCat: 0},
	{Bubble1: 0},
	{Bubble2: 0},
	{Bubble3: 0},
	{Movement: 0},
	{speed: 0},
	{Physics: 0},
	{Fish1: 0},
	{Fish2: 0},
	{Fish3: 0},
	{Fish4: 0},
	{Fish5: 0},
	{Fish6: 0},
	{Fish7: 0},
	{Fish8: 0},
	{LineOfSight: 0},
	{Fish9: 0},
	{Rotate: 0},
	{Fish10: 0},
	{SeaWall1: 0},
	{SeaWall2: 0},
	{Fish11: 0},
	{Fish12: 0},
	{BottonSea: 0},
	{Treasure: 0},
	{WallsCollition: 0},
	{ScrollTo: 0},
	{FishCamera: 0},
	{Scorex2: 0},
	{WeaponRange: 0},
	{Scorex5: 0},
	{Scorex10: 0},
	{Scorex15: 0},
	{Scorex25: 0},
	{Scorex40: 0},
	{Scorex80: 0},
	{Scorex100: 0},
	{Scorex150: 0},
	{Scorex250: 0},
	{Scorex400: 0},
	{Scorex1000: 0},
	{ButtonShop: 0},
	{ShopDog: 0},
	{TutoTalk1: 0},
	{TutoTalk2: 0},
	{TutoTalk3: 0},
	{TutoTalk4: 0},
	{LaunchTutorial: 0},
	{MoveHookTutorial: 0},
	{ShootingTutorial: 0},
	{EndTutorial: 0},
	{ShopBackground: 0},
	{LineUpgrade1: 0},
	{LineBuy1: 0},
	{LineUpgrade2: 0},
	{LineBuy2: 0},
	{LineUpgrade3: 0},
	{LineBuy3: 0},
	{LineUpgrade4: 0},
	{LineBuy4: 0},
	{LineUpgrade5: 0},
	{LineBuy5: 0},
	{CloseShop: 0},
	{GunUpgrade1: 0},
	{GunBuy2: 0},
	{GunUpgrade2: 0},
	{GunUpgrade3: 0},
	{GunBuy3: 0},
	{GunUpgrade4: 0},
	{GunBuy4: 0},
	{GunUpgrade5: 0},
	{GunBuy5: 0},
	{GunBuy1: 0},
	{BoosterUpgrade1: 0},
	{BoosterBuy1: 0},
	{BoosterUpgrade2: 0},
	{BoosterBuy2: 0},
	{BoosterUpgrade3: 0},
	{BoosterBuy3: 0},
	{BoosterUpgrade4: 0},
	{BoosterBuy4: 0},
	{BoosterUpgrade5: 0},
	{BoosterBuy5: 0},
	{LightUpgrade: 0},
	{LightBuy: 0},
	{Light: 0},
	{Electro: 0},
	{ElectroUpgrade: 0},
	{ElectroBuy: 0},
	{ShopTalk1: 0},
	{ShopTalk3: 0},
	{ShopTalk4: 0},
	{ShopTalk2: 0},
	{CharTalk1: 0},
	{CharTalk2: 0},
	{CharTalk3: 0},
	{CharTalk4: 0},
	{MenuLightFlare: 0},
	{BackButton: 0},
	{GameCompleted: 0},
	{FaderScreen: 0},
	{LocalStorage: 0},
	{Текст: 0},
	{Bubbles: 0},
	{Fishes: 0},
	{ScoreX: 0},
	{CharTalk: 0},
	{ShopTalk: 0},
	{ReadyToShot: 0},
	{Talk: 0},
	{Line1: 0},
	{Line2: 0},
	{Line3: 0},
	{Line4: 0},
	{Line5: 0},
	{Booster: 0},
	{Weapon5: 0},
	{Weapon4: 0},
	{Weapon3: 0},
	{Weapon2: 0},
	{Shop: 0},
	{WeaponSelected: 0},
	{WaveOver: 0},
	{LineUpgrade: 0},
	{GameMode: 0},
	{HookSpeed: 0},
	{Sound: 0},
	{Boost1: 0},
	{Boost2: 0},
	{Boost3: 0},
	{Boost4: 0},
	{Boost5: 0},
	{Coins: 0},
	{IsScreenRotate: 0}
];

self.InstanceType = {
	GameTittle: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	SoundUI: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	RotateScreen: class extends self.ISpriteInstance {},
	Grass1: class extends self.ISpriteInstance {},
	MenuRod: class extends self.ISpriteInstance {},
	WaterSplash: class extends self.ISpriteInstance {},
	BloodParticles: class extends self.IParticlesInstance {},
	SmokeEffect: class extends self.ISpriteInstance {},
	ElectroEffect: class extends self.ISpriteInstance {},
	CompanyLogo: class extends self.ISpriteInstance {},
	PlayButtonMenu: class extends self.ISpriteInstance {},
	MenuDock: class extends self.ISpriteInstance {},
	MenuBackground: class extends self.ISpriteInstance {},
	GameLand: class extends self.ISpriteInstance {},
	MenuCloud1: class extends self.ISpriteInstance {},
	MenuCloud2: class extends self.ISpriteInstance {},
	MenuWater1: class extends self.ISpriteInstance {},
	MenuWater2: class extends self.ISpriteInstance {},
	CatHeadMenu: class extends self.ISpriteInstance {},
	CatBodyMenu: class extends self.ISpriteInstance {},
	CatTailMenu: class extends self.ISpriteInstance {},
	CatArm1Menu: class extends self.ISpriteInstance {},
	CatArm1Menu2: class extends self.ISpriteInstance {},
	CatShotgunMenu: class extends self.ISpriteInstance {},
	MenuShadowCat: class extends self.ISpriteInstance {},
	GameDock: class extends self.ISpriteInstance {},
	GameCloud1: class extends self.ISpriteInstance {},
	GameCloud2: class extends self.ISpriteInstance {},
	GameSun: class extends self.ISpriteInstance {},
	ShopFront: class extends self.ISpriteInstance {},
	ShopBack: class extends self.ISpriteInstance {},
	GameWaterUp: class extends self.ISpriteInstance {},
	GameWaterFront: class extends self.ISpriteInstance {},
	GameSkyBackground: class extends self.ITiledBackgroundInstance {},
	GameWater: class extends self.ISpriteInstance {},
	Hook: class extends self.ISpriteInstance {},
	RodLine: class extends self.ISpriteInstance {},
	CoinUI: class extends self.ISpriteInstance {},
	MaxDistance: class extends self.ISpriteInstance {},
	HookDistance: class extends self.ISpriteFontInstance {},
	CoinFont: class extends self.ISpriteFontInstance {},
	GameCat: class extends self.ISpriteInstance {},
	Bubble1: class extends self.ISpriteInstance {},
	Bubble2: class extends self.ISpriteInstance {},
	Bubble3: class extends self.ISpriteInstance {},
	Fish1: class extends self.ISpriteInstance {},
	Fish2: class extends self.ISpriteInstance {},
	Fish3: class extends self.ISpriteInstance {},
	Fish4: class extends self.ISpriteInstance {},
	Fish5: class extends self.ISpriteInstance {},
	Fish6: class extends self.ISpriteInstance {},
	Fish7: class extends self.ISpriteInstance {},
	Fish8: class extends self.ISpriteInstance {},
	Fish9: class extends self.ISpriteInstance {},
	Fish10: class extends self.ISpriteInstance {},
	SeaWall1: class extends self.ITiledBackgroundInstance {},
	SeaWall2: class extends self.ITiledBackgroundInstance {},
	Fish11: class extends self.ISpriteInstance {},
	Fish12: class extends self.ISpriteInstance {},
	BottonSea: class extends self.ISpriteInstance {},
	Treasure: class extends self.ISpriteInstance {},
	WallsCollition: class extends self.ISpriteInstance {},
	FishCamera: class extends self.ISpriteInstance {},
	Scorex2: class extends self.ISpriteInstance {},
	WeaponRange: class extends self.ISpriteInstance {},
	Scorex5: class extends self.ISpriteInstance {},
	Scorex10: class extends self.ISpriteInstance {},
	Scorex15: class extends self.ISpriteInstance {},
	Scorex25: class extends self.ISpriteInstance {},
	Scorex40: class extends self.ISpriteInstance {},
	Scorex80: class extends self.ISpriteInstance {},
	Scorex100: class extends self.ISpriteInstance {},
	Scorex150: class extends self.ISpriteInstance {},
	Scorex250: class extends self.ISpriteInstance {},
	Scorex400: class extends self.ISpriteInstance {},
	Scorex1000: class extends self.ISpriteInstance {},
	ButtonShop: class extends self.ISpriteInstance {},
	ShopDog: class extends self.ISpriteInstance {},
	TutoTalk1: class extends self.ISpriteInstance {},
	TutoTalk2: class extends self.ISpriteInstance {},
	TutoTalk3: class extends self.ISpriteInstance {},
	TutoTalk4: class extends self.ISpriteInstance {},
	LaunchTutorial: class extends self.ISpriteInstance {},
	MoveHookTutorial: class extends self.ISpriteInstance {},
	ShootingTutorial: class extends self.ISpriteInstance {},
	EndTutorial: class extends self.ISpriteInstance {},
	ShopBackground: class extends self.ISpriteInstance {},
	LineUpgrade1: class extends self.ISpriteInstance {},
	LineBuy1: class extends self.ISpriteInstance {},
	LineUpgrade2: class extends self.ISpriteInstance {},
	LineBuy2: class extends self.ISpriteInstance {},
	LineUpgrade3: class extends self.ISpriteInstance {},
	LineBuy3: class extends self.ISpriteInstance {},
	LineUpgrade4: class extends self.ISpriteInstance {},
	LineBuy4: class extends self.ISpriteInstance {},
	LineUpgrade5: class extends self.ISpriteInstance {},
	LineBuy5: class extends self.ISpriteInstance {},
	CloseShop: class extends self.ISpriteInstance {},
	GunUpgrade1: class extends self.ISpriteInstance {},
	GunBuy2: class extends self.ISpriteInstance {},
	GunUpgrade2: class extends self.ISpriteInstance {},
	GunUpgrade3: class extends self.ISpriteInstance {},
	GunBuy3: class extends self.ISpriteInstance {},
	GunUpgrade4: class extends self.ISpriteInstance {},
	GunBuy4: class extends self.ISpriteInstance {},
	GunUpgrade5: class extends self.ISpriteInstance {},
	GunBuy5: class extends self.ISpriteInstance {},
	GunBuy1: class extends self.ISpriteInstance {},
	BoosterUpgrade1: class extends self.ISpriteInstance {},
	BoosterBuy1: class extends self.ISpriteInstance {},
	BoosterUpgrade2: class extends self.ISpriteInstance {},
	BoosterBuy2: class extends self.ISpriteInstance {},
	BoosterUpgrade3: class extends self.ISpriteInstance {},
	BoosterBuy3: class extends self.ISpriteInstance {},
	BoosterUpgrade4: class extends self.ISpriteInstance {},
	BoosterBuy4: class extends self.ISpriteInstance {},
	BoosterUpgrade5: class extends self.ISpriteInstance {},
	BoosterBuy5: class extends self.ISpriteInstance {},
	LightUpgrade: class extends self.ISpriteInstance {},
	LightBuy: class extends self.ISpriteInstance {},
	Light: class extends self.ISpriteInstance {},
	Electro: class extends self.ISpriteInstance {},
	ElectroUpgrade: class extends self.ISpriteInstance {},
	ElectroBuy: class extends self.ISpriteInstance {},
	ShopTalk1: class extends self.ISpriteInstance {},
	ShopTalk3: class extends self.ISpriteInstance {},
	ShopTalk4: class extends self.ISpriteInstance {},
	ShopTalk2: class extends self.ISpriteInstance {},
	CharTalk1: class extends self.ISpriteInstance {},
	CharTalk2: class extends self.ISpriteInstance {},
	CharTalk3: class extends self.ISpriteInstance {},
	CharTalk4: class extends self.ISpriteInstance {},
	MenuLightFlare: class extends self.ISpriteInstance {},
	BackButton: class extends self.ISpriteInstance {},
	GameCompleted: class extends self.ISpriteInstance {},
	FaderScreen: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Текст: class extends self.ITextInstance {},
	Bubbles: class extends self.ISpriteInstance {},
	Fishes: class extends self.ISpriteInstance {},
	ScoreX: class extends self.ISpriteInstance {},
	CharTalk: class extends self.ISpriteInstance {},
	ShopTalk: class extends self.ISpriteInstance {}
}