const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Function,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.TileMovement,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedPlaying,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose
	];
};
self.C3_JsPropNameTable = [
	{Array: 0},
	{Browser: 0},
	{Function: 0},
	{SwapData: 0},
	{Mouse: 0},
	{Audio: 0},
	{Touch: 0},
	{BestScoreFont: 0},
	{BlocksFont: 0},
	{LastScoreFont: 0},
	{LevelsFont: 0},
	{LoadingFont: 0},
	{MovesFont: 0},
	{ScoreFont: 0},
	{TimerFont: 0},
	{BtnExit: 0},
	{BtnFullscreen: 0},
	{BtnMusic: 0},
	{BtnPause: 0},
	{BtnRestart: 0},
	{BtnMenu: 0},
	{BtnSound: 0},
	{BtnGames: 0},
	{BtnPlay: 0},
	{BtnShare: 0},
	{Matched: 0},
	{Moving: 0},
	{trigger: 0},
	{targetY: 0},
	{row: 0},
	{col: 0},
	{dy: 0},
	{color: 0},
	{State: 0},
	{Fade: 0},
	{Sine: 0},
	{Sine2: 0},
	{Elements: 0},
	{BOOM: 0},
	{ChessMap: 0},
	{Marker: 0},
	{Rotate: 0},
	{Selection: 0},
	{Selection2: 0},
	{Selector: 0},
	{ScoreCollision: 0},
	{Selector2: 0},
	{ZadachaDec1: 0},
	{ZadachaDec2: 0},
	{ZadachaDec3: 0},
	{Якорь: 0},
	{BackgroundGame: 0},
	{Cursor: 0},
	{CursorHover: 0},
	{Anchor: 0},
	{Loading: 0},
	{LoadingBar: 0},
	{LoadingBarBackground: 0},
	{Sun: 0},
	{TimerGui: 0},
	{TimerLine: 0},
	{TimerLine2: 0},
	{Синусоид: 0},
	{Copy: 0},
	{Copy10: 0},
	{Copy100: 0},
	{Copy11: 0},
	{Copy12: 0},
	{Copy13: 0},
	{Copy14: 0},
	{Copy15: 0},
	{Copy16: 0},
	{Copy17: 0},
	{Copy18: 0},
	{Copy19: 0},
	{Copy2: 0},
	{Copy20: 0},
	{Copy21: 0},
	{Copy22: 0},
	{Copy23: 0},
	{Copy24: 0},
	{Copy25: 0},
	{Copy26: 0},
	{Copy27: 0},
	{Copy28: 0},
	{Copy29: 0},
	{Copy3: 0},
	{Copy30: 0},
	{Copy31: 0},
	{Copy32: 0},
	{Copy33: 0},
	{Copy34: 0},
	{Copy35: 0},
	{Copy36: 0},
	{Copy37: 0},
	{Copy38: 0},
	{Copy39: 0},
	{Copy4: 0},
	{Copy40: 0},
	{Copy41: 0},
	{Copy42: 0},
	{Copy43: 0},
	{Copy44: 0},
	{Copy45: 0},
	{Copy46: 0},
	{Copy47: 0},
	{Copy48: 0},
	{Copy49: 0},
	{Copy5: 0},
	{Copy50: 0},
	{Copy51: 0},
	{Copy52: 0},
	{Copy53: 0},
	{Copy54: 0},
	{Copy55: 0},
	{Copy56: 0},
	{Copy57: 0},
	{Copy58: 0},
	{Copy59: 0},
	{Copy6: 0},
	{Copy60: 0},
	{Copy61: 0},
	{Copy62: 0},
	{Copy63: 0},
	{Copy64: 0},
	{Copy65: 0},
	{Copy66: 0},
	{Copy67: 0},
	{Copy68: 0},
	{Copy69: 0},
	{Copy7: 0},
	{Copy70: 0},
	{Copy71: 0},
	{Copy72: 0},
	{Copy73: 0},
	{Copy74: 0},
	{Copy75: 0},
	{Copy76: 0},
	{Copy77: 0},
	{Copy78: 0},
	{Copy79: 0},
	{Copy8: 0},
	{Copy80: 0},
	{Copy81: 0},
	{Copy82: 0},
	{Copy83: 0},
	{Copy84: 0},
	{Copy85: 0},
	{Copy86: 0},
	{Copy87: 0},
	{Copy88: 0},
	{Copy89: 0},
	{Copy9: 0},
	{Copy90: 0},
	{Copy91: 0},
	{Copy92: 0},
	{Copy93: 0},
	{Copy94: 0},
	{Copy95: 0},
	{Copy96: 0},
	{Copy97: 0},
	{Copy98: 0},
	{Copy99: 0},
	{logotype: 0},
	{tochka: 0},
	{image4: 0},
	{image3: 0},
	{image5: 0},
	{txthodi: 0},
	{image6: 0},
	{butreklam: 0},
	{galka1: 0},
	{galka2: 0},
	{galka3: 0},
	{txtzadacha: 0},
	{txtvipolneno2: 0},
	{txtvipolneno3: 0},
	{txtzadacha1: 0},
	{txtzadacha2: 0},
	{txtzadacha3: 0},
	{txt: 0},
	{slash: 0},
	{GamePush: 0},
	{win1okno: 0},
	{winb1: 0},
	{winb2: 0},
	{wintxt1: 0},
	{wintxt2: 0},
	{wintxt: 0},
	{timer: 0},
	{winnertimer: 0},
	{butreklam2: 0},
	{ОбУстройстве: 0},
	{pngwingcom3: 0},
	{povorotfon: 0},
	{decorpovorot: 0},
	{txtpovorot: 0},
	{txtpovorot1: 0},
	{txtpovorot2IOS: 0},
	{pngwingcom6: 0},
	{pngwingcom7: 0},
	{TEST_tile: 0},
	{Угасание: 0},
	{ДвижениеПоКлеткам: 0},
	{bombzone: 0},
	{txtbombs: 0},
	{Синусоид2: 0},
	{Перетаскивание: 0},
	{bombtouch: 0},
	{butreklam3: 0},
	{image16: 0},
	{pngwingcom11: 0},
	{TESTB: 0},
	{pngwingcom14: 0},
	{pngwingcom15: 0},
	{image17: 0},
	{image18: 0},
	{image19: 0},
	{image20: 0},
	{image21: 0},
	{image22: 0},
	{pngwingcom17: 0},
	{pngwingcom18: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{подпись: 0},
	{image23: 0},
	{pngwingcom19: 0},
	{Спрайт6: 0},
	{Текст: 0},
	{zamokbombi: 0},
	{pngwingcom21: 0},
	{pngwingcom: 0},
	{txtLevel: 0},
	{camni: 0},
	{pngwingcom2: 0},
	{pngwingcom4: 0},
	{Снимок: 0},
	{image: 0},
	{Спрайт: 0},
	{image2: 0},
	{Спрайт2: 0},
	{BackgroundGame1: 0},
	{image7: 0},
	{videogameitemhourglassisolatedicon_: 0},
	{image8: 0},
	{pngwingcom5: 0},
	{image9: 0},
	{camni2: 0},
	{Текст2: 0},
	{rec: 0},
	{icon: 0},
	{Buttons: 0},
	{CX: 0},
	{CY: 0},
	{Level: 0},
	{Score: 0},
	{Blocks: 0},
	{Moves: 0},
	{Trigger: 0},
	{Minutes: 0},
	{Matches: 0},
	{ScoreBar: 0},
	{Seconds: 0},
	{LastScore: 0},
	{BestScore: 0},
	{FirstPiece: 0},
	{MovingBlocks: 0},
	{TILE: 0},
	{Hodi: 0},
	{vipolneno1: 0},
	{vipolneno2: 0},
	{vipolneno3: 0},
	{zadacha1: 0},
	{zadacha2: 0},
	{zadacha3: 0},
	{LEVELE: 0},
	{"0_win_1_endhodi_2_endtime_3": 0},
	{game_window: 0},
	{reklam_bomb: 0},
	{elementsline1: 0},
	{elementsline2: 0},
	{elementsline3: 0},
	{elementsline4: 0},
	{elementsline5: 0},
	{scoregame: 0},
	{Music: 0},
	{Sound: 0},
	{Fullscreen: 0},
	{TimeScaler: 0},
	{opens_levels: 0},
	{bombs: 0},
	{touch_bomb: 0},
	{Record: 0}
];

self.InstanceType = {
	Array: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	SwapData: class extends self.IArrayInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	BlocksFont: class extends self.ISpriteFontInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	LevelsFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	MovesFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	TimerFont: class extends self.ISpriteFontInstance {},
	BtnExit: class extends self.ISpriteInstance {},
	BtnFullscreen: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnMenu: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	BtnGames: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnShare: class extends self.ISpriteInstance {},
	Elements: class extends self.ISpriteInstance {},
	BOOM: class extends self.ISpriteInstance {},
	ChessMap: class extends self.ISpriteInstance {},
	Marker: class extends self.ISpriteInstance {},
	Selection: class extends self.ISpriteInstance {},
	Selection2: class extends self.ISpriteInstance {},
	Selector: class extends self.ISpriteInstance {},
	ScoreCollision: class extends self.ISpriteInstance {},
	Selector2: class extends self.ISpriteInstance {},
	ZadachaDec1: class extends self.ISpriteInstance {},
	ZadachaDec2: class extends self.ISpriteInstance {},
	ZadachaDec3: class extends self.ISpriteInstance {},
	BackgroundGame: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	Loading: class extends self.ISpriteInstance {},
	LoadingBar: class extends self.ISpriteInstance {},
	LoadingBarBackground: class extends self.ISpriteInstance {},
	Sun: class extends self.ISpriteInstance {},
	TimerGui: class extends self.ISpriteInstance {},
	TimerLine: class extends self.ITiledBackgroundInstance {},
	TimerLine2: class extends self.ITiledBackgroundInstance {},
	Copy: class extends self.ISpriteInstance {},
	Copy10: class extends self.ISpriteInstance {},
	Copy100: class extends self.ISpriteInstance {},
	Copy11: class extends self.ISpriteInstance {},
	Copy12: class extends self.ISpriteInstance {},
	Copy13: class extends self.ISpriteInstance {},
	Copy14: class extends self.ISpriteInstance {},
	Copy15: class extends self.ISpriteInstance {},
	Copy16: class extends self.ISpriteInstance {},
	Copy17: class extends self.ISpriteInstance {},
	Copy18: class extends self.ISpriteInstance {},
	Copy19: class extends self.ISpriteInstance {},
	Copy2: class extends self.ISpriteInstance {},
	Copy20: class extends self.ISpriteInstance {},
	Copy21: class extends self.ISpriteInstance {},
	Copy22: class extends self.ISpriteInstance {},
	Copy23: class extends self.ISpriteInstance {},
	Copy24: class extends self.ISpriteInstance {},
	Copy25: class extends self.ISpriteInstance {},
	Copy26: class extends self.ISpriteInstance {},
	Copy27: class extends self.ISpriteInstance {},
	Copy28: class extends self.ISpriteInstance {},
	Copy29: class extends self.ISpriteInstance {},
	Copy3: class extends self.ISpriteInstance {},
	Copy30: class extends self.ISpriteInstance {},
	Copy31: class extends self.ISpriteInstance {},
	Copy32: class extends self.ISpriteInstance {},
	Copy33: class extends self.ISpriteInstance {},
	Copy34: class extends self.ISpriteInstance {},
	Copy35: class extends self.ISpriteInstance {},
	Copy36: class extends self.ISpriteInstance {},
	Copy37: class extends self.ISpriteInstance {},
	Copy38: class extends self.ISpriteInstance {},
	Copy39: class extends self.ISpriteInstance {},
	Copy4: class extends self.ISpriteInstance {},
	Copy40: class extends self.ISpriteInstance {},
	Copy41: class extends self.ISpriteInstance {},
	Copy42: class extends self.ISpriteInstance {},
	Copy43: class extends self.ISpriteInstance {},
	Copy44: class extends self.ISpriteInstance {},
	Copy45: class extends self.ISpriteInstance {},
	Copy46: class extends self.ISpriteInstance {},
	Copy47: class extends self.ISpriteInstance {},
	Copy48: class extends self.ISpriteInstance {},
	Copy49: class extends self.ISpriteInstance {},
	Copy5: class extends self.ISpriteInstance {},
	Copy50: class extends self.ISpriteInstance {},
	Copy51: class extends self.ISpriteInstance {},
	Copy52: class extends self.ISpriteInstance {},
	Copy53: class extends self.ISpriteInstance {},
	Copy54: class extends self.ISpriteInstance {},
	Copy55: class extends self.ISpriteInstance {},
	Copy56: class extends self.ISpriteInstance {},
	Copy57: class extends self.ISpriteInstance {},
	Copy58: class extends self.ISpriteInstance {},
	Copy59: class extends self.ISpriteInstance {},
	Copy6: class extends self.ISpriteInstance {},
	Copy60: class extends self.ISpriteInstance {},
	Copy61: class extends self.ISpriteInstance {},
	Copy62: class extends self.ISpriteInstance {},
	Copy63: class extends self.ISpriteInstance {},
	Copy64: class extends self.ISpriteInstance {},
	Copy65: class extends self.ISpriteInstance {},
	Copy66: class extends self.ISpriteInstance {},
	Copy67: class extends self.ISpriteInstance {},
	Copy68: class extends self.ISpriteInstance {},
	Copy69: class extends self.ISpriteInstance {},
	Copy7: class extends self.ISpriteInstance {},
	Copy70: class extends self.ISpriteInstance {},
	Copy71: class extends self.ISpriteInstance {},
	Copy72: class extends self.ISpriteInstance {},
	Copy73: class extends self.ISpriteInstance {},
	Copy74: class extends self.ISpriteInstance {},
	Copy75: class extends self.ISpriteInstance {},
	Copy76: class extends self.ISpriteInstance {},
	Copy77: class extends self.ISpriteInstance {},
	Copy78: class extends self.ISpriteInstance {},
	Copy79: class extends self.ISpriteInstance {},
	Copy8: class extends self.ISpriteInstance {},
	Copy80: class extends self.ISpriteInstance {},
	Copy81: class extends self.ISpriteInstance {},
	Copy82: class extends self.ISpriteInstance {},
	Copy83: class extends self.ISpriteInstance {},
	Copy84: class extends self.ISpriteInstance {},
	Copy85: class extends self.ISpriteInstance {},
	Copy86: class extends self.ISpriteInstance {},
	Copy87: class extends self.ISpriteInstance {},
	Copy88: class extends self.ISpriteInstance {},
	Copy89: class extends self.ISpriteInstance {},
	Copy9: class extends self.ISpriteInstance {},
	Copy90: class extends self.ISpriteInstance {},
	Copy91: class extends self.ISpriteInstance {},
	Copy92: class extends self.ISpriteInstance {},
	Copy93: class extends self.ISpriteInstance {},
	Copy94: class extends self.ISpriteInstance {},
	Copy95: class extends self.ISpriteInstance {},
	Copy96: class extends self.ISpriteInstance {},
	Copy97: class extends self.ISpriteInstance {},
	Copy98: class extends self.ISpriteInstance {},
	Copy99: class extends self.ISpriteInstance {},
	logotype: class extends self.ISpriteInstance {},
	tochka: class extends self.ISpriteInstance {},
	image4: class extends self.ISpriteInstance {},
	image3: class extends self.ISpriteInstance {},
	image5: class extends self.ISpriteInstance {},
	txthodi: class extends self.ITextInstance {},
	image6: class extends self.ISpriteInstance {},
	butreklam: class extends self.ISpriteInstance {},
	galka1: class extends self.ISpriteInstance {},
	galka2: class extends self.ISpriteInstance {},
	galka3: class extends self.ISpriteInstance {},
	txtzadacha: class extends self.ITextInstance {},
	txtvipolneno2: class extends self.ITextInstance {},
	txtvipolneno3: class extends self.ITextInstance {},
	txtzadacha1: class extends self.ITextInstance {},
	txtzadacha2: class extends self.ITextInstance {},
	txtzadacha3: class extends self.ITextInstance {},
	txt: class extends self.ITextInstance {},
	slash: class extends self.ITextInstance {},
	GamePush: class extends self.IInstance {},
	win1okno: class extends self.ISpriteInstance {},
	winb1: class extends self.ISpriteInstance {},
	winb2: class extends self.ISpriteInstance {},
	wintxt1: class extends self.ISpriteInstance {},
	wintxt2: class extends self.ISpriteInstance {},
	wintxt: class extends self.ITextInstance {},
	timer: class extends self.ISpriteInstance {},
	winnertimer: class extends self.ISpriteInstance {},
	butreklam2: class extends self.ISpriteInstance {},
	ОбУстройстве: class extends self.IInstance {},
	pngwingcom3: class extends self.ISpriteInstance {},
	povorotfon: class extends self.ISpriteInstance {},
	decorpovorot: class extends self.ISpriteInstance {},
	txtpovorot: class extends self.ITextInstance {},
	txtpovorot1: class extends self.ISpriteInstance {},
	txtpovorot2IOS: class extends self.ISpriteInstance {},
	pngwingcom6: class extends self.ISpriteInstance {},
	pngwingcom7: class extends self.ISpriteInstance {},
	TEST_tile: class extends self.ITextInstance {},
	bombzone: class extends self.ISpriteInstance {},
	txtbombs: class extends self.ITextInstance {},
	bombtouch: class extends self.ISpriteInstance {},
	butreklam3: class extends self.ISpriteInstance {},
	image16: class extends self.ISpriteInstance {},
	pngwingcom11: class extends self.ISpriteInstance {},
	TESTB: class extends self.ITextInstance {},
	pngwingcom14: class extends self.ISpriteInstance {},
	pngwingcom15: class extends self.ISpriteInstance {},
	image17: class extends self.ISpriteInstance {},
	image18: class extends self.ISpriteInstance {},
	image19: class extends self.ISpriteInstance {},
	image20: class extends self.ISpriteInstance {},
	image21: class extends self.ISpriteInstance {},
	image22: class extends self.ISpriteInstance {},
	pngwingcom17: class extends self.ISpriteInstance {},
	pngwingcom18: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	подпись: class extends self.ISpriteInstance {},
	image23: class extends self.ISpriteInstance {},
	pngwingcom19: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	zamokbombi: class extends self.ISpriteInstance {},
	pngwingcom21: class extends self.ISpriteInstance {},
	pngwingcom: class extends self.ISpriteInstance {},
	txtLevel: class extends self.ITextInstance {},
	camni: class extends self.ISpriteInstance {},
	pngwingcom2: class extends self.ISpriteInstance {},
	pngwingcom4: class extends self.ISpriteInstance {},
	Снимок: class extends self.ISpriteInstance {},
	image: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	image2: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	BackgroundGame1: class extends self.ISpriteInstance {},
	image7: class extends self.ISpriteInstance {},
	videogameitemhourglassisolatedicon_: class extends self.ISpriteInstance {},
	image8: class extends self.ISpriteInstance {},
	pngwingcom5: class extends self.ISpriteInstance {},
	image9: class extends self.ISpriteInstance {},
	camni2: class extends self.ISpriteInstance {},
	Текст2: class extends self.ITextInstance {},
	rec: class extends self.ITextInstance {},
	icon: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {}
}