const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.TiledBg,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Behaviors.LOS,
		C3.Behaviors.Physics,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Plugins.Particles,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Sin.Acts.UpdateInitialState,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.Bounce,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.solid.Cnds.IsEnabled,
		C3.Plugins.System.Acts.SaveState,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Browser.Cnds.WindowHasFocus,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Eponesh_GameScore.Cnds.Language
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{GamePush: 0},
	{Браузер: 0},
	{Аудио: 0},
	{Text: 0},
	{TextR: 0},
	{hp: 0},
	{Твёрдый: 0},
	{block1: 0},
	{СледитьЗа: 0},
	{ДвижениеК: 0},
	{camera: 0},
	{Платформер: 0},
	{ОграничитьСценой: 0},
	{Мигание: 0},
	{Steve: 0},
	{block2: 0},
	{block3: 0},
	{СквознаяПлатформа: 0},
	{block4: 0},
	{block5: 0},
	{block11: 0},
	{block6: 0},
	{block7: 0},
	{block8: 0},
	{portal1: 0},
	{ec9089b4018e920bd42879af3b: 0},
	{block10: 0},
	{block12: 0},
	{blocksss: 0},
	{block13: 0},
	{blocksss3: 0},
	{blocksss4: 0},
	{d8pcc9bab2cf0edb2ee4c5381a0290fdc6c2: 0},
	{d8pcc9bab2cf0edb2ee4c5381a0290fdc6c3: 0},
	{Якорь: 0},
	{position1: 0},
	{position2: 0},
	{leftN1: 0},
	{leftN2: 0},
	{leftN3: 0},
	{dist: 0},
	{ang: 0},
	{Big: 0},
	{Small: 0},
	{Синусоида: 0},
	{Поворот: 0},
	{ruka1: 0},
	{winterlightbluegradientvectorbackground_: 0},
	{ruka2: 0},
	{line: 0},
	{shop: 0},
	{ТайловыйФон: 0},
	{block14: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{fon_menu: 0},
	{int1: 0},
	{w061n0055Bp2: 0},
	{txt_coin: 0},
	{int2: 0},
	{int3: 0},
	{int4: 0},
	{int5: 0},
	{Nut_May_: 0},
	{b_play: 0},
	{iconka_button_attack: 0},
	{But_attack: 0},
	{txt_play: 0},
	{b_play2: 0},
	{txt_play2: 0},
	{block15: 0},
	{zone_joy: 0},
	{zone_joy2: 0},
	{dver: 0},
	{krovat: 0},
	{hp_icons: 0},
	{ОбУстройстве: 0},
	{Клавиатура: 0},
	{Мышь: 0},
	{svitok: 0},
	{txt_svitok: 0},
	{quest_txt: 0},
	{quest_txt2: 0},
	{blocksss5: 0},
	{interface_derevo: 0},
	{Прикрепить: 0},
	{kirka_mech: 0},
	{minecraftswordsminecrafttheultimatecombatguideminecraftsecrets: 0},
	{txt_yicheika1: 0},
	{txt_yicheika2: 0},
	{txt_yicheika3: 0},
	{txt_yicheika4: 0},
	{txt_yicheika5: 0},
	{blocksss6: 0},
	{block16: 0},
	{ТайловыйФон2: 0},
	{boss_issushitel: 0},
	{blockADD2: 0},
	{blockADD1: 0},
	{ТайловыйФон3: 0},
	{stroyka: 0},
	{lava: 0},
	{shop_okno: 0},
	{b_shop_close: 0},
	{txt_shop: 0},
	{txt_shop1: 0},
	{shop_prodazha: 0},
	{but_obshenie: 0},
	{but_smena: 0},
	{but_v_menu: 0},
	{shopmech: 0},
	{shopKirka: 0},
	{pokupkaKirka: 0},
	{pokupkaMech: 0},
	{svitok_shop: 0},
	{pokupkaSvitok: 0},
	{iconka_ad: 0},
	{ad_txt: 0},
	{uvidel: 0},
	{patrul: 0},
	{timer: 0},
	{ПолеЗрения: 0},
	{mob_zombie: 0},
	{Физика: 0},
	{Угасание: 0},
	{txt_hp: 0},
	{line_boss: 0},
	{txt_boss: 0},
	{boss_punkt1: 0},
	{boss_punkt2: 0},
	{boss_punkt3: 0},
	{Пуля: 0},
	{boss_shar: 0},
	{boss_chastici: 0},
	{portal3: 0},
	{ЛокальноеХранилище: 0},
	{block_lestnice: 0},
	{portal2: 0},
	{punkt1: 0},
	{punkt2: 0},
	{punkt3: 0},
	{HUD_lestn: 0},
	{lestnica: 0},
	{But_attack2: 0},
	{but_jump: 0},
	{iconka_ad2: 0},
	{ad_txt2: 0},
	{w061n0055Bp3: 0},
	{txt_zadacha: 0},
	{But_attack3: 0},
	{b_zadacha: 0},
	{But_attack4: 0},
	{But_attack5: 0},
	{b_tgm: 0},
	{shop_okno2: 0},
	{shop_okno3: 0},
	{shop_okno4: 0},
	{fail_okno: 0},
	{fail_but: 0},
	{txt_fail: 0},
	{sound: 0},
	{music: 0},
	{menu: 0},
	{"1ugol": 0},
	{"2zhelezo": 0},
	{"3zoloto": 0},
	{"4almaz": 0},
	{"5doski": 0},
	{kirka: 0},
	{weapon: 0},
	{vibrano: 0},
	{coins: 0},
	{uron: 0},
	{HP: 0},
	{shop_cena1: 0},
	{shop_cena2: 0},
	{kupleno: 0},
	{kupleno2: 0},
	{obshaya_cena_prodazhi: 0},
	{quest: 0},
	{boss_dead: 0},
	{boss_hp: 0},
	{boss_active: 0},
	{boss_attack: 0},
	{world: 0},
	{saved: 0},
	{zadacha: 0},
	{deades: 0},
	{mus_variation: 0},
	{Lang: 0},
	{AD: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	GamePush: class extends self.IInstance {},
	Браузер: class extends self.IInstance {},
	Аудио: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	TextR: class extends self.ITextInstance {},
	block1: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	Steve: class extends self.ISpriteInstance {},
	block2: class extends self.ISpriteInstance {},
	block3: class extends self.ISpriteInstance {},
	block4: class extends self.ISpriteInstance {},
	block5: class extends self.ISpriteInstance {},
	block11: class extends self.ISpriteInstance {},
	block6: class extends self.ISpriteInstance {},
	block7: class extends self.ISpriteInstance {},
	block8: class extends self.ISpriteInstance {},
	portal1: class extends self.ISpriteInstance {},
	ec9089b4018e920bd42879af3b: class extends self.ISpriteInstance {},
	block10: class extends self.ISpriteInstance {},
	block12: class extends self.ISpriteInstance {},
	blocksss: class extends self.ISpriteInstance {},
	block13: class extends self.ISpriteInstance {},
	blocksss3: class extends self.ISpriteInstance {},
	blocksss4: class extends self.ISpriteInstance {},
	d8pcc9bab2cf0edb2ee4c5381a0290fdc6c2: class extends self.ISpriteInstance {},
	d8pcc9bab2cf0edb2ee4c5381a0290fdc6c3: class extends self.ISpriteInstance {},
	position1: class extends self.ISpriteInstance {},
	position2: class extends self.ISpriteInstance {},
	leftN1: class extends self.ISpriteInstance {},
	leftN2: class extends self.ISpriteInstance {},
	leftN3: class extends self.ISpriteInstance {},
	Big: class extends self.ISpriteInstance {},
	Small: class extends self.ISpriteInstance {},
	ruka1: class extends self.ISpriteInstance {},
	winterlightbluegradientvectorbackground_: class extends self.ISpriteInstance {},
	ruka2: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	shop: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	block14: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	fon_menu: class extends self.ISpriteInstance {},
	int1: class extends self.ISpriteInstance {},
	w061n0055Bp2: class extends self.ISpriteInstance {},
	txt_coin: class extends self.ITextInstance {},
	int2: class extends self.ISpriteInstance {},
	int3: class extends self.ISpriteInstance {},
	int4: class extends self.ISpriteInstance {},
	int5: class extends self.ISpriteInstance {},
	Nut_May_: class extends self.ISpriteInstance {},
	b_play: class extends self.ISpriteInstance {},
	iconka_button_attack: class extends self.ISpriteInstance {},
	But_attack: class extends self.ISpriteInstance {},
	txt_play: class extends self.ITextInstance {},
	b_play2: class extends self.ISpriteInstance {},
	txt_play2: class extends self.ITextInstance {},
	block15: class extends self.ISpriteInstance {},
	zone_joy: class extends self.ISpriteInstance {},
	zone_joy2: class extends self.ISpriteInstance {},
	dver: class extends self.ISpriteInstance {},
	krovat: class extends self.ISpriteInstance {},
	hp_icons: class extends self.ISpriteInstance {},
	ОбУстройстве: class extends self.IInstance {},
	Клавиатура: class extends self.IInstance {},
	Мышь: class extends self.IInstance {},
	svitok: class extends self.ISpriteInstance {},
	txt_svitok: class extends self.ITextInstance {},
	quest_txt: class extends self.ITextInstance {},
	quest_txt2: class extends self.ITextInstance {},
	blocksss5: class extends self.ISpriteInstance {},
	interface_derevo: class extends self.ISpriteInstance {},
	kirka_mech: class extends self.ISpriteInstance {},
	minecraftswordsminecrafttheultimatecombatguideminecraftsecrets: class extends self.ISpriteInstance {},
	txt_yicheika1: class extends self.ITextInstance {},
	txt_yicheika2: class extends self.ITextInstance {},
	txt_yicheika3: class extends self.ITextInstance {},
	txt_yicheika4: class extends self.ITextInstance {},
	txt_yicheika5: class extends self.ITextInstance {},
	blocksss6: class extends self.ISpriteInstance {},
	block16: class extends self.ISpriteInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	boss_issushitel: class extends self.ISpriteInstance {},
	blockADD2: class extends self.ISpriteInstance {},
	blockADD1: class extends self.ISpriteInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	stroyka: class extends self.ISpriteInstance {},
	lava: class extends self.ISpriteInstance {},
	shop_okno: class extends self.ISpriteInstance {},
	b_shop_close: class extends self.ISpriteInstance {},
	txt_shop: class extends self.ITextInstance {},
	txt_shop1: class extends self.ITextInstance {},
	shop_prodazha: class extends self.ITextInstance {},
	but_obshenie: class extends self.ISpriteInstance {},
	but_smena: class extends self.ISpriteInstance {},
	but_v_menu: class extends self.ISpriteInstance {},
	shopmech: class extends self.ISpriteInstance {},
	shopKirka: class extends self.ISpriteInstance {},
	pokupkaKirka: class extends self.ITextInstance {},
	pokupkaMech: class extends self.ITextInstance {},
	svitok_shop: class extends self.ISpriteInstance {},
	pokupkaSvitok: class extends self.ITextInstance {},
	iconka_ad: class extends self.ISpriteInstance {},
	ad_txt: class extends self.ITextInstance {},
	mob_zombie: class extends self.ISpriteInstance {},
	txt_hp: class extends self.ITextInstance {},
	line_boss: class extends self.ISpriteInstance {},
	txt_boss: class extends self.ITextInstance {},
	boss_punkt1: class extends self.ISpriteInstance {},
	boss_punkt2: class extends self.ISpriteInstance {},
	boss_punkt3: class extends self.ISpriteInstance {},
	boss_shar: class extends self.ISpriteInstance {},
	boss_chastici: class extends self.IParticlesInstance {},
	portal3: class extends self.ISpriteInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	block_lestnice: class extends self.ISpriteInstance {},
	portal2: class extends self.ISpriteInstance {},
	punkt1: class extends self.ISpriteInstance {},
	punkt2: class extends self.ISpriteInstance {},
	punkt3: class extends self.ISpriteInstance {},
	HUD_lestn: class extends self.ISpriteInstance {},
	lestnica: class extends self.ISpriteInstance {},
	But_attack2: class extends self.ISpriteInstance {},
	but_jump: class extends self.ISpriteInstance {},
	iconka_ad2: class extends self.ISpriteInstance {},
	ad_txt2: class extends self.ITextInstance {},
	w061n0055Bp3: class extends self.ISpriteInstance {},
	txt_zadacha: class extends self.ITextInstance {},
	But_attack3: class extends self.ISpriteInstance {},
	b_zadacha: class extends self.ISpriteInstance {},
	But_attack4: class extends self.ISpriteInstance {},
	But_attack5: class extends self.ISpriteInstance {},
	b_tgm: class extends self.ISpriteInstance {},
	shop_okno2: class extends self.ISpriteInstance {},
	shop_okno3: class extends self.ISpriteInstance {},
	shop_okno4: class extends self.ISpriteInstance {},
	fail_okno: class extends self.ISpriteInstance {},
	fail_but: class extends self.ISpriteInstance {},
	txt_fail: class extends self.ITextInstance {}
}