const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Behaviors.MoveTo,
		C3.Behaviors.custom,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.PickAll,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.AddVar
	];
};
self.C3_JsPropNameTable = [
	{Active: 0},
	{Matched: 0},
	{Chain: 0},
	{Created: 0},
	{OutOfChain: 0},
	{Match3: 0},
	{MatchNormal: 0},
	{DragDrop: 0},
	{Tween: 0},
	{MoveTo: 0},
	{Custom: 0},
	{Jewel: 0},
	{Occupied: 0},
	{MaskMatched: 0},
	{Tile: 0},
	{Table: 0},
	{BG: 0},
	{MaskJewell: 0},
	{Mouse: 0},
	{Points: 0},
	{Touch: 0},
	{FrameDragStart: 0},
	{Xtarget: 0},
	{YTarget: 0},
	{UIDTarget: 0},
	{TileX: 0},
	{TileY: 0},
	{TileUid: 0},
	{UIDChain: 0},
	{X: 0},
	{Y: 0},
	{NewX: 0},
	{NewY: 0},
	{Parameter0: 0},
	{Parameter1: 0},
	{Parameter2: 0}
];

self.InstanceType = {
	Jewel: class extends self.ISpriteInstance {},
	Tile: class extends self.ISpriteInstance {},
	Table: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	MaskJewell: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Points: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {}
}