const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Physics,
		C3.Plugins.Touch,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.NextPrevLayout
	];
};
self.C3_JsPropNameTable = [
	{IMG_20251106_234514_: 0},
	{IMG_20251106_234516_: 0},
	{Nom: 0},
	{b_bukv: 0},
	{monst1: 0},
	{monst4: 0},
	{monst2: 0},
	{john: 0},
	{skeleton: 0},
	{Синусоида: 0},
	{monst11: 0},
	{monst111: 0},
	{b_leaderboard: 0},
	{txt_score: 0},
	{Физика: 0},
	{raz1: 0},
	{raz11: 0},
	{raz111: 0},
	{pol_physix: 0},
	{Тач: 0},
	{TESTER: 0},
	{monst22: 0},
	{monst222: 0},
	{monst2222: 0},
	{raz2: 0},
	{raz22: 0},
	{raz222: 0},
	{raz2222: 0},
	{raz22222: 0},
	{Синусоида2: 0},
	{monst3: 0},
	{monst33: 0},
	{GamePush: 0},
	{monst44: 0},
	{monst444: 0},
	{raz3: 0},
	{raz33: 0},
	{raz333: 0},
	{raz3333: 0},
	{score: 0},
	{nachislenie: 0},
	{vibran1: 0},
	{vibran2: 0},
	{objects_bukv: 0},
	{level: 0},
	{razrushenie: 0}
];

self.InstanceType = {
	IMG_20251106_234514_: class extends self.ISpriteInstance {},
	IMG_20251106_234516_: class extends self.ISpriteInstance {},
	b_bukv: class extends self.ISpriteInstance {},
	monst1: class extends self.ISpriteInstance {},
	monst4: class extends self.ISpriteInstance {},
	monst2: class extends self.ISpriteInstance {},
	john: class extends self.ISpriteInstance {},
	skeleton: class extends self.ISpriteInstance {},
	monst11: class extends self.ISpriteInstance {},
	monst111: class extends self.ISpriteInstance {},
	b_leaderboard: class extends self.ISpriteInstance {},
	txt_score: class extends self.ITextInstance {},
	raz1: class extends self.ISpriteInstance {},
	raz11: class extends self.ISpriteInstance {},
	raz111: class extends self.ISpriteInstance {},
	pol_physix: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	TESTER: class extends self.ITextInstance {},
	monst22: class extends self.ISpriteInstance {},
	monst222: class extends self.ISpriteInstance {},
	monst2222: class extends self.ISpriteInstance {},
	raz2: class extends self.ISpriteInstance {},
	raz22: class extends self.ISpriteInstance {},
	raz222: class extends self.ISpriteInstance {},
	raz2222: class extends self.ISpriteInstance {},
	raz22222: class extends self.ISpriteInstance {},
	monst3: class extends self.ISpriteInstance {},
	monst33: class extends self.ISpriteInstance {},
	GamePush: class extends self.IInstance {},
	monst44: class extends self.ISpriteInstance {},
	monst444: class extends self.ISpriteInstance {},
	raz3: class extends self.ISpriteInstance {},
	raz33: class extends self.ISpriteInstance {},
	raz333: class extends self.ISpriteInstance {},
	raz3333: class extends self.ISpriteInstance {}
}