const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Behaviors.Rotate,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Audio,
		C3.Behaviors.MoveTo,
		C3.Behaviors.destroy,
		C3.Behaviors.NoSave,
		C3.Plugins.Particles,
		C3.Behaviors.Fade,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Eponesh_GameScore.Acts.FullscreenClose,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.LoadState,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Acts.PauseAllTweens,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Behaviors.Sin.Acts.UpdateInitialState,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedPlaying,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.OnLoadFailed,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying
	];
};
self.C3_JsPropNameTable = [
	{xx: 0},
	{yy: 0},
	{Moved: 0},
	{Del: 0},
	{Синусоида: 0},
	{Block: 0},
	{HostBlock: 0},
	{bl: 0},
	{N: 0},
	{Spot: 0},
	{BoardBg: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Browser: 0},
	{Синусоид: 0},
	{Поворот: 0},
	{Якорь: 0},
	{BtnReset: 0},
	{GameOver: 0},
	{txtScore: 0},
	{LocalStorage: 0},
	{GamePush: 0},
	{txtversion: 0},
	{bplay: 0},
	{bvmenu: 0},
	{bsound: 0},
	{Аудио: 0},
	{image6: 0},
	{bg_menu: 0},
	{Спрайт4: 0},
	{ДвижениеК: 0},
	{УничтожениеВнеМакета: 0},
	{НеСохранять: 0},
	{ingr1: 0},
	{Частицы: 0},
	{"—Pngtree—waterbubbleGreenBubble_": 0},
	{Спрайт: 0},
	{ingr2: 0},
	{ingr3: 0},
	{ingr4: 0},
	{ingr5: 0},
	{ingr6: 0},
	{ingr7: 0},
	{ingr8: 0},
	{ingr9: 0},
	{ingr10: 0},
	{ingr11: 0},
	{punkt: 0},
	{image: 0},
	{image2: 0},
	{image3: 0},
	{but3232преобразованный: 0},
	{image4: 0},
	{image5: 0},
	{but3232преобразованный2: 0},
	{coin: 0},
	{txtCoin: 0},
	{but3232преобразованный3: 0},
	{b_vozvrat: 0},
	{b_dell: 0},
	{TEST: 0},
	{txtCoin2: 0},
	{txtCoin3: 0},
	{freeiconbackward: 0},
	{Спрайт2: 0},
	{coinHUD: 0},
	{linedell: 0},
	{iconreklam_over: 0},
	{image7: 0},
	{image8: 0},
	{image9: 0},
	{image10: 0},
	{image11: 0},
	{image12: 0},
	{bplay2: 0},
	{image13: 0},
	{Spot2: 0},
	{Угасание: 0},
	{eyes: 0},
	{bg_menu2: 0},
	{ghost: 0},
	{witch: 0},
	{OVSWBJ2: 0},
	{OVSWB3233223J: 0},
	{txtScore2: 0},
	{txtScore3: 0},
	{flatdesignmagicsymbols_: 0},
	{ad_money: 0},
	{txtCoin_ad: 0},
	{Tween: 0},
	{FBlock: 0},
	{FSpot: 0},
	{SwipeDir: 0},
	{SwipeMaxDistance: 0},
	{StartTouchX: 0},
	{StartTouchY: 0},
	{BlocksMoving: 0},
	{Score: 0},
	{starter: 0},
	{BlockID: 0},
	{SpotID: 0},
	{Tag: 0},
	{ThereIsChance: 0},
	{starter_timer: 0},
	{BestScore: 0},
	{volume: 0},
	{coins: 0}
];

self.InstanceType = {
	Block: class extends self.ISpriteInstance {},
	Spot: class extends self.ISpriteInstance {},
	BoardBg: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	BtnReset: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	txtScore: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	GamePush: class extends self.IInstance {},
	txtversion: class extends self.ITextInstance {},
	bplay: class extends self.ISpriteInstance {},
	bvmenu: class extends self.ISpriteInstance {},
	bsound: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	image6: class extends self.ISpriteInstance {},
	bg_menu: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	ingr1: class extends self.ISpriteInstance {},
	Частицы: class extends self.IParticlesInstance {},
	__InvalidName0__: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	ingr2: class extends self.ISpriteInstance {},
	ingr3: class extends self.ISpriteInstance {},
	ingr4: class extends self.ISpriteInstance {},
	ingr5: class extends self.ISpriteInstance {},
	ingr6: class extends self.ISpriteInstance {},
	ingr7: class extends self.ISpriteInstance {},
	ingr8: class extends self.ISpriteInstance {},
	ingr9: class extends self.ISpriteInstance {},
	ingr10: class extends self.ISpriteInstance {},
	ingr11: class extends self.ISpriteInstance {},
	punkt: class extends self.ISpriteInstance {},
	image: class extends self.ISpriteInstance {},
	image2: class extends self.ISpriteInstance {},
	image3: class extends self.ISpriteInstance {},
	but3232преобразованный: class extends self.ISpriteInstance {},
	image4: class extends self.ISpriteInstance {},
	image5: class extends self.ISpriteInstance {},
	but3232преобразованный2: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	txtCoin: class extends self.ITextInstance {},
	but3232преобразованный3: class extends self.ISpriteInstance {},
	b_vozvrat: class extends self.ISpriteInstance {},
	b_dell: class extends self.ISpriteInstance {},
	TEST: class extends self.ITextInstance {},
	txtCoin2: class extends self.ITextInstance {},
	txtCoin3: class extends self.ITextInstance {},
	freeiconbackward: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	coinHUD: class extends self.ISpriteInstance {},
	linedell: class extends self.ISpriteInstance {},
	iconreklam_over: class extends self.ISpriteInstance {},
	image7: class extends self.ISpriteInstance {},
	image8: class extends self.ISpriteInstance {},
	image9: class extends self.ISpriteInstance {},
	image10: class extends self.ISpriteInstance {},
	image11: class extends self.ISpriteInstance {},
	image12: class extends self.ISpriteInstance {},
	bplay2: class extends self.ISpriteInstance {},
	image13: class extends self.ISpriteInstance {},
	Spot2: class extends self.ISpriteInstance {},
	eyes: class extends self.ISpriteInstance {},
	bg_menu2: class extends self.ISpriteInstance {},
	ghost: class extends self.ISpriteInstance {},
	witch: class extends self.ISpriteInstance {},
	OVSWBJ2: class extends self.ISpriteInstance {},
	OVSWB3233223J: class extends self.ISpriteInstance {},
	txtScore2: class extends self.ITextInstance {},
	txtScore3: class extends self.ITextInstance {},
	flatdesignmagicsymbols_: class extends self.ISpriteInstance {},
	ad_money: class extends self.ISpriteInstance {},
	txtCoin_ad: class extends self.ITextInstance {},
	FBlock: class extends self.ISpriteInstance {},
	FSpot: class extends self.ISpriteInstance {}
}