const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Json,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Behaviors.scrollto,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Behaviors.Timer,
		C3.Behaviors.Sin,
		C3.Behaviors.MoveTo,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.UnloadUnusedTextures,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Spritefont2.Acts.SetHAlign,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Acts.SetPath,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.right,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.TiledBg.Acts.SetImageScaleX,
		C3.Plugins.TiledBg.Acts.SetImageScaleY,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.System.Cnds.PickAll,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.TiledBg.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgb,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.TiledBg.Exps.UID,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.TiledBg.Exps.ColorValue,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Arr.Exps.Front,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Arr.Acts.Pop,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Exps.tickcount,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Play
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{Array: 0},
	{JSON: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{Button: 0},
	{Buttons: 0},
	{LoadingBar: 0},
	{LoadingBar2: 0},
	{LoadingBase: 0},
	{This: 0},
	{Tween: 0},
	{Sprite: 0},
	{Rotate: 0},
	{SunBurst: 0},
	{ID: 0},
	{Anchor: 0},
	{Text: 0},
	{Title: 0},
	{BuildedBuildings: 0},
	{OwnedBuildings: 0},
	{FirstX: 0},
	{FirstY: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Empty: 0},
	{ID2: 0},
	{Upgrade: 0},
	{CityPlane: 0},
	{DistanceChecker: 0},
	{House: 0},
	{Fade: 0},
	{Houseiso: 0},
	{Bullet: 0},
	{Particles_Sponge: 0},
	{Painted: 0},
	{Point: 0},
	{Timer: 0},
	{Props: 0},
	{Shadow: 0},
	{Anglee: 0},
	{CurPaint: 0},
	{Sine: 0},
	{MoveTo: 0},
	{Sponge: 0},
	{CityFence: 0},
	{Sprite5: 0},
	{CurAngle: 0},
	{Paint: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{Sine2: 0},
	{Sine3: 0},
	{Particles: 0},
	{Sprite2: 0},
	{TiledBackground: 0},
	{CityPlus: 0},
	{Money: 0},
	{BackButton: 0},
	{TiledBackground5: 0},
	{Sprite3: 0},
	{TouchPoint1: 0},
	{TouchPoint2: 0},
	{CamRef: 0},
	{SoundButton: 0},
	{Audio: 0},
	{Browser: 0},
	{MoreGamesButton: 0},
	{Текст: 0},
	{Family1: 0},
	{Level: 0},
	{Phase: 0},
	{HouseSize: 0},
	{HouseHeight: 0},
	{Debug: 0},
	{Color: 0},
	{R: 0},
	{G: 0},
	{B: 0},
	{R_P: 0},
	{G_P: 0},
	{B_P: 0},
	{TotalPhase: 0},
	{LevelVisual: 0},
	{Scale: 0},
	{Sound: 0},
	{FirstStart: 0},
	{TargetX: 0},
	{TargetY: 0},
	{X: 0},
	{Y: 0},
	{MoneyEarned: 0},
	{Levelinit: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	JSON: class extends self.IJSONInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Buttons: class extends self.ISpriteInstance {},
	LoadingBar: class extends self.ITiledBackgroundInstance {},
	LoadingBar2: class extends self.ISpriteInstance {},
	LoadingBase: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	SunBurst: class extends self.ISpriteInstance {},
	Text: class extends self.ISpriteFontInstance {},
	Title: class extends self.ISpriteInstance {},
	BuildedBuildings: class extends self.IArrayInstance {},
	OwnedBuildings: class extends self.IArrayInstance {},
	Camera: class extends self.ISpriteInstance {},
	CityPlane: class extends self.ISpriteInstance {},
	DistanceChecker: class extends self.ISpriteInstance {},
	House: class extends self.ISpriteInstance {},
	Houseiso: class extends self.ISpriteInstance {},
	Particles_Sponge: class extends self.ISpriteInstance {},
	Point: class extends self.ISpriteInstance {},
	Props: class extends self.ISpriteInstance {},
	Shadow: class extends self.ITiledBackgroundInstance {},
	Sponge: class extends self.ISpriteInstance {},
	CityFence: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Paint: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Particles: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	CityPlus: class extends self.ISpriteInstance {},
	Money: class extends self.ISpriteInstance {},
	BackButton: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TouchPoint1: class extends self.ISpriteInstance {},
	TouchPoint2: class extends self.ISpriteInstance {},
	CamRef: class extends self.ISpriteInstance {},
	SoundButton: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	MoreGamesButton: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Family1: class extends self.ISpriteInstance {}
}