const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Sprite,
		C3.Behaviors.LOS,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Fade,
		C3.Behaviors.EightDir,
		C3.Behaviors.MoveTo,
		C3.Behaviors.destroy,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.OnLoadFailed,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Аудио: 0},
	{Тач: 0},
	{ОбУстройстве: 0},
	{GamePush: 0},
	{rost: 0},
	{voda: 0},
	{semena: 0},
	{otkr_zakr: 0},
	{viroslo: 0},
	{gryadka: 0},
	{ПолеЗрения: 0},
	{fermer: 0},
	{auto: 0},
	{icon_coin: 0},
	{fon_menu: 0},
	{Спрайт3: 0},
	{b_menu: 0},
	{b_sound: 0},
	{ТайловыйФон: 0},
	{ramka1: 0},
	{txt_money: 0},
	{Перетаскивание: 0},
	{leika: 0},
	{b_otpravka_mashini: 0},
	{b_play: 0},
	{txt_play: 0},
	{ТайловыйФон2: 0},
	{txt_otpravka: 0},
	{mesto_leiki: 0},
	{Угасание: 0},
	{"8Направлений": 0},
	{kaplya: 0},
	{shop_okno: 0},
	{ДвижениеК: 0},
	{УничтожениеВнеМакета: 0},
	{Luk: 0},
	{ramka2: 0},
	{ramka3: 0},
	{ramka4: 0},
	{ramka5: 0},
	{ramka6: 0},
	{b_otkrite1: 0},
	{txt_otkrite1: 0},
	{b_otkrite2: 0},
	{b_otkrite3: 0},
	{b_otkrite4: 0},
	{b_otkrite5: 0},
	{b_otkrite6: 0},
	{txt_otkrite2: 0},
	{txt_otkrite3: 0},
	{txt_otkrite4: 0},
	{txt_otkrite5: 0},
	{txt_otkrite6: 0},
	{Kapusta: 0},
	{Svekla: 0},
	{Salat: 0},
	{Chesnok: 0},
	{Morkov: 0},
	{sklad: 0},
	{txt_sklad: 0},
	{Пуля: 0},
	{auto_iconka: 0},
	{punkt1: 0},
	{punkt2: 0},
	{ТайловыйФон3: 0},
	{calligraphicornamentaldividerset_: 0},
	{tablichka: 0},
	{txt_rost_voda: 0},
	{mesto_semena: 0},
	{Strelka_semyan: 0},
	{ramka7: 0},
	{Спрайт4: 0},
	{txt_naProdazhu: 0},
	{prod_salat: 0},
	{prod_kapusta: 0},
	{prod_luk: 0},
	{prod_svekla: 0},
	{prod_chesnok: 0},
	{prod_morkov: 0},
	{strelka_salat: 0},
	{strelka_kapusta: 0},
	{strelka_luk: 0},
	{strelka_svekla: 0},
	{strelka_chesnok: 0},
	{strelka_morkov: 0},
	{sklad_salat: 0},
	{sklad_kapusta: 0},
	{sklad_luk: 0},
	{sklad_svekla: 0},
	{sklad_chesnok: 0},
	{sklad_morkov: 0},
	{money: 0},
	{sound: 0},
	{menu: 0},
	{play: 0},
	{shop: 0},
	{level: 0},
	{gryadka1: 0},
	{gryadka2: 0},
	{gryadka3: 0},
	{gryadka4: 0},
	{gryadka5: 0},
	{gryadka6: 0},
	{otpravlena: 0},
	{distancee: 0},
	{vibrani_semena: 0},
	{sklad_open: 0}
];

self.InstanceType = {
	Аудио: class extends self.IInstance {},
	Тач: class extends self.IInstance {},
	ОбУстройстве: class extends self.IInstance {},
	GamePush: class extends self.IInstance {},
	gryadka: class extends self.ISpriteInstance {},
	fermer: class extends self.ISpriteInstance {},
	auto: class extends self.ISpriteInstance {},
	icon_coin: class extends self.ISpriteInstance {},
	fon_menu: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	b_menu: class extends self.ISpriteInstance {},
	b_sound: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	ramka1: class extends self.ISpriteInstance {},
	txt_money: class extends self.ITextInstance {},
	leika: class extends self.ISpriteInstance {},
	b_otpravka_mashini: class extends self.ISpriteInstance {},
	b_play: class extends self.ISpriteInstance {},
	txt_play: class extends self.ITextInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	txt_otpravka: class extends self.ITextInstance {},
	mesto_leiki: class extends self.ISpriteInstance {},
	kaplya: class extends self.ISpriteInstance {},
	semena: class extends self.ISpriteInstance {},
	shop_okno: class extends self.ISpriteInstance {},
	Luk: class extends self.ISpriteInstance {},
	ramka2: class extends self.ISpriteInstance {},
	ramka3: class extends self.ISpriteInstance {},
	ramka4: class extends self.ISpriteInstance {},
	ramka5: class extends self.ISpriteInstance {},
	ramka6: class extends self.ISpriteInstance {},
	b_otkrite1: class extends self.ISpriteInstance {},
	txt_otkrite1: class extends self.ITextInstance {},
	b_otkrite2: class extends self.ISpriteInstance {},
	b_otkrite3: class extends self.ISpriteInstance {},
	b_otkrite4: class extends self.ISpriteInstance {},
	b_otkrite5: class extends self.ISpriteInstance {},
	b_otkrite6: class extends self.ISpriteInstance {},
	txt_otkrite2: class extends self.ITextInstance {},
	txt_otkrite3: class extends self.ITextInstance {},
	txt_otkrite4: class extends self.ITextInstance {},
	txt_otkrite5: class extends self.ITextInstance {},
	txt_otkrite6: class extends self.ITextInstance {},
	Kapusta: class extends self.ISpriteInstance {},
	Svekla: class extends self.ISpriteInstance {},
	Salat: class extends self.ISpriteInstance {},
	Chesnok: class extends self.ISpriteInstance {},
	Morkov: class extends self.ISpriteInstance {},
	sklad: class extends self.ISpriteInstance {},
	txt_sklad: class extends self.ITextInstance {},
	auto_iconka: class extends self.ISpriteInstance {},
	punkt1: class extends self.ISpriteInstance {},
	punkt2: class extends self.ISpriteInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	calligraphicornamentaldividerset_: class extends self.ISpriteInstance {},
	tablichka: class extends self.ISpriteInstance {},
	txt_rost_voda: class extends self.ITextInstance {},
	mesto_semena: class extends self.ISpriteInstance {},
	Strelka_semyan: class extends self.ISpriteInstance {},
	ramka7: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	txt_naProdazhu: class extends self.ITextInstance {},
	prod_salat: class extends self.ITextInstance {},
	prod_kapusta: class extends self.ITextInstance {},
	prod_luk: class extends self.ITextInstance {},
	prod_svekla: class extends self.ITextInstance {},
	prod_chesnok: class extends self.ITextInstance {},
	prod_morkov: class extends self.ITextInstance {},
	strelka_salat: class extends self.ISpriteInstance {},
	strelka_kapusta: class extends self.ISpriteInstance {},
	strelka_luk: class extends self.ISpriteInstance {},
	strelka_svekla: class extends self.ISpriteInstance {},
	strelka_chesnok: class extends self.ISpriteInstance {},
	strelka_morkov: class extends self.ISpriteInstance {},
	sklad_salat: class extends self.ITextInstance {},
	sklad_kapusta: class extends self.ITextInstance {},
	sklad_luk: class extends self.ITextInstance {},
	sklad_svekla: class extends self.ITextInstance {},
	sklad_chesnok: class extends self.ITextInstance {},
	sklad_morkov: class extends self.ITextInstance {}
}