const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.destroy,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Behaviors.Timer,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddLayer,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetOpacity
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{DestroyOutsideLayout: 0},
	{Wall: 0},
	{MoveDuration: 0},
	{Direction: 0},
	{TargetX: 0},
	{TargetY: 0},
	{Bullet: 0},
	{PacMan: 0},
	{Keyboard: 0},
	{GhostName: 0},
	{VulnerableTimer: 0},
	{eaten: 0},
	{vert: 0},
	{escape: 0},
	{escapeBlink: 0},
	{hor: 0},
	{Name: 0},
	{Timer: 0},
	{Ghost: 0},
	{TextScore: 0},
	{CollisionDetector: 0},
	{AvailableDirections: 0},
	{BigDot: 0},
	{Dot: 0},
	{GhostHome: 0},
	{Fade: 0},
	{Points: 0},
	{FruitHome: 0},
	{Fruit: 0},
	{TextPoints: 0},
	{ID: 0},
	{PacLives: 0},
	{TextLives: 0},
	{ParticlesPacMan: 0},
	{ParticlesGhost: 0},
	{PacManHome: 0},
	{TextWin: 0},
	{TextLose: 0},
	{Sprite: 0},
	{myhead: 0},
	{Аудио: 0},
	{txt_logo: 0},
	{Тач: 0},
	{b_play: 0},
	{Текст: 0},
	{Якорь: 0},
	{Текст2: 0},
	{txt_levels_vsego: 0},
	{but_volume: 0},
	{but_niz: 0},
	{but_pravo: 0},
	{but_verh: 0},
	{but_levo: 0},
	{b_home: 0},
	{b_restart: 0},
	{Синусоида: 0},
	{txt_loader: 0},
	{Спрайт: 0},
	{PacMan_menu: 0},
	{spawner: 0},
	{Пуля: 0},
	{Dot2_menu: 0},
	{Твёрдый: 0},
	{Wall2: 0},
	{Dot2_end: 0},
	{PacMan_end: 0},
	{Текст3: 0},
	{aDir: 0},
	{ghostSpawn: 0},
	{TileSize: 0},
	{Score: 0},
	{Lives: 0},
	{playerRespawnTime: 0},
	{nbGhost: 0},
	{bigDotScore: 0},
	{dotScore: 0},
	{ghostEscapeTime: 0},
	{ghostBlinkTime: 0},
	{Alive: 0},
	{Game: 0},
	{image: 0},
	{image2: 0},
	{GhostsEaten: 0},
	{n: 0},
	{level_postroika: 0},
	{TileSize2: 0},
	{Score2: 0},
	{Lives2: 0},
	{GhostsEaten2: 0},
	{n2: 0},
	{timer_loader: 0},
	{volume: 0},
	{levels_all: 0}
];

self.InstanceType = {
	Background: class extends self.ITiledBackgroundInstance {},
	Wall: class extends self.ISpriteInstance {},
	PacMan: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Ghost: class extends self.ISpriteInstance {},
	TextScore: class extends self.ITextInstance {},
	CollisionDetector: class extends self.ISpriteInstance {},
	AvailableDirections: class extends self.IArrayInstance {},
	BigDot: class extends self.ISpriteInstance {},
	Dot: class extends self.ISpriteInstance {},
	GhostHome: class extends self.ISpriteInstance {},
	Points: class extends self.ISpriteInstance {},
	FruitHome: class extends self.ISpriteInstance {},
	Fruit: class extends self.ISpriteInstance {},
	TextPoints: class extends self.ITextInstance {},
	PacLives: class extends self.ISpriteInstance {},
	TextLives: class extends self.ITextInstance {},
	ParticlesPacMan: class extends self.IParticlesInstance {},
	ParticlesGhost: class extends self.IParticlesInstance {},
	PacManHome: class extends self.ISpriteInstance {},
	TextWin: class extends self.ISpriteInstance {},
	TextLose: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	myhead: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	txt_logo: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	b_play: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Текст2: class extends self.ITextInstance {},
	txt_levels_vsego: class extends self.ITextInstance {},
	but_volume: class extends self.ISpriteInstance {},
	but_niz: class extends self.ISpriteInstance {},
	but_pravo: class extends self.ISpriteInstance {},
	but_verh: class extends self.ISpriteInstance {},
	but_levo: class extends self.ISpriteInstance {},
	b_home: class extends self.ISpriteInstance {},
	b_restart: class extends self.ISpriteInstance {},
	txt_loader: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	PacMan_menu: class extends self.ISpriteInstance {},
	spawner: class extends self.ISpriteInstance {},
	Dot2_menu: class extends self.ISpriteInstance {},
	Wall2: class extends self.ISpriteInstance {},
	Dot2_end: class extends self.ISpriteInstance {},
	PacMan_end: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	aDir: class extends self.IArrayInstance {},
	ghostSpawn: class extends self.ISpriteInstance {},
	Game: class extends self.ISpriteInstance {},
	image: class extends self.ISpriteInstance {},
	image2: class extends self.ISpriteInstance {}
}