const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.Dictionary,
		C3.Plugins.Keyboard,
		C3.Behaviors.wrap,
		C3.Behaviors.Anchor,
		C3.Plugins.Spritefont2,
		C3.Behaviors.EightDir,
		C3.Behaviors.Flash,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Behaviors.EightDir.Acts.SetAcceleration,
		C3.Behaviors.EightDir.Acts.SetDeceleration,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Cnds.CompareY,
		C3.Plugins.Spritefont2.Exps.Opacity,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsShare,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.regexreplace,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Spritefont2.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.CompareOpacity
	];
};
self.C3_JsPropNameTable = [
	{Activated: 0},
	{Activation_Coordinate: 0},
	{Invulnerable: 0},
	{Shielded: 0},
	{Health: 0},
	{Points: 0},
	{Dying: 0},
	{Debris_RGB: 0},
	{BigDeathSequence: 0},
	{DropsItems: 0},
	{RotateDirection: 0},
	{Bullet: 0},
	{En_Asteroid: 0},
	{Strength: 0},
	{En_Bullet_1: 0},
	{En_Bullet_2: 0},
	{En_Bullet_3: 0},
	{En_Bullet_4: 0},
	{En_Bullet_5: 0},
	{Sine: 0},
	{En_Bullet_6: 0},
	{State: 0},
	{State_Timer: 0},
	{Boss: 0},
	{ShootTimer: 0},
	{Enemy_Red: 0},
	{FlyAway_Timer: 0},
	{FlyAway_Angle: 0},
	{Enemy_Blue: 0},
	{StartingAngle: 0},
	{Enemy_Grey: 0},
	{Enemy_Green: 0},
	{AimAngle: 0},
	{Enemy_Green_Cannon: 0},
	{Shoot_Timer: 0},
	{Shoot_Timer_2: 0},
	{Shoot_Count: 0},
	{Enemy_GroundCannon: 0},
	{GroundCannon_Destroyed: 0},
	{Enemy_GroundCannon2: 0},
	{Timer: 0},
	{SweepDirection: 0},
	{Pin: 0},
	{En_Laser: 0},
	{ID: 0},
	{Boss_Cannons: 0},
	{Side: 0},
	{Boss_Turrets: 0},
	{Cutscene: 0},
	{Controller_Cutscene: 0},
	{Audio: 0},
	{Data: 0},
	{MusicFadeState: 0},
	{MusicVolume: 0},
	{MenuLock: 0},
	{Generic_Controller: 0},
	{Keyboard: 0},
	{Background: 0},
	{Wrap: 0},
	{Якорь: 0},
	{Background_Infinite: 0},
	{ToLayout: 0},
	{FinishLine: 0},
	{Particle_Debris: 0},
	{Particle_Generic: 0},
	{Particle_Smoke: 0},
	{PowerUp: 0},
	{Speed: 0},
	{Transition: 0},
	{LevelTop: 0},
	{HUD_Lives: 0},
	{HUD_WeaponIcon: 0},
	{BrightnessFX: 0},
	{Logo: 0},
	{LogoOverlay: 0},
	{SpriteFont_Generic: 0},
	{SpriteFont_Points: 0},
	{HurtTimer: 0},
	{Hurt: 0},
	{BeamSide: 0},
	{"8Direction": 0},
	{Flash: 0},
	{Player: 0},
	{Destroyed: 0},
	{Player_NormalBeam: 0},
	{Player_SpreadBeam: 0},
	{Player_SineBeam: 0},
	{Player_SineBeam_Effect: 0},
	{Player_Jets: 0},
	{GamePush: 0},
	{Тач: 0},
	{ОбУстройстве: 0},
	{"8Направлений": 0},
	{txtstarting: 0},
	{txt_v_pute: 0},
	{txt_: 0},
	{but_play: 0},
	{txtistoria: 0},
	{bvmenu: 0},
	{OF8TEJ: 0},
	{OF8TEJ2: 0},
	{b_soc: 0},
	{b_social: 0},
	{b_instruction: 0},
	{b_instr: 0},
	{txt_instru: 0},
	{SpriteFonts: 0},
	{Enemies: 0},
	{Enemy_Bullets: 0},
	{Player_Bullets: 0},
	{instruction: 0},
	{enemyUid: 0},
	{damage: 0},
	{DropRandomizer: 0},
	{createX: 0},
	{createY: 0},
	{rgbStr: 0},
	{CannonID: 0},
	{Testing: 0},
	{transitionState: 0},
	{transitionSpeed: 0},
	{transitionAnimFrame: 0}
];

self.InstanceType = {
	En_Asteroid: class extends self.ISpriteInstance {},
	En_Bullet_1: class extends self.ISpriteInstance {},
	En_Bullet_2: class extends self.ISpriteInstance {},
	En_Bullet_3: class extends self.ISpriteInstance {},
	En_Bullet_4: class extends self.ISpriteInstance {},
	En_Bullet_5: class extends self.ISpriteInstance {},
	En_Bullet_6: class extends self.ISpriteInstance {},
	Boss: class extends self.ISpriteInstance {},
	Enemy_Red: class extends self.ISpriteInstance {},
	Enemy_Blue: class extends self.ISpriteInstance {},
	Enemy_Grey: class extends self.ISpriteInstance {},
	Enemy_Green: class extends self.ISpriteInstance {},
	Enemy_Green_Cannon: class extends self.ISpriteInstance {},
	Enemy_GroundCannon: class extends self.ISpriteInstance {},
	GroundCannon_Destroyed: class extends self.ISpriteInstance {},
	Enemy_GroundCannon2: class extends self.ISpriteInstance {},
	En_Laser: class extends self.ISpriteInstance {},
	Boss_Cannons: class extends self.ISpriteInstance {},
	Boss_Turrets: class extends self.ISpriteInstance {},
	Controller_Cutscene: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Data: class extends self.IDictionaryInstance {},
	Generic_Controller: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Background: class extends self.ISpriteInstance {},
	Background_Infinite: class extends self.ISpriteInstance {},
	FinishLine: class extends self.ISpriteInstance {},
	Particle_Debris: class extends self.ISpriteInstance {},
	Particle_Generic: class extends self.ISpriteInstance {},
	Particle_Smoke: class extends self.ISpriteInstance {},
	PowerUp: class extends self.ISpriteInstance {},
	Transition: class extends self.ISpriteInstance {},
	LevelTop: class extends self.ISpriteInstance {},
	HUD_Lives: class extends self.ISpriteInstance {},
	HUD_WeaponIcon: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	LogoOverlay: class extends self.ISpriteInstance {},
	SpriteFont_Generic: class extends self.ISpriteFontInstance {},
	SpriteFont_Points: class extends self.ISpriteFontInstance {},
	Player: class extends self.ISpriteInstance {},
	Player_NormalBeam: class extends self.ISpriteInstance {},
	Player_SpreadBeam: class extends self.ISpriteInstance {},
	Player_SineBeam: class extends self.ISpriteInstance {},
	Player_SineBeam_Effect: class extends self.ISpriteInstance {},
	Player_Jets: class extends self.ISpriteInstance {},
	GamePush: class extends self.IInstance {},
	Тач: class extends self.IInstance {},
	ОбУстройстве: class extends self.IInstance {},
	txtstarting: class extends self.ITextInstance {},
	txt_v_pute: class extends self.ITextInstance {},
	txt_: class extends self.ITextInstance {},
	but_play: class extends self.ISpriteInstance {},
	txtistoria: class extends self.ITextInstance {},
	bvmenu: class extends self.ISpriteInstance {},
	OF8TEJ: class extends self.ISpriteInstance {},
	OF8TEJ2: class extends self.ISpriteInstance {},
	b_soc: class extends self.ISpriteInstance {},
	b_social: class extends self.ISpriteInstance {},
	b_instruction: class extends self.ISpriteInstance {},
	b_instr: class extends self.ISpriteInstance {},
	txt_instru: class extends self.ITextInstance {},
	SpriteFonts: class extends self.ISpriteFontInstance {},
	Enemies: class extends self.ISpriteInstance {},
	Enemy_Bullets: class extends self.ISpriteInstance {},
	Player_Bullets: class extends self.ISpriteInstance {}
}