const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.Turret,
		C3.Behaviors.Sin,
		C3.Behaviors.MoveTo,
		C3.Plugins.Spritefont2,
		C3.Plugins.ScirraArcadeV4,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Touch,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Plugins.TiledBg,
		C3.Behaviors.LOS,
		C3.Behaviors.destroy,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Behaviors.Flash,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Turret.Acts.UnacquireTarget,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Turret.Acts.SetEnabled,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Behaviors.Turret.Acts.ClearTargets,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnError,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedPlaying,
		C3.Plugins.LocalStorage.Acts.SetItem
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{СледитьЗа: 0},
	{Пуля: 0},
	{Турель: 0},
	{snake_head: 0},
	{Variable1: 0},
	{snake_body: 0},
	{Синусоида: 0},
	{ДвижениеК: 0},
	{eda: 0},
	{grass: 0},
	{SpriteFont: 0},
	{ScirraArcade: 0},
	{Keyboard: 0},
	{Audio: 0},
	{ЛокальноеХранилище: 0},
	{GamePush: 0},
	{Тач: 0},
	{Якорь: 0},
	{fon: 0},
	{logomenu: 0},
	{txtloader: 0},
	{image: 0},
	{image2: 0},
	{image3: 0},
	{Спрайт5: 0},
	{image4: 0},
	{b_option: 0},
	{b_play: 0},
	{banner_menu: 0},
	{b_bonus1: 0},
	{b_bonus2: 0},
	{b_bonus3: 0},
	{Текст: 0},
	{b_sound: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{Спрайт6: 0},
	{txt_coin: 0},
	{Текст2: 0},
	{vecteezy_dreamyimmaculateapairofcrossedswordsornatehiltsno_: 0},
	{Спрайт3: 0},
	{txt_record: 0},
	{O4YIIJ: 0},
	{b7be94684794be9a7923e705bdad2c: 0},
	{image5: 0},
	{w032_n003_315b_p1_: 0},
	{txt_level: 0},
	{txt_xp: 0},
	{Сни321231мок: 0},
	{but_speed: 0},
	{icons8магнит: 0},
	{txt_bonus_speed: 0},
	{Спрайт7: 0},
	{txt_bonus_magnit: 0},
	{b_reklam_coin: 0},
	{b_reklam_speed: 0},
	{b_reklam_magnit: 0},
	{Мышь: 0},
	{ОбУстройстве: 0},
	{Спрайт4: 0},
	{e6c81d1ae349f596b21bd28221f: 0},
	{b_home: 0},
	{okno_rezhim1: 0},
	{b_rezhim1: 0},
	{Текст3: 0},
	{drenderinghexagonaltexturebackground: 0},
	{ТайловыйФон: 0},
	{cell: 0},
	{ПолеЗрения: 0},
	{УничтожениеВнеМакета: 0},
	{Твёрдый: 0},
	{snake_head_enemy1: 0},
	{snake_body_enemy1: 0},
	{Спрайт8: 0},
	{Спрайт9: 0},
	{okno_tablo: 0},
	{Текст4: 0},
	{txt_tablo_1: 0},
	{txt_tablo_2: 0},
	{txt_tablo_3: 0},
	{txt_tablo_4: 0},
	{txt_tablo_5: 0},
	{txt_tablo_6: 0},
	{txt_tablo_7: 0},
	{txt_tablo_8: 0},
	{txt_tablo_9: 0},
	{txt_tablo_10: 0},
	{skin2: 0},
	{Текст5: 0},
	{buy_skin1: 0},
	{buy_skin1_txt: 0},
	{buy_skin2: 0},
	{buy_skin3: 0},
	{buy_skin4: 0},
	{buy_skin5: 0},
	{buy_skin2_txt: 0},
	{buy_skin3_txt: 0},
	{buy_skin4_txt: 0},
	{buy_skin5_txt: 0},
	{buy_skin6: 0},
	{buy_skin6_txt: 0},
	{buy_skin7: 0},
	{buy_skin8: 0},
	{buy_skin9: 0},
	{buy_skin10: 0},
	{buy_skin7_txt: 0},
	{buy_skin8_txt: 0},
	{buy_skin9_txt: 0},
	{buy_skin10_txt: 0},
	{eda_skin_pokupka1: 0},
	{eda_skin_pokupka2: 0},
	{eda_skin_pokupka3: 0},
	{eda_skin_pokupka4: 0},
	{eda_skin_pokupka5: 0},
	{eda_skin_pokupka6: 0},
	{eda_skin_pokupka7: 0},
	{eda_skin_pokupka8: 0},
	{skines_krug: 0},
	{coin_spawn: 0},
	{snake_head_enemy2: 0},
	{snake_head_enemy3: 0},
	{snake_head_enemy4: 0},
	{snake_head_enemy5: 0},
	{snake_head_enemy6: 0},
	{snake_head_enemy7: 0},
	{snake_head_enemy8: 0},
	{snake_head_enemy9: 0},
	{snake_body_enemy2: 0},
	{snake_body_enemy3: 0},
	{snake_body_enemy4: 0},
	{snake_body_enemy5: 0},
	{snake_body_enemy6: 0},
	{snake_body_enemy7: 0},
	{snake_body_enemy8: 0},
	{snake_body_enemy9: 0},
	{Угасание: 0},
	{O4YIIJ2: 0},
	{Текст6: 0},
	{Мигание: 0},
	{b_reklam_restart: 0},
	{txt_vibor_upr: 0},
	{txt_vibor_upr1: 0},
	{txt_vibor_upr2: 0},
	{magnit_krug: 0},
	{Спрайт10: 0},
	{spraY_dead: 0},
	{Спрайт11: 0},
	{zone_tap: 0},
	{b_restart: 0},
	{Спрайт12: 0},
	{block: 0},
	{zone_tap2: 0},
	{set_of_hexagons_multiple_styles: 0},
	{dlya1: 0},
	{dlya2: 0},
	{dlya3: 0},
	{dlya4: 0},
	{dlya5: 0},
	{dlya6: 0},
	{dlya7: 0},
	{dlya8: 0},
	{dlya9: 0},
	{dlya_snake: 0},
	{Score: 0},
	{start: 0},
	{move: 0},
	{growth: 0},
	{end_okno_game: 0},
	{size_snake: 0},
	{spawn_edi_v_nachale: 0},
	{move_enemy1: 0},
	{growth_enemy1: 0},
	{size_enemy1: 0},
	{move_enemy2: 0},
	{growth_enemy2: 0},
	{size_enemy2: 0},
	{move_enemy3: 0},
	{growth_enemy3: 0},
	{size_enemy3: 0},
	{move_enemy4: 0},
	{growth_enemy4: 0},
	{size_enemy4: 0},
	{move_enemy5: 0},
	{growth_enemy5: 0},
	{size_enemy5: 0},
	{move_enemy6: 0},
	{growth_enemy6: 0},
	{size_enemy6: 0},
	{move_enemy7: 0},
	{growth_enemy7: 0},
	{size_enemy7: 0},
	{move_enemy8: 0},
	{growth_enemy8: 0},
	{size_enemy8: 0},
	{move_enemy9: 0},
	{growth_enemy9: 0},
	{size_enemy9: 0},
	{name1: 0},
	{name2: 0},
	{name3: 0},
	{name4: 0},
	{name5: 0},
	{name6: 0},
	{name7: 0},
	{name8: 0},
	{name9: 0},
	{name10: 0},
	{name1_rec: 0},
	{name2_rec: 0},
	{name3_rec: 0},
	{name4_rec: 0},
	{name5_rec: 0},
	{name6_rec: 0},
	{name7_rec: 0},
	{name8_rec: 0},
	{name9_rec: 0},
	{name10_rec: 0},
	{random_name: 0},
	{random_name_poryadok: 0},
	{nachislenie_xp: 0},
	{pc_1_mobile_2: 0},
	{zmeya1: 0},
	{zmeya2: 0},
	{zmeya3: 0},
	{zmeya4: 0},
	{zmeya5: 0},
	{zmeya6: 0},
	{zmeya7: 0},
	{zmeya8: 0},
	{zmeya9: 0},
	{record: 0},
	{coins: 0},
	{sound: 0},
	{level: 0},
	{xp: 0},
	{xp_max: 0},
	{nachislenie_money: 0},
	{bonus_speed: 0},
	{bonus_magnit: 0},
	{AD_vibor: 0},
	{rezhim: 0},
	{skin_eda: 0},
	{skin_snake: 0},
	{skin_snake_kupleno: 0},
	{open_okno_nastroiki: 0}
];

self.InstanceType = {
	snake_head: class extends self.ISpriteInstance {},
	snake_body: class extends self.ISpriteInstance {},
	eda: class extends self.ISpriteInstance {},
	grass: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	ScirraArcade: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	GamePush: class extends self.IInstance {},
	Тач: class extends self.IInstance {},
	fon: class extends self.ISpriteInstance {},
	logomenu: class extends self.ISpriteInstance {},
	txtloader: class extends self.ISpriteInstance {},
	image: class extends self.ISpriteInstance {},
	image2: class extends self.ISpriteInstance {},
	image3: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	image4: class extends self.ISpriteInstance {},
	b_option: class extends self.ISpriteInstance {},
	b_play: class extends self.ISpriteInstance {},
	banner_menu: class extends self.ISpriteInstance {},
	b_bonus1: class extends self.ISpriteInstance {},
	b_bonus2: class extends self.ISpriteInstance {},
	b_bonus3: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	b_sound: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	txt_coin: class extends self.ITextInstance {},
	Текст2: class extends self.ITextInstance {},
	vecteezy_dreamyimmaculateapairofcrossedswordsornatehiltsno_: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	txt_record: class extends self.ITextInstance {},
	O4YIIJ: class extends self.ISpriteInstance {},
	b7be94684794be9a7923e705bdad2c: class extends self.ISpriteInstance {},
	image5: class extends self.ISpriteInstance {},
	w032_n003_315b_p1_: class extends self.ISpriteInstance {},
	txt_level: class extends self.ITextInstance {},
	txt_xp: class extends self.ITextInstance {},
	Сни321231мок: class extends self.ISpriteInstance {},
	but_speed: class extends self.ISpriteInstance {},
	icons8магнит: class extends self.ISpriteInstance {},
	txt_bonus_speed: class extends self.ITextInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	txt_bonus_magnit: class extends self.ITextInstance {},
	b_reklam_coin: class extends self.ISpriteInstance {},
	b_reklam_speed: class extends self.ISpriteInstance {},
	b_reklam_magnit: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	ОбУстройстве: class extends self.IInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	e6c81d1ae349f596b21bd28221f: class extends self.ISpriteInstance {},
	b_home: class extends self.ISpriteInstance {},
	okno_rezhim1: class extends self.ISpriteInstance {},
	b_rezhim1: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	drenderinghexagonaltexturebackground: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	cell: class extends self.ISpriteInstance {},
	snake_head_enemy1: class extends self.ISpriteInstance {},
	snake_body_enemy1: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	okno_tablo: class extends self.ISpriteInstance {},
	Текст4: class extends self.ITextInstance {},
	txt_tablo_1: class extends self.ITextInstance {},
	txt_tablo_2: class extends self.ITextInstance {},
	txt_tablo_3: class extends self.ITextInstance {},
	txt_tablo_4: class extends self.ITextInstance {},
	txt_tablo_5: class extends self.ITextInstance {},
	txt_tablo_6: class extends self.ITextInstance {},
	txt_tablo_7: class extends self.ITextInstance {},
	txt_tablo_8: class extends self.ITextInstance {},
	txt_tablo_9: class extends self.ITextInstance {},
	txt_tablo_10: class extends self.ITextInstance {},
	skin2: class extends self.ISpriteInstance {},
	Текст5: class extends self.ITextInstance {},
	buy_skin1: class extends self.ISpriteInstance {},
	buy_skin1_txt: class extends self.ITextInstance {},
	buy_skin2: class extends self.ISpriteInstance {},
	buy_skin3: class extends self.ISpriteInstance {},
	buy_skin4: class extends self.ISpriteInstance {},
	buy_skin5: class extends self.ISpriteInstance {},
	buy_skin2_txt: class extends self.ITextInstance {},
	buy_skin3_txt: class extends self.ITextInstance {},
	buy_skin4_txt: class extends self.ITextInstance {},
	buy_skin5_txt: class extends self.ITextInstance {},
	buy_skin6: class extends self.ISpriteInstance {},
	buy_skin6_txt: class extends self.ITextInstance {},
	buy_skin7: class extends self.ISpriteInstance {},
	buy_skin8: class extends self.ISpriteInstance {},
	buy_skin9: class extends self.ISpriteInstance {},
	buy_skin10: class extends self.ISpriteInstance {},
	buy_skin7_txt: class extends self.ITextInstance {},
	buy_skin8_txt: class extends self.ITextInstance {},
	buy_skin9_txt: class extends self.ITextInstance {},
	buy_skin10_txt: class extends self.ITextInstance {},
	eda_skin_pokupka1: class extends self.ISpriteInstance {},
	eda_skin_pokupka2: class extends self.ISpriteInstance {},
	eda_skin_pokupka3: class extends self.ISpriteInstance {},
	eda_skin_pokupka4: class extends self.ISpriteInstance {},
	eda_skin_pokupka5: class extends self.ISpriteInstance {},
	eda_skin_pokupka6: class extends self.ISpriteInstance {},
	eda_skin_pokupka7: class extends self.ISpriteInstance {},
	eda_skin_pokupka8: class extends self.ISpriteInstance {},
	skines_krug: class extends self.ISpriteInstance {},
	coin_spawn: class extends self.ISpriteInstance {},
	snake_head_enemy2: class extends self.ISpriteInstance {},
	snake_head_enemy3: class extends self.ISpriteInstance {},
	snake_head_enemy4: class extends self.ISpriteInstance {},
	snake_head_enemy5: class extends self.ISpriteInstance {},
	snake_head_enemy6: class extends self.ISpriteInstance {},
	snake_head_enemy7: class extends self.ISpriteInstance {},
	snake_head_enemy8: class extends self.ISpriteInstance {},
	snake_head_enemy9: class extends self.ISpriteInstance {},
	snake_body_enemy2: class extends self.ISpriteInstance {},
	snake_body_enemy3: class extends self.ISpriteInstance {},
	snake_body_enemy4: class extends self.ISpriteInstance {},
	snake_body_enemy5: class extends self.ISpriteInstance {},
	snake_body_enemy6: class extends self.ISpriteInstance {},
	snake_body_enemy7: class extends self.ISpriteInstance {},
	snake_body_enemy8: class extends self.ISpriteInstance {},
	snake_body_enemy9: class extends self.ISpriteInstance {},
	O4YIIJ2: class extends self.ISpriteInstance {},
	Текст6: class extends self.ITextInstance {},
	b_reklam_restart: class extends self.ISpriteInstance {},
	txt_vibor_upr: class extends self.ITextInstance {},
	txt_vibor_upr1: class extends self.ITextInstance {},
	txt_vibor_upr2: class extends self.ITextInstance {},
	magnit_krug: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	spraY_dead: class extends self.IParticlesInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	zone_tap: class extends self.ISpriteInstance {},
	b_restart: class extends self.ISpriteInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	block: class extends self.ISpriteInstance {},
	zone_tap2: class extends self.ISpriteInstance {},
	set_of_hexagons_multiple_styles: class extends self.ISpriteInstance {},
	dlya1: class extends self.ISpriteInstance {},
	dlya2: class extends self.ISpriteInstance {},
	dlya3: class extends self.ISpriteInstance {},
	dlya4: class extends self.ISpriteInstance {},
	dlya5: class extends self.ISpriteInstance {},
	dlya6: class extends self.ISpriteInstance {},
	dlya7: class extends self.ISpriteInstance {},
	dlya8: class extends self.ISpriteInstance {},
	dlya9: class extends self.ISpriteInstance {},
	dlya_snake: class extends self.ISpriteInstance {}
}