const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Shape3D,
		C3.Behaviors.Bullet,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Camera3D,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Plugins.gamepad,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.Physics,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Plugins.Text,
		C3.Plugins.NinePatch,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Tilemap.Acts.SetTileRange,
		C3.Plugins.Tilemap.Exps.TileWidth,
		C3.Plugins.Tilemap.Exps.TileHeight,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.AdvancedRandom.Exps.Voronoi2d,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Tilemap.Acts.EraseTileWithBrush,
		C3.Plugins.AdvancedRandom.Exps.Ridged2d,
		C3.Plugins.Tilemap.Acts.SetTileWithBrush,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.TiledBg.Acts.AddChild,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.TagAt,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Exps.LayerToLayerX,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Camera3D.Exps.LayerToLayerY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Behaviors.Tween.Exps.Progress,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.EightDir.Exps.VectorY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Camera3D.Exps.CameraZ,
		C3.Plugins.Camera3D.Exps.LookX,
		C3.Plugins.Camera3D.Exps.LookY,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.float,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Shape3D.Acts.SetBoolInstanceVar,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.Shape3D.Acts.SetOpacity,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Shape3D.Acts.SetZHeight,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.Shape3D.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Shape3D.Acts.SetEffectParam,
		C3.Behaviors.EightDir.Exps.Speed,
		C3.Behaviors.EightDir.Exps.MaxSpeed,
		C3.Behaviors.EightDir.Exps.MovingAngle,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.ImageWidth,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.Shape3D.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.Arr.Acts.Pop,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.EightDir.Exps.VectorX,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.NinePatch.Cnds.CompareWidth,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Text.Exps.TagAt,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Audio.Acts.Preload,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.gamepad.Cnds.OnAnyButtonDown,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Text.Acts.SetPos
	];
};
self.C3_JsPropNameTable = [
	{xPos: 0},
	{yPos: 0},
	{zPos: 0},
	{MuzzleFlash: 0},
	{ProjectileHit: 0},
	{inPool: 0},
	{AncientBlast: 0},
	{TexAncientBlast: 0},
	{enemyLock: 0},
	{alive: 0},
	{damage: 0},
	{Bullet: 0},
	{Tween: 0},
	{Timer: 0},
	{MagicMissile: 0},
	{MagicMissileParticle: 0},
	{MagicMissileBillboard: 0},
	{Rotate: 0},
	{Sine: 0},
	{LeechAura: 0},
	{Meteor: 0},
	{TexMeteor: 0},
	{goBack: 0},
	{ArcaneStar: 0},
	{Trap: 0},
	{"3DCamera": 0},
	{AdvancedRandom: 0},
	{Keyboard: 0},
	{ArrTemp: 0},
	{AJAX: 0},
	{DictSkill: 0},
	{DictProfile: 0},
	{LocalStorage: 0},
	{DictWaveTimes: 0},
	{ArrWaves: 0},
	{ArrCredits: 0},
	{Gamepad: 0},
	{Audio: 0},
	{TiledBackground: 0},
	{TileGrass: 0},
	{TilePaths: 0},
	{WorldLimiter: 0},
	{TilePlants: 0},
	{WorldLimiterShape: 0},
	{TexWorldLimiter: 0},
	{hp: 0},
	{maxSpeed: 0},
	{expOrbType: 0},
	{Physics: 0},
	{BoundToLayout: 0},
	{Enemy: 0},
	{size: 0},
	{EnemyBillboard: 0},
	{EnemySeparator: 0},
	{TexEnemy0: 0},
	{EnemyHitter: 0},
	{TexEnemy1: 0},
	{TexEnemy2: 0},
	{TexEnemy3: 0},
	{TexEnemy4: 0},
	{TexEnemy5: 0},
	{TexEnemy6: 0},
	{TexEnemy7: 0},
	{TexEnemy8: 0},
	{TexEnemy9: 0},
	{currentTime: 0},
	{waveEnemy: 0},
	{waveAmount: 0},
	{waveFrequency: 0},
	{GameManager: 0},
	{level: 0},
	{exp: 0},
	{invincible: 0},
	{baseHp: 0},
	{maxHp: 0},
	{baseSpeed: 0},
	{expPickupRange: 0},
	{numOfSlots: 0},
	{magicMissiles: 0},
	{leechAura: 0},
	{meteorShower: 0},
	{ancientBlast: 0},
	{arcaneStar: 0},
	{trapBoots: 0},
	{vitalityPendant: 0},
	{eagernessRing: 0},
	{socksOfHurry: 0},
	{"8Direction": 0},
	{Player: 0},
	{PlayerBillboard: 0},
	{TexPlayer: 0},
	{SkillUpgradeUI: 0},
	{SkillUpgradeIcon: 0},
	{current: 0},
	{SkillUpgradeSelection: 0},
	{TextSkillDescription: 0},
	{TextCountdown: 0},
	{TopBarUI: 0},
	{ExpBar: 0},
	{SkillSlotLevel: 0},
	{SkillSlot: 0},
	{PlayerHealthbar: 0},
	{PlayerHealthbarBG: 0},
	{PauseUI: 0},
	{PauseSelection: 0},
	{PauseIcon: 0},
	{GameOverUI: 0},
	{HurtMarkUI: 0},
	{VignetteUI: 0},
	{TutorialUI: 0},
	{Bush: 0},
	{TexBush0: 0},
	{TexBush1: 0},
	{TexBush2: 0},
	{TexBush3: 0},
	{TexBush4: 0},
	{TexBush5: 0},
	{TexBush6: 0},
	{TexBush7: 0},
	{TexBush8: 0},
	{PropBillboard: 0},
	{TexPropBillboard0: 0},
	{TexPropBillboard1: 0},
	{TexPropBillboard2: 0},
	{Solid: 0},
	{PropCollider: 0},
	{TexPropBillboard3: 0},
	{TexPropBillboard4: 0},
	{TexPropBillboard5: 0},
	{Fader: 0},
	{TextGeneric: 0},
	{SubFader: 0},
	{expAmt: 0},
	{ExpOrb: 0},
	{TexExpOrb0: 0},
	{TexExpOrb1: 0},
	{TexExpOrb2: 0},
	{currPos: 0},
	{MenuCam: 0},
	{leftPress: 0},
	{rightPress: 0},
	{upPress: 0},
	{downPress: 0},
	{description: 0},
	{soulCost: 0},
	{upgradedDesc: 0},
	{MenuButton: 0},
	{Flash: 0},
	{TextPressSpace: 0},
	{TextTitle: 0},
	{TextTitleShadow: 0},
	{currentButton: 0},
	{MenuButtonSelector: 0},
	{MenuButtonLevel: 0},
	{MenuSoulsIcon: 0},
	{MenuSoulsTextIcon: 0},
	{currCredits: 0},
	{CreditsCam: 0},
	{Enemies: 0},
	{PropCols: 0},
	{CAMERA_SPEED: 0},
	{CAMERA_Z: 0},
	{CAMERA_OFFSET: 0},
	{STARTING_TIME: 0},
	{BGM_GAME_VOLUME: 0},
	{SFX_SKILLS_VOLUME: 0},
	{killCount: 0},
	{inputFocus: 0},
	{posX: 0},
	{posY: 0},
	{canCreate: 0},
	{currentProp: 0},
	{maxProps: 0},
	{minimumDistance: 0},
	{centerX: 0},
	{centerY: 0},
	{randomAmt: 0},
	{randomOffset: 0},
	{withProps: 0},
	{camX: 0},
	{camY: 0},
	{offsetY: 0},
	{type: 0},
	{x: 0},
	{y: 0},
	{xyRepos: 0},
	{dist: 0},
	{theta: 0},
	{validPosition: 0},
	{xyPos: 0},
	{enemyType: 0},
	{EAGERNESS_RING_BASE: 0},
	{delta: 0},
	{skill: 0},
	{MS_BASE_COOLDOWN: 0},
	{MS_COOLDOWN_DEC: 0},
	{MS_BASE_DAMAGE: 0},
	{MS_DAMAGE_INC: 0},
	{MS_BASE_AREA: 0},
	{MS_AREA_INC: 0},
	{meteorShowerSize: 0},
	{leechAuraSize: 0},
	{TB_BASE_COOLDOWN: 0},
	{TB_BASE_DAMAGE: 0},
	{TB_DAMAGE_INC: 0},
	{canPlace: 0},
	{AB_BASE_COOLDOWN: 0},
	{AB_COOLDOWN_DEC: 0},
	{AB_BASE_DAMAGE: 0},
	{AB_DAMAGE_INC: 0},
	{AB_BASE_AREA: 0},
	{AB_AREA_INC: 0},
	{AB_TWEEN_TIME_INC: 0},
	{ab_area: 0},
	{AS_BASE_COOLDOWN: 0},
	{AS_COOLDOWN_DEC: 0},
	{AS_BASE_DAMAGE: 0},
	{AS_DAMAGE_INC: 0},
	{MM_BASE_COOLDOWN: 0},
	{MM_COOLDOWN_DEC: 0},
	{MM_BASE_DAMAGE: 0},
	{MM_DAMAGE_INC: 0},
	{enemyX: 0},
	{enemyY: 0},
	{enemyUID: 0},
	{skillLevel: 0},
	{returnValue: 0},
	{emptySlots: 0},
	{MAX_EXP_BAR_SIZE: 0},
	{BGM_MENU_VOLUME: 0},
	{SFX_VOLUME: 0},
	{menuInputFocus: 0},
	{text: 0},
	{moveSelector: 0},
	{resetProgress: 0},
	{button: 0},
	{coordX: 0},
	{coordY: 0}
];

self.InstanceType = {
	MuzzleFlash: class extends self.ISpriteInstance {},
	ProjectileHit: class extends self.ISpriteInstance {},
	AncientBlast: class extends self.I3DShapeInstance {},
	TexAncientBlast: class extends self.ISpriteInstance {},
	MagicMissile: class extends self.I3DShapeInstance {},
	MagicMissileParticle: class extends self.IParticlesInstance {},
	MagicMissileBillboard: class extends self.I3DShapeInstance {},
	LeechAura: class extends self.ISpriteInstance {},
	Meteor: class extends self.I3DShapeInstance {},
	TexMeteor: class extends self.ISpriteInstance {},
	ArcaneStar: class extends self.ISpriteInstance {},
	Trap: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	AdvancedRandom: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	ArrTemp: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	DictSkill: class extends self.IDictionaryInstance {},
	DictProfile: class extends self.IDictionaryInstance {},
	LocalStorage: class extends self.IInstance {},
	DictWaveTimes: class extends self.IDictionaryInstance {},
	ArrWaves: class extends self.IArrayInstance {},
	ArrCredits: class extends self.IArrayInstance {},
	Gamepad: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TileGrass: class extends self.ITilemapInstance {},
	TilePaths: class extends self.ITilemapInstance {},
	WorldLimiter: class extends self.ITiledBackgroundInstance {},
	TilePlants: class extends self.ITilemapInstance {},
	WorldLimiterShape: class extends self.I3DShapeInstance {},
	TexWorldLimiter: class extends self.ITiledBackgroundInstance {},
	Enemy: class extends self.ISpriteInstance {},
	EnemyBillboard: class extends self.I3DShapeInstance {},
	EnemySeparator: class extends self.ISpriteInstance {},
	TexEnemy0: class extends self.ISpriteInstance {},
	EnemyHitter: class extends self.ISpriteInstance {},
	TexEnemy1: class extends self.ISpriteInstance {},
	TexEnemy2: class extends self.ISpriteInstance {},
	TexEnemy3: class extends self.ISpriteInstance {},
	TexEnemy4: class extends self.ISpriteInstance {},
	TexEnemy5: class extends self.ISpriteInstance {},
	TexEnemy6: class extends self.ISpriteInstance {},
	TexEnemy7: class extends self.ISpriteInstance {},
	TexEnemy8: class extends self.ISpriteInstance {},
	TexEnemy9: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	PlayerBillboard: class extends self.I3DShapeInstance {},
	TexPlayer: class extends self.ISpriteInstance {},
	SkillUpgradeUI: class extends self.ISpriteInstance {},
	SkillUpgradeIcon: class extends self.ISpriteInstance {},
	SkillUpgradeSelection: class extends self.ISpriteInstance {},
	TextSkillDescription: class extends self.ITextInstance {},
	TextCountdown: class extends self.ITextInstance {},
	TopBarUI: class extends self.ISpriteInstance {},
	ExpBar: class extends self.IWorldInstance {},
	SkillSlotLevel: class extends self.ISpriteInstance {},
	SkillSlot: class extends self.ISpriteInstance {},
	PlayerHealthbar: class extends self.ITiledBackgroundInstance {},
	PlayerHealthbarBG: class extends self.ITiledBackgroundInstance {},
	PauseUI: class extends self.ISpriteInstance {},
	PauseSelection: class extends self.ISpriteInstance {},
	PauseIcon: class extends self.ISpriteInstance {},
	GameOverUI: class extends self.ISpriteInstance {},
	HurtMarkUI: class extends self.ISpriteInstance {},
	VignetteUI: class extends self.ISpriteInstance {},
	TutorialUI: class extends self.ISpriteInstance {},
	Bush: class extends self.I3DShapeInstance {},
	TexBush0: class extends self.ISpriteInstance {},
	TexBush1: class extends self.ISpriteInstance {},
	TexBush2: class extends self.ISpriteInstance {},
	TexBush3: class extends self.ISpriteInstance {},
	TexBush4: class extends self.ISpriteInstance {},
	TexBush5: class extends self.ISpriteInstance {},
	TexBush6: class extends self.ISpriteInstance {},
	TexBush7: class extends self.ISpriteInstance {},
	TexBush8: class extends self.ISpriteInstance {},
	PropBillboard: class extends self.I3DShapeInstance {},
	TexPropBillboard0: class extends self.ISpriteInstance {},
	TexPropBillboard1: class extends self.ISpriteInstance {},
	TexPropBillboard2: class extends self.ISpriteInstance {},
	PropCollider: class extends self.ISpriteInstance {},
	TexPropBillboard3: class extends self.ISpriteInstance {},
	TexPropBillboard4: class extends self.ISpriteInstance {},
	TexPropBillboard5: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	TextGeneric: class extends self.ITextInstance {},
	SubFader: class extends self.ITiledBackgroundInstance {},
	ExpOrb: class extends self.I3DShapeInstance {},
	TexExpOrb0: class extends self.ISpriteInstance {},
	TexExpOrb1: class extends self.ISpriteInstance {},
	TexExpOrb2: class extends self.ISpriteInstance {},
	MenuCam: class extends self.ISpriteInstance {},
	MenuButton: class extends self.ISpriteInstance {},
	TextPressSpace: class extends self.ITextInstance {},
	TextTitle: class extends self.ITextInstance {},
	TextTitleShadow: class extends self.ITextInstance {},
	MenuButtonSelector: class extends self.ISpriteInstance {},
	MenuButtonLevel: class extends self.ISpriteInstance {},
	MenuSoulsIcon: class extends self.ISpriteInstance {},
	MenuSoulsTextIcon: class extends self.ISpriteInstance {},
	CreditsCam: class extends self.ISpriteInstance {},
	Enemies: class extends self.ISpriteInstance {},
	PropCols: class extends self.ISpriteInstance {}
}