const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Rotate,
		C3.Plugins.Touch,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Behaviors.Flash,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Rotate.Cnds.IsEnabled,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.OnLoadFailed
	];
};
self.C3_JsPropNameTable = [
	{Физика: 0},
	{doska: 0},
	{zakruchen: 0},
	{vibran: 0},
	{Поворот: 0},
	{bolt1: 0},
	{Тач: 0},
	{zanyato: 0},
	{tochka_zakrutka: 0},
	{k7t_5f4f_6: 0},
	{k7t_5f4f_7: 0},
	{GamePush: 0},
	{back: 0},
	{Якорь: 0},
	{backmenu: 0},
	{binfo: 0},
	{bsound: 0},
	{bvmenu: 0},
	{brestart: 0},
	{Мигание: 0},
	{oknotimer: 0},
	{Z_2101w017n001353Bp8: 0},
	{Синусоида: 0},
	{bplay: 0},
	{bclose: 0},
	{Аудио: 0},
	{txt_level_menu: 0},
	{ЛокальноеХранилище: 0},
	{txt_info: 0},
	{txt_level_menu2: 0},
	{timer: 0},
	{txt_level: 0},
	{txt_winner_true: 0},
	{brestart2: 0},
	{set_of_six_screw_heads_flat_style: 0},
	{redzone: 0},
	{TEST: 0},
	{brown_wooden_vector_texture: 0},
	{bsbros: 0},
	{Z_2101w017n001354Bp: 0},
	{Z_2101w017n001354Bp2: 0},
	{pngwingcom: 0},
	{pngwingcom2: 0},
	{pngwingcom3: 0},
	{txt_loader: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{played: 0},
	{win_1_lose_2: 0},
	{zadacha: 0},
	{vipoln: 0},
	{vibran_bolt: 0},
	{Level: 0},
	{info: 0},
	{sou: 0}
];

self.InstanceType = {
	doska: class extends self.ISpriteInstance {},
	bolt1: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	tochka_zakrutka: class extends self.ISpriteInstance {},
	k7t_5f4f_6: class extends self.ISpriteInstance {},
	k7t_5f4f_7: class extends self.ISpriteInstance {},
	GamePush: class extends self.IInstance {},
	back: class extends self.ITiledBackgroundInstance {},
	backmenu: class extends self.ISpriteInstance {},
	binfo: class extends self.ISpriteInstance {},
	bsound: class extends self.ISpriteInstance {},
	bvmenu: class extends self.ISpriteInstance {},
	brestart: class extends self.ISpriteInstance {},
	oknotimer: class extends self.ISpriteInstance {},
	Z_2101w017n001353Bp8: class extends self.ISpriteInstance {},
	bplay: class extends self.ISpriteInstance {},
	bclose: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	txt_level_menu: class extends self.ITextInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	txt_info: class extends self.ITextInstance {},
	txt_level_menu2: class extends self.ITextInstance {},
	timer: class extends self.ITextInstance {},
	txt_level: class extends self.ITextInstance {},
	txt_winner_true: class extends self.ITextInstance {},
	brestart2: class extends self.ISpriteInstance {},
	set_of_six_screw_heads_flat_style: class extends self.ISpriteInstance {},
	redzone: class extends self.ISpriteInstance {},
	TEST: class extends self.ITextInstance {},
	brown_wooden_vector_texture: class extends self.ISpriteInstance {},
	bsbros: class extends self.ISpriteInstance {},
	Z_2101w017n001354Bp: class extends self.ISpriteInstance {},
	Z_2101w017n001354Bp2: class extends self.ISpriteInstance {},
	pngwingcom: class extends self.ISpriteInstance {},
	pngwingcom2: class extends self.ISpriteInstance {},
	pngwingcom3: class extends self.ISpriteInstance {},
	txt_loader: class extends self.ITextInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {}
}