const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.Timer,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Plugins.gamepad,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.TileMovement.Acts.SetEnabled,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsShare,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.OnLoadFailed
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Wall: 0},
	{TileMovement: 0},
	{СледитьЗа: 0},
	{Player: 0},
	{TimeCounter: 0},
	{Range: 0},
	{Flash: 0},
	{Timer: 0},
	{Синусоида: 0},
	{Bomb: 0},
	{Keyboard: 0},
	{walldestroy: 0},
	{Ground: 0},
	{Direction: 0},
	{Enemy1: 0},
	{Tween: 0},
	{Flame: 0},
	{Dust: 0},
	{Gamepad: 0},
	{Fade: 0},
	{TextFont: 0},
	{TextBackground: 0},
	{Тач: 0},
	{GamePush: 0},
	{ОбУстройстве: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{Твёрдый: 0},
	{walle: 0},
	{OD34SV2: 0},
	{OD34SV3: 0},
	{dd2e158743045e4b26182872fec570c: 0},
	{pol: 0},
	{wal: 0},
	{OD34SV6: 0},
	{ТайловыйФон: 0},
	{Спрайт3: 0},
	{txt_level: 0},
	{b_up: 0},
	{dver: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{Аудио: 0},
	{but_bomb: 0},
	{b_down: 0},
	{b_left: 0},
	{b_right: 0},
	{winner_okno: 0},
	{b_prodolzhite: 0},
	{txt_win: 0},
	{txt_but_win: 0},
	{okno_menu: 0},
	{b_pause: 0},
	{txt_menu: 0},
	{txt_menu2: 0},
	{b_sound: 0},
	{Player_decor: 0},
	{b_play: 0},
	{b_soc: 0},
	{pngwingcom: 0},
	{version: 0},
	{instr_PC: 0},
	{pause: 0},
	{Level: 0},
	{Menu: 0},
	{win: 0},
	{sound: 0},
	{ExplosionRange: 0},
	{XOffset: 0},
	{YOffset: 0}
];

self.InstanceType = {
	Wall: class extends self.ITilemapInstance {},
	Player: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	walldestroy: class extends self.ISpriteInstance {},
	Ground: class extends self.ITilemapInstance {},
	Enemy1: class extends self.ISpriteInstance {},
	Flame: class extends self.ISpriteInstance {},
	Dust: class extends self.IParticlesInstance {},
	Gamepad: class extends self.IInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	TextBackground: class extends self.ITiledBackgroundInstance {},
	Тач: class extends self.IInstance {},
	GamePush: class extends self.IInstance {},
	ОбУстройстве: class extends self.IInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	walle: class extends self.ISpriteInstance {},
	OD34SV2: class extends self.ISpriteInstance {},
	OD34SV3: class extends self.ISpriteInstance {},
	dd2e158743045e4b26182872fec570c: class extends self.ISpriteInstance {},
	pol: class extends self.ISpriteInstance {},
	wal: class extends self.ISpriteInstance {},
	OD34SV6: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	txt_level: class extends self.ITextInstance {},
	b_up: class extends self.ISpriteInstance {},
	dver: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	but_bomb: class extends self.ISpriteInstance {},
	b_down: class extends self.ISpriteInstance {},
	b_left: class extends self.ISpriteInstance {},
	b_right: class extends self.ISpriteInstance {},
	winner_okno: class extends self.ISpriteInstance {},
	b_prodolzhite: class extends self.ISpriteInstance {},
	txt_win: class extends self.ITextInstance {},
	txt_but_win: class extends self.ITextInstance {},
	okno_menu: class extends self.ISpriteInstance {},
	b_pause: class extends self.ISpriteInstance {},
	txt_menu: class extends self.ITextInstance {},
	txt_menu2: class extends self.ITextInstance {},
	b_sound: class extends self.ISpriteInstance {},
	Player_decor: class extends self.ISpriteInstance {},
	b_play: class extends self.ISpriteInstance {},
	b_soc: class extends self.ISpriteInstance {},
	pngwingcom: class extends self.ISpriteInstance {},
	version: class extends self.ITextInstance {},
	instr_PC: class extends self.ITextInstance {}
}