const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Touch,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.OnLoadFailed,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{startX: 0},
	{startY: 0},
	{DragDrop: 0},
	{Block1: 0},
	{zanyato: 0},
	{Cell1: 0},
	{Мигание: 0},
	{schet: 0},
	{photo_20231003_: 0},
	{Спрайт: 0},
	{butlevels: 0},
	{Тач: 0},
	{butbacktomenu: 0},
	{decorkubok: 0},
	{Якорь: 0},
	{Спрайт2: 0},
	{txtAdventure: 0},
	{bl1: 0},
	{butlevel: 0},
	{txtlevel_levls: 0},
	{bl2: 0},
	{bl3: 0},
	{bl4: 0},
	{bl5: 0},
	{bl6: 0},
	{bl7: 0},
	{bl8: 0},
	{bl9: 0},
	{bl10: 0},
	{bl11: 0},
	{bl12: 0},
	{bl13: 0},
	{bl14: 0},
	{bl15: 0},
	{bl16: 0},
	{bl17: 0},
	{bl18: 0},
	{bl19: 0},
	{bl20: 0},
	{bl21: 0},
	{bl22: 0},
	{bl23: 0},
	{bl24: 0},
	{bl25: 0},
	{bl26: 0},
	{bl27: 0},
	{bl28: 0},
	{bl29: 0},
	{bl30: 0},
	{bl31: 0},
	{bl32: 0},
	{bl33: 0},
	{bl34: 0},
	{bl35: 0},
	{bl36: 0},
	{bl37: 0},
	{bl38: 0},
	{bl39: 0},
	{bl40: 0},
	{bl41: 0},
	{bl42: 0},
	{bl43: 0},
	{bl44: 0},
	{bl45: 0},
	{bl46: 0},
	{bl47: 0},
	{bl48: 0},
	{bl49: 0},
	{bl50: 0},
	{numLevels: 0},
	{Синусоид: 0},
	{strelkaLevels: 0},
	{test1: 0},
	{test2: 0},
	{test3: 0},
	{test4: 0},
	{test5: 0},
	{test6: 0},
	{test7: 0},
	{test8: 0},
	{Cell2: 0},
	{Cell3: 0},
	{Cell4: 0},
	{Cell5: 0},
	{Cell6: 0},
	{Cell7: 0},
	{Cell8: 0},
	{line1: 0},
	{line2: 0},
	{Block1zapolnenie: 0},
	{spawner1: 0},
	{spawner2: 0},
	{spawner3: 0},
	{test9: 0},
	{test10: 0},
	{test11: 0},
	{Cell9: 0},
	{Cell10: 0},
	{Cell11: 0},
	{Cell12: 0},
	{Cell13: 0},
	{Cell14: 0},
	{Cell15: 0},
	{Cell16: 0},
	{Cell17: 0},
	{Cell18: 0},
	{Cell19: 0},
	{Cell20: 0},
	{Cell21: 0},
	{Cell22: 0},
	{Cell23: 0},
	{Cell24: 0},
	{Cell25: 0},
	{Cell26: 0},
	{Cell27: 0},
	{Cell28: 0},
	{Cell29: 0},
	{Cell30: 0},
	{Cell31: 0},
	{Cell32: 0},
	{Cell33: 0},
	{Cell34: 0},
	{Cell35: 0},
	{Cell36: 0},
	{Cell37: 0},
	{Cell38: 0},
	{Cell39: 0},
	{Cell40: 0},
	{Cell41: 0},
	{Cell42: 0},
	{Cell43: 0},
	{Cell44: 0},
	{Cell45: 0},
	{Cell46: 0},
	{Cell47: 0},
	{Cell48: 0},
	{Cell49: 0},
	{Cell50: 0},
	{Cell51: 0},
	{Cell52: 0},
	{Cell53: 0},
	{Cell54: 0},
	{Cell55: 0},
	{Cell56: 0},
	{Cell57: 0},
	{Cell58: 0},
	{Cell59: 0},
	{Cell60: 0},
	{Cell61: 0},
	{Cell62: 0},
	{Cell63: 0},
	{Cell64: 0},
	{line3: 0},
	{line4: 0},
	{line5: 0},
	{line6: 0},
	{line7: 0},
	{line8: 0},
	{anglee: 0},
	{Block2: 0},
	{Block3: 0},
	{Block4: 0},
	{Block5: 0},
	{Block6: 0},
	{redzone: 0},
	{line9: 0},
	{line10: 0},
	{line11: 0},
	{line12: 0},
	{line13: 0},
	{line14: 0},
	{line15: 0},
	{line16: 0},
	{test12: 0},
	{test13: 0},
	{test14: 0},
	{test15: 0},
	{test16: 0},
	{test17: 0},
	{test18: 0},
	{test19: 0},
	{test20: 0},
	{test21: 0},
	{test22: 0},
	{test23: 0},
	{test24: 0},
	{test25: 0},
	{test26: 0},
	{test27: 0},
	{test28: 0},
	{test29: 0},
	{test30: 0},
	{test31: 0},
	{test32: 0},
	{test33: 0},
	{test34: 0},
	{test35: 0},
	{test36: 0},
	{test37: 0},
	{test38: 0},
	{test39: 0},
	{test40: 0},
	{test41: 0},
	{test42: 0},
	{test43: 0},
	{test44: 0},
	{test45: 0},
	{test46: 0},
	{test47: 0},
	{test48: 0},
	{test49: 0},
	{test50: 0},
	{test51: 0},
	{test52: 0},
	{test53: 0},
	{test54: 0},
	{test55: 0},
	{test56: 0},
	{test57: 0},
	{test58: 0},
	{test59: 0},
	{test60: 0},
	{test61: 0},
	{test62: 0},
	{test63: 0},
	{test64: 0},
	{test65: 0},
	{test66: 0},
	{butendless: 0},
	{pngwingcom: 0},
	{schetRecEndless: 0},
	{boption: 0},
	{backgrounds: 0},
	{tileback: 0},
	{grafica: 0},
	{grafica2: 0},
	{grafica3: 0},
	{butlevels2: 0},
	{butendless2: 0},
	{version: 0},
	{tileback2: 0},
	{Аудио: 0},
	{zapolnenieKubok: 0},
	{Спрайт3: 0},
	{iconkaBP: 0},
	{zastav1ka: 0},
	{bl51: 0},
	{oknomenu: 0},
	{bvmenuu: 0},
	{bplayy: 0},
	{brestartt: 0},
	{levelgn: 0},
	{bsoundd: 0},
	{bloccker: 0},
	{shkaladec: 0},
	{krugdec: 0},
	{schetceli: 0},
	{zastav1ka2: 0},
	{image: 0},
	{image2: 0},
	{freeiconequaltoorgreaterthansymbol: 0},
	{form_1b: 0},
	{Blocks: 0},
	{cell: 0},
	{Blzapolnenie: 0},
	{"7blocks": 0},
	{zadacha: 0},
	{schetzachislenie: 0},
	{cell_schet: 0},
	{"3figursSpawner": 0},
	{okno_menu: 0},
	{Loader_starter_timer: 0},
	{Loader_timer: 0},
	{Levels: 0},
	{rezhim: 0},
	{sound: 0},
	{music: 0},
	{recordEndless: 0},
	{kubok: 0}
];

self.InstanceType = {
	Block1: class extends self.ISpriteInstance {},
	Cell1: class extends self.ISpriteInstance {},
	schet: class extends self.ITextInstance {},
	photo_20231003_: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	butlevels: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	butbacktomenu: class extends self.ISpriteInstance {},
	decorkubok: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	txtAdventure: class extends self.ITextInstance {},
	bl1: class extends self.ISpriteInstance {},
	butlevel: class extends self.ISpriteInstance {},
	txtlevel_levls: class extends self.ITextInstance {},
	bl2: class extends self.ISpriteInstance {},
	bl3: class extends self.ISpriteInstance {},
	bl4: class extends self.ISpriteInstance {},
	bl5: class extends self.ISpriteInstance {},
	bl6: class extends self.ISpriteInstance {},
	bl7: class extends self.ISpriteInstance {},
	bl8: class extends self.ISpriteInstance {},
	bl9: class extends self.ISpriteInstance {},
	bl10: class extends self.ISpriteInstance {},
	bl11: class extends self.ISpriteInstance {},
	bl12: class extends self.ISpriteInstance {},
	bl13: class extends self.ISpriteInstance {},
	bl14: class extends self.ISpriteInstance {},
	bl15: class extends self.ISpriteInstance {},
	bl16: class extends self.ISpriteInstance {},
	bl17: class extends self.ISpriteInstance {},
	bl18: class extends self.ISpriteInstance {},
	bl19: class extends self.ISpriteInstance {},
	bl20: class extends self.ISpriteInstance {},
	bl21: class extends self.ISpriteInstance {},
	bl22: class extends self.ISpriteInstance {},
	bl23: class extends self.ISpriteInstance {},
	bl24: class extends self.ISpriteInstance {},
	bl25: class extends self.ISpriteInstance {},
	bl26: class extends self.ISpriteInstance {},
	bl27: class extends self.ISpriteInstance {},
	bl28: class extends self.ISpriteInstance {},
	bl29: class extends self.ISpriteInstance {},
	bl30: class extends self.ISpriteInstance {},
	bl31: class extends self.ISpriteInstance {},
	bl32: class extends self.ISpriteInstance {},
	bl33: class extends self.ISpriteInstance {},
	bl34: class extends self.ISpriteInstance {},
	bl35: class extends self.ISpriteInstance {},
	bl36: class extends self.ISpriteInstance {},
	bl37: class extends self.ISpriteInstance {},
	bl38: class extends self.ISpriteInstance {},
	bl39: class extends self.ISpriteInstance {},
	bl40: class extends self.ISpriteInstance {},
	bl41: class extends self.ISpriteInstance {},
	bl42: class extends self.ISpriteInstance {},
	bl43: class extends self.ISpriteInstance {},
	bl44: class extends self.ISpriteInstance {},
	bl45: class extends self.ISpriteInstance {},
	bl46: class extends self.ISpriteInstance {},
	bl47: class extends self.ISpriteInstance {},
	bl48: class extends self.ISpriteInstance {},
	bl49: class extends self.ISpriteInstance {},
	bl50: class extends self.ISpriteInstance {},
	numLevels: class extends self.ITextInstance {},
	strelkaLevels: class extends self.ISpriteInstance {},
	test1: class extends self.ITextInstance {},
	test2: class extends self.ITextInstance {},
	test3: class extends self.ITextInstance {},
	test4: class extends self.ITextInstance {},
	test5: class extends self.ITextInstance {},
	test6: class extends self.ITextInstance {},
	test7: class extends self.ITextInstance {},
	test8: class extends self.ITextInstance {},
	Cell2: class extends self.ISpriteInstance {},
	Cell3: class extends self.ISpriteInstance {},
	Cell4: class extends self.ISpriteInstance {},
	Cell5: class extends self.ISpriteInstance {},
	Cell6: class extends self.ISpriteInstance {},
	Cell7: class extends self.ISpriteInstance {},
	Cell8: class extends self.ISpriteInstance {},
	line1: class extends self.ISpriteInstance {},
	line2: class extends self.ISpriteInstance {},
	Block1zapolnenie: class extends self.ISpriteInstance {},
	spawner1: class extends self.ISpriteInstance {},
	spawner2: class extends self.ISpriteInstance {},
	spawner3: class extends self.ISpriteInstance {},
	test9: class extends self.ITextInstance {},
	test10: class extends self.ITextInstance {},
	test11: class extends self.ITextInstance {},
	Cell9: class extends self.ISpriteInstance {},
	Cell10: class extends self.ISpriteInstance {},
	Cell11: class extends self.ISpriteInstance {},
	Cell12: class extends self.ISpriteInstance {},
	Cell13: class extends self.ISpriteInstance {},
	Cell14: class extends self.ISpriteInstance {},
	Cell15: class extends self.ISpriteInstance {},
	Cell16: class extends self.ISpriteInstance {},
	Cell17: class extends self.ISpriteInstance {},
	Cell18: class extends self.ISpriteInstance {},
	Cell19: class extends self.ISpriteInstance {},
	Cell20: class extends self.ISpriteInstance {},
	Cell21: class extends self.ISpriteInstance {},
	Cell22: class extends self.ISpriteInstance {},
	Cell23: class extends self.ISpriteInstance {},
	Cell24: class extends self.ISpriteInstance {},
	Cell25: class extends self.ISpriteInstance {},
	Cell26: class extends self.ISpriteInstance {},
	Cell27: class extends self.ISpriteInstance {},
	Cell28: class extends self.ISpriteInstance {},
	Cell29: class extends self.ISpriteInstance {},
	Cell30: class extends self.ISpriteInstance {},
	Cell31: class extends self.ISpriteInstance {},
	Cell32: class extends self.ISpriteInstance {},
	Cell33: class extends self.ISpriteInstance {},
	Cell34: class extends self.ISpriteInstance {},
	Cell35: class extends self.ISpriteInstance {},
	Cell36: class extends self.ISpriteInstance {},
	Cell37: class extends self.ISpriteInstance {},
	Cell38: class extends self.ISpriteInstance {},
	Cell39: class extends self.ISpriteInstance {},
	Cell40: class extends self.ISpriteInstance {},
	Cell41: class extends self.ISpriteInstance {},
	Cell42: class extends self.ISpriteInstance {},
	Cell43: class extends self.ISpriteInstance {},
	Cell44: class extends self.ISpriteInstance {},
	Cell45: class extends self.ISpriteInstance {},
	Cell46: class extends self.ISpriteInstance {},
	Cell47: class extends self.ISpriteInstance {},
	Cell48: class extends self.ISpriteInstance {},
	Cell49: class extends self.ISpriteInstance {},
	Cell50: class extends self.ISpriteInstance {},
	Cell51: class extends self.ISpriteInstance {},
	Cell52: class extends self.ISpriteInstance {},
	Cell53: class extends self.ISpriteInstance {},
	Cell54: class extends self.ISpriteInstance {},
	Cell55: class extends self.ISpriteInstance {},
	Cell56: class extends self.ISpriteInstance {},
	Cell57: class extends self.ISpriteInstance {},
	Cell58: class extends self.ISpriteInstance {},
	Cell59: class extends self.ISpriteInstance {},
	Cell60: class extends self.ISpriteInstance {},
	Cell61: class extends self.ISpriteInstance {},
	Cell62: class extends self.ISpriteInstance {},
	Cell63: class extends self.ISpriteInstance {},
	Cell64: class extends self.ISpriteInstance {},
	line3: class extends self.ISpriteInstance {},
	line4: class extends self.ISpriteInstance {},
	line5: class extends self.ISpriteInstance {},
	line6: class extends self.ISpriteInstance {},
	line7: class extends self.ISpriteInstance {},
	line8: class extends self.ISpriteInstance {},
	Block2: class extends self.ISpriteInstance {},
	Block3: class extends self.ISpriteInstance {},
	Block4: class extends self.ISpriteInstance {},
	Block5: class extends self.ISpriteInstance {},
	Block6: class extends self.ISpriteInstance {},
	redzone: class extends self.ISpriteInstance {},
	line9: class extends self.ISpriteInstance {},
	line10: class extends self.ISpriteInstance {},
	line11: class extends self.ISpriteInstance {},
	line12: class extends self.ISpriteInstance {},
	line13: class extends self.ISpriteInstance {},
	line14: class extends self.ISpriteInstance {},
	line15: class extends self.ISpriteInstance {},
	line16: class extends self.ISpriteInstance {},
	test12: class extends self.ITextInstance {},
	test13: class extends self.ITextInstance {},
	test14: class extends self.ITextInstance {},
	test15: class extends self.ITextInstance {},
	test16: class extends self.ITextInstance {},
	test17: class extends self.ITextInstance {},
	test18: class extends self.ITextInstance {},
	test19: class extends self.ITextInstance {},
	test20: class extends self.ITextInstance {},
	test21: class extends self.ITextInstance {},
	test22: class extends self.ITextInstance {},
	test23: class extends self.ITextInstance {},
	test24: class extends self.ITextInstance {},
	test25: class extends self.ITextInstance {},
	test26: class extends self.ITextInstance {},
	test27: class extends self.ITextInstance {},
	test28: class extends self.ITextInstance {},
	test29: class extends self.ITextInstance {},
	test30: class extends self.ITextInstance {},
	test31: class extends self.ITextInstance {},
	test32: class extends self.ITextInstance {},
	test33: class extends self.ITextInstance {},
	test34: class extends self.ITextInstance {},
	test35: class extends self.ITextInstance {},
	test36: class extends self.ITextInstance {},
	test37: class extends self.ITextInstance {},
	test38: class extends self.ITextInstance {},
	test39: class extends self.ITextInstance {},
	test40: class extends self.ITextInstance {},
	test41: class extends self.ITextInstance {},
	test42: class extends self.ITextInstance {},
	test43: class extends self.ITextInstance {},
	test44: class extends self.ITextInstance {},
	test45: class extends self.ITextInstance {},
	test46: class extends self.ITextInstance {},
	test47: class extends self.ITextInstance {},
	test48: class extends self.ITextInstance {},
	test49: class extends self.ITextInstance {},
	test50: class extends self.ITextInstance {},
	test51: class extends self.ITextInstance {},
	test52: class extends self.ITextInstance {},
	test53: class extends self.ITextInstance {},
	test54: class extends self.ITextInstance {},
	test55: class extends self.ITextInstance {},
	test56: class extends self.ITextInstance {},
	test57: class extends self.ITextInstance {},
	test58: class extends self.ITextInstance {},
	test59: class extends self.ITextInstance {},
	test60: class extends self.ITextInstance {},
	test61: class extends self.ITextInstance {},
	test62: class extends self.ITextInstance {},
	test63: class extends self.ITextInstance {},
	test64: class extends self.ITextInstance {},
	test65: class extends self.ITextInstance {},
	test66: class extends self.ITextInstance {},
	butendless: class extends self.ISpriteInstance {},
	pngwingcom: class extends self.ISpriteInstance {},
	schetRecEndless: class extends self.ITextInstance {},
	boption: class extends self.ISpriteInstance {},
	backgrounds: class extends self.ISpriteInstance {},
	tileback: class extends self.ITiledBackgroundInstance {},
	grafica: class extends self.ISpriteInstance {},
	grafica2: class extends self.ISpriteInstance {},
	grafica3: class extends self.ISpriteInstance {},
	butlevels2: class extends self.ISpriteInstance {},
	butendless2: class extends self.ISpriteInstance {},
	version: class extends self.ITextInstance {},
	tileback2: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	zapolnenieKubok: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	iconkaBP: class extends self.ISpriteInstance {},
	zastav1ka: class extends self.ISpriteInstance {},
	bl51: class extends self.ISpriteInstance {},
	oknomenu: class extends self.ISpriteInstance {},
	bvmenuu: class extends self.ISpriteInstance {},
	bplayy: class extends self.ISpriteInstance {},
	brestartt: class extends self.ISpriteInstance {},
	levelgn: class extends self.ITextInstance {},
	bsoundd: class extends self.ISpriteInstance {},
	bloccker: class extends self.ISpriteInstance {},
	shkaladec: class extends self.ISpriteInstance {},
	krugdec: class extends self.ISpriteInstance {},
	schetceli: class extends self.ITextInstance {},
	zastav1ka2: class extends self.ISpriteInstance {},
	image: class extends self.ISpriteInstance {},
	image2: class extends self.ISpriteInstance {},
	freeiconequaltoorgreaterthansymbol: class extends self.ISpriteInstance {},
	form_1b: class extends self.ISpriteInstance {},
	Blocks: class extends self.ISpriteInstance {},
	cell: class extends self.ISpriteInstance {},
	Blzapolnenie: class extends self.ISpriteInstance {},
	_7blocks: class extends self.ISpriteInstance {}
}