const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Behaviors.destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SubVar
	];
};
self.C3_JsPropNameTable = [
	{dec_menu: 0},
	{Тач: 0},
	{ЛокальноеХранилище: 0},
	{dec_menu1: 0},
	{b_play: 0},
	{txt_menu: 0},
	{txt_levels: 0},
	{Якорь: 0},
	{b_home: 0},
	{b_restart: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{txt_winner: 0},
	{shadow: 0},
	{b_winner: 0},
	{icon_winner: 0},
	{txt_winner2: 0},
	{exit: 0},
	{ДвижениеК: 0},
	{ПоискПути: 0},
	{vor: 0},
	{vibran: 0},
	{police1: 0},
	{Пуля: 0},
	{punktir: 0},
	{lines: 0},
	{otmetka: 0},
	{punkt: 0},
	{timeout: 0},
	{start_timer: 0},
	{cel_police1: 0},
	{cel_vor: 0},
	{line1: 0},
	{line2: 0},
	{i: 0},
	{ex: 0},
	{proklad2exit: 0},
	{proklad: 0},
	{line3: 0},
	{line4: 0},
	{police2: 0},
	{police3: 0},
	{police4: 0},
	{cel_police2: 0},
	{Синусоида: 0},
	{instruction: 0},
	{cel_police3: 0},
	{cel_police4: 0},
	{УничтожениеВнеМакета: 0},
	{proklad2: 0},
	{proklad3: 0},
	{proklad4exiter: 0},
	{TEST: 0},
	{Спрайт: 0},
	{exiter1: 0},
	{exiter2: 0},
	{exiter3: 0},
	{exiter4: 0},
	{exiter5: 0},
	{exiter6: 0},
	{exiter7: 0},
	{exiter8: 0},
	{exiter9: 0},
	{exiter10: 0},
	{Level: 0},
	{win_1_lose_2: 0},
	{play_true: 0},
	{colvo_scan: 0}
];

self.InstanceType = {
	dec_menu: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	dec_menu1: class extends self.ISpriteInstance {},
	b_play: class extends self.ISpriteInstance {},
	txt_menu: class extends self.ITextInstance {},
	txt_levels: class extends self.ITextInstance {},
	b_home: class extends self.ISpriteInstance {},
	b_restart: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	txt_winner: class extends self.ITextInstance {},
	shadow: class extends self.ISpriteInstance {},
	b_winner: class extends self.ISpriteInstance {},
	icon_winner: class extends self.ISpriteInstance {},
	txt_winner2: class extends self.ITextInstance {},
	exit: class extends self.ISpriteInstance {},
	vor: class extends self.ISpriteInstance {},
	police1: class extends self.ISpriteInstance {},
	punktir: class extends self.ISpriteInstance {},
	punkt: class extends self.ISpriteInstance {},
	cel_police1: class extends self.ISpriteInstance {},
	cel_vor: class extends self.ISpriteInstance {},
	line1: class extends self.ISpriteInstance {},
	line2: class extends self.ISpriteInstance {},
	proklad2exit: class extends self.ISpriteInstance {},
	proklad: class extends self.ISpriteInstance {},
	line3: class extends self.ISpriteInstance {},
	line4: class extends self.ISpriteInstance {},
	police2: class extends self.ISpriteInstance {},
	police3: class extends self.ISpriteInstance {},
	police4: class extends self.ISpriteInstance {},
	cel_police2: class extends self.ISpriteInstance {},
	instruction: class extends self.ITextInstance {},
	cel_police3: class extends self.ISpriteInstance {},
	cel_police4: class extends self.ISpriteInstance {},
	proklad2: class extends self.ISpriteInstance {},
	proklad3: class extends self.ISpriteInstance {},
	proklad4exiter: class extends self.ISpriteInstance {},
	TEST: class extends self.ITextInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	exiter1: class extends self.ISpriteInstance {},
	exiter2: class extends self.ISpriteInstance {},
	exiter3: class extends self.ISpriteInstance {},
	exiter4: class extends self.ISpriteInstance {},
	exiter5: class extends self.ISpriteInstance {},
	exiter6: class extends self.ISpriteInstance {},
	exiter7: class extends self.ISpriteInstance {},
	exiter8: class extends self.ISpriteInstance {},
	exiter9: class extends self.ISpriteInstance {},
	exiter10: class extends self.ISpriteInstance {}
}