const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.DragnDrop.Acts.Drop,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Behaviors.Physics.Cnds.IsSleeping,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsShare,
		C3.Plugins.Text.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{Якорь: 0},
	{background: 0},
	{Пуля: 0},
	{Заворачивание: 0},
	{oblako1: 0},
	{oblako2: 0},
	{oblako4: 0},
	{oblako3: 0},
	{Синусоида: 0},
	{homyak: 0},
	{shadow: 0},
	{mask_shadow: 0},
	{okno_shop: 0},
	{touch: 0},
	{Аудио: 0},
	{GamePush: 0},
	{p30p_yy9p_: 0},
	{chastica_tap: 0},
	{but_sound: 0},
	{but_lang: 0},
	{Спрайт5: 0},
	{but_X3_AD: 0},
	{but_shop1: 0},
	{txtshop_shop: 0},
	{txt_level: 0},
	{shkala: 0},
	{Клавиатура: 0},
	{txt_coins: 0},
	{txt_coins_vsecundu: 0},
	{ОбУстройстве: 0},
	{pod_shkala: 0},
	{pod_shkala2: 0},
	{flag: 0},
	{txt_X2: 0},
	{DragDrop: 0},
	{Твердый: 0},
	{scroll_bar: 0},
	{Mouse: 0},
	{border: 0},
	{TEST: 0},
	{scroller: 0},
	{but_shop2: 0},
	{but_shop3: 0},
	{but_shop4: 0},
	{but_shop5: 0},
	{but_shop6: 0},
	{but_shop7: 0},
	{but_shop8: 0},
	{but_shop9: 0},
	{but_shop10: 0},
	{txt: 0},
	{cena: 0},
	{plus: 0},
	{vsek_zaklik: 0},
	{txtshopbut1: 0},
	{txtshopbut2: 0},
	{txtshopbut3: 0},
	{txtshopbut4: 0},
	{txtshopbut5: 0},
	{txtshopbut6: 0},
	{txtshopbut7: 0},
	{txtshopbut8: 0},
	{txtshopbut9: 0},
	{bIcon1: 0},
	{bIcon2: 0},
	{bIcon3: 0},
	{bIcon4: 0},
	{bIcon5: 0},
	{bIcon6: 0},
	{bIcon7: 0},
	{bIcon8: 0},
	{bIcon9: 0},
	{Физика: 0},
	{УничтожениеВнеМакета: 0},
	{viletchislo: 0},
	{butrating: 0},
	{Спрайт: 0},
	{timer_x2: 0},
	{indoapr: 0},
	{Снимок: 0},
	{Снимок2: 0},
	{Снимок3: 0},
	{w026n0023882Bp: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{bmenu: 0},
	{brestart: 0},
	{Спрайт4: 0},
	{w032n0021041Ap: 0},
	{txtpause: 0},
	{bplay: 0},
	{pngwingcom: 0},
	{txtsbros: 0},
	{decor_ad: 0},
	{w054n005339Bp: 0},
	{kubok: 0},
	{b_soc_priglashenie: 0},
	{vopros: 0},
	{txt_instr: 0},
	{dec_ad: 0},
	{Level_drako: 0},
	{plus_automation: 0},
	{score: 0},
	{language: 0},
	{chislo_lang: 0},
	{predel_shkala: 0},
	{played: 0},
	{sound: 0},
	{tap_coins: 0},
	{tap_level_shkala: 0},
	{scroll_visota: 0},
	{AD_2min: 0},
	{AD_N: 0},
	{Timer_x2_ogranichenie: 0},
	{menu: 0},
	{instruction: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	oblako1: class extends self.ISpriteInstance {},
	oblako2: class extends self.ISpriteInstance {},
	oblako4: class extends self.ISpriteInstance {},
	oblako3: class extends self.ISpriteInstance {},
	homyak: class extends self.ISpriteInstance {},
	shadow: class extends self.ISpriteInstance {},
	mask_shadow: class extends self.ISpriteInstance {},
	okno_shop: class extends self.ISpriteInstance {},
	touch: class extends self.IInstance {},
	Аудио: class extends self.IInstance {},
	GamePush: class extends self.IInstance {},
	p30p_yy9p_: class extends self.ISpriteInstance {},
	chastica_tap: class extends self.IParticlesInstance {},
	but_sound: class extends self.ISpriteInstance {},
	but_lang: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	but_X3_AD: class extends self.ISpriteInstance {},
	but_shop1: class extends self.ISpriteInstance {},
	txtshop_shop: class extends self.ITextInstance {},
	txt_level: class extends self.ITextInstance {},
	shkala: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	txt_coins: class extends self.ITextInstance {},
	txt_coins_vsecundu: class extends self.ITextInstance {},
	ОбУстройстве: class extends self.IInstance {},
	pod_shkala: class extends self.ISpriteInstance {},
	pod_shkala2: class extends self.ISpriteInstance {},
	flag: class extends self.ISpriteInstance {},
	txt_X2: class extends self.ITextInstance {},
	scroll_bar: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	border: class extends self.ISpriteInstance {},
	TEST: class extends self.ITextInstance {},
	scroller: class extends self.ISpriteInstance {},
	but_shop2: class extends self.ISpriteInstance {},
	but_shop3: class extends self.ISpriteInstance {},
	but_shop4: class extends self.ISpriteInstance {},
	but_shop5: class extends self.ISpriteInstance {},
	but_shop6: class extends self.ISpriteInstance {},
	but_shop7: class extends self.ISpriteInstance {},
	but_shop8: class extends self.ISpriteInstance {},
	but_shop9: class extends self.ISpriteInstance {},
	but_shop10: class extends self.ISpriteInstance {},
	txtshopbut1: class extends self.ITextInstance {},
	txtshopbut2: class extends self.ITextInstance {},
	txtshopbut3: class extends self.ITextInstance {},
	txtshopbut4: class extends self.ITextInstance {},
	txtshopbut5: class extends self.ITextInstance {},
	txtshopbut6: class extends self.ITextInstance {},
	txtshopbut7: class extends self.ITextInstance {},
	txtshopbut8: class extends self.ITextInstance {},
	txtshopbut9: class extends self.ITextInstance {},
	bIcon1: class extends self.ISpriteInstance {},
	bIcon2: class extends self.ISpriteInstance {},
	bIcon3: class extends self.ISpriteInstance {},
	bIcon4: class extends self.ISpriteInstance {},
	bIcon5: class extends self.ISpriteInstance {},
	bIcon6: class extends self.ISpriteInstance {},
	bIcon7: class extends self.ISpriteInstance {},
	bIcon8: class extends self.ISpriteInstance {},
	bIcon9: class extends self.ISpriteInstance {},
	viletchislo: class extends self.ITextInstance {},
	butrating: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	timer_x2: class extends self.ITextInstance {},
	indoapr: class extends self.ISpriteInstance {},
	Снимок: class extends self.ISpriteInstance {},
	Снимок2: class extends self.ISpriteInstance {},
	Снимок3: class extends self.ISpriteInstance {},
	w026n0023882Bp: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	bmenu: class extends self.ISpriteInstance {},
	brestart: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	w032n0021041Ap: class extends self.ISpriteInstance {},
	txtpause: class extends self.ITextInstance {},
	bplay: class extends self.ISpriteInstance {},
	pngwingcom: class extends self.ISpriteInstance {},
	txtsbros: class extends self.ITextInstance {},
	decor_ad: class extends self.ISpriteInstance {},
	w054n005339Bp: class extends self.ISpriteInstance {},
	kubok: class extends self.ISpriteInstance {},
	b_soc_priglashenie: class extends self.ISpriteInstance {},
	vopros: class extends self.ISpriteInstance {},
	txt_instr: class extends self.ITextInstance {},
	dec_ad: class extends self.ISpriteInstance {}
}