const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Orbit,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.Timer,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Behaviors.Turret,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Acts.LoadObjectTextures,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Text.Exps.Text,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Orbit.Acts.Pin,
		C3.Behaviors.Orbit.Acts.SetOffsetAngle,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Orbit.Acts.SetRadius,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Orbit.Acts.SetEnabled,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.LocalStorage.Cnds.IsProcessingGets,
		C3.Plugins.LocalStorage.Cnds.IsProcessingSets,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.RecreateInitialObjects,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Behaviors.Sin.Exps.Value,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.ChildCount,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.Turret.Acts.SetRateOfFire,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Exps.roundtodp,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.Text.Cnds.CompareOpacity,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Exps.float,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Text.Exps.Y,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.MoveTo.Exps.TargetX,
		C3.Behaviors.MoveTo.Exps.TargetY,
		C3.Behaviors.Tween.Exps.Progress,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Behaviors.Turret.Exps.TargetUID,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Dictionary.Exps.KeyCount,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.MoveTo.Acts.MoveToPosition
	];
};
self.C3_JsPropNameTable = [
	{summonOrder: 0},
	{MMBtnNo: 0},
	{MMBtnYes: 0},
	{Tween: 0},
	{MMSureFrame: 0},
	{MMBtnBGM: 0},
	{MMBtnPlay: 0},
	{MMBtnReset: 0},
	{MMBtnSFX: 0},
	{MMTitleGrukkle: 0},
	{MMTitleOnslaught: 0},
	{MMPivot: 0},
	{Orbit: 0},
	{MMPlanet: 0},
	{MMTextProgress: 0},
	{Flash: 0},
	{MMTextInput: 0},
	{MMTextMisc: 0},
	{ArrEnemies: 0},
	{ArrLevel: 0},
	{ArrTowers: 0},
	{ArrTutorial: 0},
	{ArrWaves: 0},
	{DictGPMusic: 0},
	{DictProfile: 0},
	{DictTech: 0},
	{Keyboard: 0},
	{Touch: 0},
	{Mouse: 0},
	{AJAX: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{PlatformInfo: 0},
	{GPBGM: 0},
	{GPExit: 0},
	{GPSFX: 0},
	{Tween2: 0},
	{GPButtonCrystal: 0},
	{GPButtonEmber: 0},
	{GPButtonFlux: 0},
	{GPUIFrameTech: 0},
	{GPButtonExitNo: 0},
	{GPButtonExitYes: 0},
	{GPUIFrameExit: 0},
	{GPButtonProceed: 0},
	{GPButtonSkip: 0},
	{GPUIFrameTutorial: 0},
	{GPTextTutorial: 0},
	{GPRangeMarker: 0},
	{GPUIFrameTowers: 0},
	{tipActive: 0},
	{tipText: 0},
	{desktopOnly: 0},
	{towerID: 0},
	{GPTowerIcon: 0},
	{GPTextTower: 0},
	{Timer: 0},
	{GPNextWave: 0},
	{GPUIFrameTop: 0},
	{GPTextCrystal: 0},
	{GPTextEmber: 0},
	{GPTextFlux: 0},
	{GPTextLives: 0},
	{GPTextTime: 0},
	{GPTextWaves: 0},
	{GPTextFunds: 0},
	{GPTextInterest: 0},
	{GPUIFrameTip: 0},
	{GPTextTip: 0},
	{GPTipShow: 0},
	{GPTextMisc: 0},
	{GPTextDesc: 0},
	{GPIcon: 0},
	{FadeFinish: 0},
	{GPTextFinish: 0},
	{GPTextEnemyGold: 0},
	{GPAcid: 0},
	{YPos: 0},
	{GPBolt: 0},
	{damage: 0},
	{tech: 0},
	{special: 0},
	{radiusAoE: 0},
	{targetUID: 0},
	{linear: 0},
	{linearStartX: 0},
	{linearStartY: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Rotate: 0},
	{GPBullet: 0},
	{GPBulletDeath: 0},
	{GPPulseMuzzle: 0},
	{GPTower: 0},
	{GPTowerParticles: 0},
	{damageBuff: 0},
	{range: 0},
	{cooldown: 0},
	{GPTowerPulse: 0},
	{linearBullet: 0},
	{realRange: 0},
	{Turret: 0},
	{GPTowerTurret: 0},
	{GPTurretMuzzle: 0},
	{hp: 0},
	{spawnedFrom: 0},
	{defaultSpeed: 0},
	{specialPower: 0},
	{gold: 0},
	{currWpt: 0},
	{MoveTo: 0},
	{Sine: 0},
	{GPEnemy: 0},
	{GPEnemyDeath: 0},
	{GPPortalBase: 0},
	{GPPortalEffect: 0},
	{spawnerID: 0},
	{GPPortalSpawner: 0},
	{GPInterestTimer: 0},
	{Fader: 0},
	{BGStars0: 0},
	{BGStars1: 0},
	{BGStars2: 0},
	{BGStarsBG: 0},
	{LVBase: 0},
	{available: 0},
	{LVBuildingSpot: 0},
	{wptID: 0},
	{mirrorEnemies: 0},
	{LVEnemyWaypoint: 0},
	{startMirrored: 0},
	{LVSpawner: 0},
	{LVBackground: 0},
	{CreditsText: 0},
	{CreditsTimer: 0},
	{CreditEnemy: 0},
	{GPDontShowBlocks: 0},
	{GPTipObjects: 0},
	{GPTowerActuators: 0},
	{SineFlash: 0},
	{GPUIFlashables: 0},
	{GPZOrderables: 0},
	{GPTechButtons: 0},
	{GPCornerButtons: 0},
	{MMButtons: 0},
	{LVLevelBlocks: 0},
	{NPLANETS: 0},
	{NLEVELS: 0},
	{currLevel: 0},
	{canGoToMenu: 0},
	{planetsStartingDist: 0},
	{planetsMinDist: 0},
	{starSpeed: 0},
	{sumOfTechs: 0},
	{planetAnim: 0},
	{finalY: 0},
	{lives: 0},
	{interest: 0},
	{ember: 0},
	{crystal: 0},
	{flux: 0},
	{timeToWave: 0},
	{wave: 0},
	{inputFocus: 0},
	{currWaveID: 0},
	{currEnemyID: 0},
	{tutorialState: 0},
	{isOnMobile: 0},
	{chosenTech: 0},
	{TIP_HL_COL: 0},
	{TIP_GOLD_COL: 0},
	{TIP_STD_COL: 0},
	{STARTING_LIVES: 0},
	{STARTING_INTEREST: 0},
	{WAVE_GOLD_INC: 0},
	{WAVE_SPEED_INC: 0},
	{focus: 0},
	{techPressed: 0},
	{techButtonPressed: 0},
	{towerAnim: 0},
	{idx: 0},
	{newAnimName: 0},
	{arrTowerID: 0},
	{sellValue: 0},
	{touchX: 0},
	{tempFireSpotX: 0},
	{tempFireSpotY: 0},
	{enemyToShow: 0},
	{text: 0},
	{levelNumber: 0},
	{waveNumber: 0},
	{totalDamage: 0},
	{teslaCount: 0},
	{enemyUID: 0},
	{earnGold: 0},
	{bonus: 0},
	{x: 0},
	{y: 0},
	{radius: 0},
	{towerInterest: 0},
	{frameAnim: 0},
	{SFXWasPlaying: 0},
	{currGPTrack: 0},
	{BGMPlaying: 0},
	{BGMVOL: 0},
	{currAudioID: 0},
	{SFXPlaying: 0},
	{SFXVOL: 0},
	{SFXSIZE: 0},
	{fadeOut: 0},
	{musicFile: 0},
	{fadeIn: 0},
	{sfxFile: 0},
	{rndPBRate: 0},
	{rndPBRateRange: 0},
	{movePattern: 0}
];

self.InstanceType = {
	MMBtnNo: class extends self.ISpriteInstance {},
	MMBtnYes: class extends self.ISpriteInstance {},
	MMSureFrame: class extends self.ISpriteInstance {},
	MMBtnBGM: class extends self.ISpriteInstance {},
	MMBtnPlay: class extends self.ISpriteInstance {},
	MMBtnReset: class extends self.ISpriteInstance {},
	MMBtnSFX: class extends self.ISpriteInstance {},
	MMTitleGrukkle: class extends self.ISpriteInstance {},
	MMTitleOnslaught: class extends self.ISpriteInstance {},
	MMPivot: class extends self.ISpriteInstance {},
	MMPlanet: class extends self.ISpriteInstance {},
	MMTextProgress: class extends self.ITextInstance {},
	MMTextInput: class extends self.ITextInstance {},
	MMTextMisc: class extends self.ITextInstance {},
	ArrEnemies: class extends self.IArrayInstance {},
	ArrLevel: class extends self.IArrayInstance {},
	ArrTowers: class extends self.IArrayInstance {},
	ArrTutorial: class extends self.IArrayInstance {},
	ArrWaves: class extends self.IArrayInstance {},
	DictGPMusic: class extends self.IDictionaryInstance {},
	DictProfile: class extends self.IDictionaryInstance {},
	DictTech: class extends self.IDictionaryInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	GPBGM: class extends self.ISpriteInstance {},
	GPExit: class extends self.ISpriteInstance {},
	GPSFX: class extends self.ISpriteInstance {},
	GPButtonCrystal: class extends self.ISpriteInstance {},
	GPButtonEmber: class extends self.ISpriteInstance {},
	GPButtonFlux: class extends self.ISpriteInstance {},
	GPUIFrameTech: class extends self.ISpriteInstance {},
	GPButtonExitNo: class extends self.ISpriteInstance {},
	GPButtonExitYes: class extends self.ISpriteInstance {},
	GPUIFrameExit: class extends self.ISpriteInstance {},
	GPButtonProceed: class extends self.ISpriteInstance {},
	GPButtonSkip: class extends self.ISpriteInstance {},
	GPUIFrameTutorial: class extends self.ISpriteInstance {},
	GPTextTutorial: class extends self.ITextInstance {},
	GPRangeMarker: class extends self.ISpriteInstance {},
	GPUIFrameTowers: class extends self.ISpriteInstance {},
	GPTowerIcon: class extends self.ISpriteInstance {},
	GPTextTower: class extends self.ITextInstance {},
	GPNextWave: class extends self.ISpriteInstance {},
	GPUIFrameTop: class extends self.ISpriteInstance {},
	GPTextCrystal: class extends self.ITextInstance {},
	GPTextEmber: class extends self.ITextInstance {},
	GPTextFlux: class extends self.ITextInstance {},
	GPTextLives: class extends self.ITextInstance {},
	GPTextTime: class extends self.ITextInstance {},
	GPTextWaves: class extends self.ITextInstance {},
	GPTextFunds: class extends self.ITextInstance {},
	GPTextInterest: class extends self.ITextInstance {},
	GPUIFrameTip: class extends self.ISpriteInstance {},
	GPTextTip: class extends self.ITextInstance {},
	GPTipShow: class extends self.ISpriteInstance {},
	GPTextMisc: class extends self.ITextInstance {},
	GPTextDesc: class extends self.ITextInstance {},
	GPIcon: class extends self.ISpriteInstance {},
	FadeFinish: class extends self.ITiledBackgroundInstance {},
	GPTextFinish: class extends self.ITextInstance {},
	GPTextEnemyGold: class extends self.ITextInstance {},
	GPAcid: class extends self.ISpriteInstance {},
	GPBolt: class extends self.ISpriteInstance {},
	GPBullet: class extends self.ISpriteInstance {},
	GPBulletDeath: class extends self.ISpriteInstance {},
	GPPulseMuzzle: class extends self.ISpriteInstance {},
	GPTower: class extends self.ISpriteInstance {},
	GPTowerParticles: class extends self.IParticlesInstance {},
	GPTowerPulse: class extends self.ISpriteInstance {},
	GPTowerTurret: class extends self.ISpriteInstance {},
	GPTurretMuzzle: class extends self.ISpriteInstance {},
	GPEnemy: class extends self.ISpriteInstance {},
	GPEnemyDeath: class extends self.IParticlesInstance {},
	GPPortalBase: class extends self.ISpriteInstance {},
	GPPortalEffect: class extends self.ISpriteInstance {},
	GPPortalSpawner: class extends self.ISpriteInstance {},
	GPInterestTimer: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	BGStars0: class extends self.ITiledBackgroundInstance {},
	BGStars1: class extends self.ITiledBackgroundInstance {},
	BGStars2: class extends self.ITiledBackgroundInstance {},
	BGStarsBG: class extends self.ITiledBackgroundInstance {},
	LVBase: class extends self.ISpriteInstance {},
	LVBuildingSpot: class extends self.ISpriteInstance {},
	LVEnemyWaypoint: class extends self.ISpriteInstance {},
	LVSpawner: class extends self.ISpriteInstance {},
	LVBackground: class extends self.ISpriteInstance {},
	CreditsText: class extends self.ITextInstance {},
	CreditsTimer: class extends self.ISpriteInstance {},
	CreditEnemy: class extends self.ISpriteInstance {},
	GPDontShowBlocks: class extends self.ISpriteInstance {},
	GPTipObjects: class extends self.ISpriteInstance {},
	GPTowerActuators: class extends self.ISpriteInstance {},
	GPUIFlashables: class extends self.ISpriteInstance {},
	GPZOrderables: class extends self.ISpriteInstance {},
	GPTechButtons: class extends self.ISpriteInstance {},
	GPCornerButtons: class extends self.ISpriteInstance {},
	MMButtons: class extends self.ISpriteInstance {},
	LVLevelBlocks: class extends self.ISpriteInstance {}
}