const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Turret,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.MoveTo,
		C3.Behaviors.destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Cnds.HasTarget,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.Turret.Acts.ClearTargets,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{zachvatchik: 0},
	{chislo: 0},
	{vibran: 0},
	{Турель: 0},
	{punkt: 0},
	{line: 0},
	{touch: 0},
	{territory: 0},
	{txt_punkts: 0},
	{ДвижениеК: 0},
	{УничтожениеВнеМакета: 0},
	{pers: 0},
	{cell: 0},
	{pers2: 0},
	{line2: 0},
	{pers3: 0},
	{pers4: 0},
	{pers5: 0},
	{scaner: 0},
	{TEST: 0},
	{synchronize: 0},
	{winner_window: 0},
	{winner_txt: 0},
	{Семья1: 0},
	{AI_UID: 0},
	{win1_lose2: 0},
	{colvo_player_zones: 0}
];

self.InstanceType = {
	punkt: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	touch: class extends self.IInstance {},
	territory: class extends self.ISpriteInstance {},
	txt_punkts: class extends self.ITextInstance {},
	pers: class extends self.ISpriteInstance {},
	cell: class extends self.ISpriteInstance {},
	pers2: class extends self.ISpriteInstance {},
	line2: class extends self.ISpriteInstance {},
	pers3: class extends self.ISpriteInstance {},
	pers4: class extends self.ISpriteInstance {},
	pers5: class extends self.ISpriteInstance {},
	scaner: class extends self.ISpriteInstance {},
	TEST: class extends self.ITextInstance {},
	synchronize: class extends self.ISpriteInstance {},
	winner_window: class extends self.ISpriteInstance {},
	winner_txt: class extends self.ITextInstance {},
	Семья1: class extends self.ISpriteInstance {}
}