const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Behaviors.wrap,
		C3.Behaviors.EightDir,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Behaviors.MoveTo,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.TextBox,
		C3.Plugins.LocalStorage,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpenScoped,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardPublishRecord,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardSetRecord,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.TextBox.Acts.SetBlur,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.CompareOpacity
	];
};
self.C3_JsPropNameTable = [
	{Угасание: 0},
	{ig: 0},
	{desktop_460002290fd947409c57252b46c64e: 0},
	{Спрайт: 0},
	{Заворачивание: 0},
	{"8Направлений": 0},
	{brevno: 0},
	{gorod: 0},
	{ТайловыйФон: 0},
	{Спрайт3: 0},
	{Якорь: 0},
	{w026n002949Bp: 0},
	{ДвижениеК: 0},
	{Pers: 0},
	{animati1on: 0},
	{animati1on2: 0},
	{Element_Game_53преобразованный: 0},
	{Аудио: 0},
	{buttons_menu: 0},
	{but_sou: 0},
	{Тач: 0},
	{Текст: 0},
	{PD: 0},
	{Синусоида: 0},
	{Спрайт4: 0},
	{type: 0},
	{button: 0},
	{redzone1: 0},
	{window_pers: 0},
	{Element_Game_53преобразованный2: 0},
	{Nm: 0},
	{b_pers: 0},
	{txt_pers: 0},
	{b_level: 0},
	{b_level2: 0},
	{txt_uroven: 0},
	{txt_level: 0},
	{txt_coins: 0},
	{coin_decore: 0},
	{Element_Game_53преобразованный3: 0},
	{redzone2: 0},
	{tapper: 0},
	{Спрайт2: 0},
	{punkt1: 0},
	{punkt2: 0},
	{Частицы: 0},
	{hp: 0},
	{winner_okno: 0},
	{winner_but: 0},
	{txt_winner: 0},
	{timer_start_game: 0},
	{txt_winner_button: 0},
	{punkt11: 0},
	{punkt22: 0},
	{pregrada: 0},
	{spawner1: 0},
	{spawner2: 0},
	{spawner3: 0},
	{txt_winner2_viigrish: 0},
	{VintageAndModernBalconyRailingsVectorIllustrationsSet: 0},
	{winner_decore: 0},
	{Спрайт5: 0},
	{txt_distance: 0},
	{perecherkivanie: 0},
	{name_vvod: 0},
	{Текст2: 0},
	{but_play: 0},
	{but_load: 0},
	{but_nastroiki: 0},
	{but_pravila: 0},
	{but_personazhi: 0},
	{but_nastroyki: 0},
	{window_nastroyki: 0},
	{ЛокальноеХранилище: 0},
	{Текст3: 0},
	{Спрайт6: 0},
	{bad_zone: 0},
	{test: 0},
	{GamePush: 0},
	{trophy: 0},
	{button_slot1: 0},
	{button_slot2: 0},
	{button_slot3: 0},
	{name1: 0},
	{name2: 0},
	{name3: 0},
	{Спрайт7: 0},
	{Спрайт8: 0},
	{PC5MGV: 0},
	{PC0T: 0},
	{PC0T2: 0},
	{PC0T3: 0},
	{PC0T4: 0},
	{vrag_sprava: 0},
	{vrag_sleva: 0},
	{Частицы2: 0},
	{punkt_vrag1: 0},
	{punkt_vrag2: 0},
	{score: 0},
	{pers: 0},
	{name: 0},
	{sound: 0},
	{window_loader: 0},
	{window_pravila: 0},
	{slot: 0},
	{HP: 0},
	{left_0_right_1: 0},
	{stolknovenie: 0},
	{play: 0},
	{winner: 0},
	{vniz: 0},
	{vverh: 0},
	{zadel: 0},
	{starter_time: 0},
	{timer: 0},
	{the_end: 0},
	{vibor_spawner: 0},
	{vibor_spawner_vrag: 0},
	{coin_viigrish: 0},
	{seconds: 0},
	{minutes: 0},
	{sunduk: 0},
	{level_jungle: 0},
	{open_jungle: 0},
	{level_city: 0},
	{open_city: 0},
	{jungle_1_city_2: 0}
];

self.InstanceType = {
	ig: class extends self.ISpriteInstance {},
	desktop_460002290fd947409c57252b46c64e: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	brevno: class extends self.ISpriteInstance {},
	gorod: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	w026n002949Bp: class extends self.ISpriteInstance {},
	Pers: class extends self.ISpriteInstance {},
	animati1on: class extends self.ISpriteInstance {},
	animati1on2: class extends self.ISpriteInstance {},
	Element_Game_53преобразованный: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	buttons_menu: class extends self.ISpriteInstance {},
	but_sou: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	Текст: class extends self.ITextInstance {},
	PD: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	redzone1: class extends self.ISpriteInstance {},
	window_pers: class extends self.ISpriteInstance {},
	Element_Game_53преобразованный2: class extends self.ISpriteInstance {},
	b_pers: class extends self.ISpriteInstance {},
	txt_pers: class extends self.ITextInstance {},
	b_level: class extends self.ISpriteInstance {},
	b_level2: class extends self.ISpriteInstance {},
	txt_uroven: class extends self.ITextInstance {},
	txt_level: class extends self.ITextInstance {},
	txt_coins: class extends self.ITextInstance {},
	coin_decore: class extends self.ISpriteInstance {},
	Element_Game_53преобразованный3: class extends self.ISpriteInstance {},
	redzone2: class extends self.ISpriteInstance {},
	tapper: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	punkt1: class extends self.ISpriteInstance {},
	punkt2: class extends self.ISpriteInstance {},
	Частицы: class extends self.IParticlesInstance {},
	hp: class extends self.ISpriteInstance {},
	winner_okno: class extends self.ISpriteInstance {},
	winner_but: class extends self.ISpriteInstance {},
	txt_winner: class extends self.ITextInstance {},
	timer_start_game: class extends self.ITextInstance {},
	txt_winner_button: class extends self.ITextInstance {},
	punkt11: class extends self.ISpriteInstance {},
	punkt22: class extends self.ISpriteInstance {},
	pregrada: class extends self.ISpriteInstance {},
	spawner1: class extends self.ISpriteInstance {},
	spawner2: class extends self.ISpriteInstance {},
	spawner3: class extends self.ISpriteInstance {},
	txt_winner2_viigrish: class extends self.ITextInstance {},
	VintageAndModernBalconyRailingsVectorIllustrationsSet: class extends self.ISpriteInstance {},
	winner_decore: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	txt_distance: class extends self.ITextInstance {},
	perecherkivanie: class extends self.ISpriteInstance {},
	name_vvod: class extends self.ITextInputInstance {},
	Текст2: class extends self.ITextInstance {},
	but_play: class extends self.ISpriteInstance {},
	but_load: class extends self.ISpriteInstance {},
	but_nastroiki: class extends self.ISpriteInstance {},
	but_pravila: class extends self.ISpriteInstance {},
	but_personazhi: class extends self.ISpriteInstance {},
	but_nastroyki: class extends self.ISpriteInstance {},
	window_nastroyki: class extends self.ISpriteInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	Текст3: class extends self.ITextInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	bad_zone: class extends self.ISpriteInstance {},
	test: class extends self.ITextInstance {},
	GamePush: class extends self.IInstance {},
	trophy: class extends self.ISpriteInstance {},
	button_slot1: class extends self.ISpriteInstance {},
	button_slot2: class extends self.ISpriteInstance {},
	button_slot3: class extends self.ISpriteInstance {},
	name1: class extends self.ITextInstance {},
	name2: class extends self.ITextInstance {},
	name3: class extends self.ITextInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	PC5MGV: class extends self.ISpriteInstance {},
	PC0T: class extends self.ISpriteInstance {},
	PC0T2: class extends self.ISpriteInstance {},
	PC0T3: class extends self.ISpriteInstance {},
	PC0T4: class extends self.ISpriteInstance {},
	vrag_sprava: class extends self.ISpriteInstance {},
	vrag_sleva: class extends self.ISpriteInstance {},
	Частицы2: class extends self.IParticlesInstance {},
	punkt_vrag1: class extends self.ISpriteInstance {},
	punkt_vrag2: class extends self.ISpriteInstance {}
}