const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.aekiro_proui,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.NinePatch,
		C3.Plugins.Browser,
		C3.Behaviors.aekiro_button,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Pin,
		C3.Plugins.Particles,
		C3.Behaviors.Timer,
		C3.Behaviors.scrollto,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Arr,
		C3.Plugins.TextBox,
		C3.Behaviors.skymenTrail,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.StopAll,
		C3.JavaScriptInEvents.Setup_Event77_Act1,
		C3.JavaScriptInEvents.Setup_Event78_Act1,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Exps.Count,
		C3.JavaScriptInEvents.Setup_Event87_Act1,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.JavaScriptInEvents.Setup_Event94_Act12,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.JavaScriptInEvents.Setup_Event98_Act7,
		C3.JavaScriptInEvents.Setup_Event103_Act1,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.JavaScriptInEvents.Setup_Event106_Act1,
		C3.JavaScriptInEvents.Setup_Event108_Act13,
		C3.JavaScriptInEvents.Setup_Event111_Act1,
		C3.JavaScriptInEvents.Setup_Event112_Act6,
		C3.JavaScriptInEvents.Setup_Event112_Act8,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.JavaScriptInEvents.Setup_Event115_Act1,
		C3.JavaScriptInEvents.Setup_Event115_Act3,
		C3.JavaScriptInEvents.Setup_Event117_Act1,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.JavaScriptInEvents.Setup_Event118_Act1,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Spritefont2.Cnds.IsOnLayer,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.JavaScriptInEvents.Setup_Event145_Act3,
		C3.JavaScriptInEvents.Setup_Event146_Act3,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Exps.Width,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Particles.Acts.Destroy,
		C3.JavaScriptInEvents.Setup_Event149_Act8,
		C3.JavaScriptInEvents.Setup_Event149_Act9,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Particles.Acts.SetInitSize,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.JavaScriptInEvents.Setup_Event151_Act2,
		C3.JavaScriptInEvents.Setup_Event152_Act2,
		C3.JavaScriptInEvents.Setup_Event156_Act1,
		C3.JavaScriptInEvents.Setup_Event158_Act1,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.SpeedForID,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Exps.AngleForID,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.System.Exps.layoutwidth,
		C3.JavaScriptInEvents.Start_Event4_Act1,
		C3.JavaScriptInEvents.Start_Event4_Act16,
		C3.JavaScriptInEvents.Start_Event6_Act2,
		C3.Behaviors.skymenTrail.Acts.SetWidthStart,
		C3.Behaviors.skymenTrail.Acts.Attach,
		C3.Behaviors.skymenTrail.Acts.Reset,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.JavaScriptInEvents.Start_Event17_Act2,
		C3.JavaScriptInEvents.Start_Event17_Act5,
		C3.JavaScriptInEvents.Start_Event19_Act2,
		C3.JavaScriptInEvents.Start_Event19_Act5,
		C3.Plugins.Spritefont2.Cnds.PickParent,
		C3.JavaScriptInEvents.Start_Event24_Act1,
		C3.JavaScriptInEvents.Start_Event24_Act9,
		C3.JavaScriptInEvents.Start_Event29_Act2,
		C3.JavaScriptInEvents.Start_Event31_Act1,
		C3.Plugins.Text.Cnds.CompareText,
		C3.JavaScriptInEvents.Start_Event32_Act1,
		C3.JavaScriptInEvents.Start_Event32_Act3,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.IsEffectEnabled,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.JavaScriptInEvents.Start_Event53_Act2,
		C3.JavaScriptInEvents.Start_Event53_Act4,
		C3.JavaScriptInEvents.Start_Event54_Act2,
		C3.JavaScriptInEvents.Start_Event54_Act4,
		C3.JavaScriptInEvents.Start_Event55_Act2,
		C3.JavaScriptInEvents.Start_Event55_Act4,
		C3.JavaScriptInEvents.Start_Event57_Act1,
		C3.JavaScriptInEvents.Start_Event57_Act10,
		C3.JavaScriptInEvents.Start_Event59_Act1,
		C3.JavaScriptInEvents.Start_Event62_Act7,
		C3.JavaScriptInEvents.Start_Event67_Act2,
		C3.JavaScriptInEvents.Start_Event68_Act1,
		C3.JavaScriptInEvents.Start_Event68_Act3,
		C3.JavaScriptInEvents.Start_Event69_Act1,
		C3.JavaScriptInEvents.Start_Event71_Act1,
		C3.Plugins.System.Cnds.Every,
		C3.JavaScriptInEvents.Start_Event73_Act1,
		C3.JavaScriptInEvents.Start_Event78_Act1,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.Start_Event96_Act2,
		C3.JavaScriptInEvents.Start_Event96_Act5,
		C3.JavaScriptInEvents.Start_Event97_Act3,
		C3.JavaScriptInEvents.Start_Event99_Act1,
		C3.JavaScriptInEvents.Start_Event103_Act3,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.JavaScriptInEvents.Start_Event107_Act1,
		C3.JavaScriptInEvents.Start_Event110_Act4,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.JavaScriptInEvents.Collection_Event5_Act1,
		C3.JavaScriptInEvents.Collection_Event7_Act2,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.JavaScriptInEvents.Collection_Event8_Act2,
		C3.Plugins.Text.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.JavaScriptInEvents.Collection_Event16_Act2,
		C3.JavaScriptInEvents.Collection_Event18_Act1,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.JavaScriptInEvents.Luckyspin_Event3_Act1,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.Angle,
		C3.JavaScriptInEvents.Areas_Event1_Act2,
		C3.JavaScriptInEvents.Puzzle_Event1_Act1,
		C3.JavaScriptInEvents.Puzzle_Event1_Act2,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.DrawingCanvas.Acts.MoveToTop,
		C3.Plugins.DrawingCanvas.Exps.Angle,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.DrawingCanvas.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.SetBoolInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.SetInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.NinePatch.Cnds.PickDistance,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.DrawingCanvas.Acts.SetPos,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.DrawingCanvas.Exps.LayerName,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.DrawingCanvas.Exps.Width,
		C3.Plugins.DrawingCanvas.Exps.Height,
		C3.Plugins.DrawingCanvas.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.DrawingCanvas.Exps.Count,
		C3.JavaScriptInEvents.Puzzle_Event19_Act2,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.DrawingCanvas.Acts.PasteObject
	];
};
self.C3_JsPropNameTable = [
	{ww: 0},
	{hh: 0},
	{gc: 0},
	{Tween: 0},
	{goldicon: 0},
	{wheelText: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Audio: 0},
	{ProUI: 0},
	{AJAX: 0},
	{LocalStorage: 0},
	{dark: 0},
	{"NAME📌": 0},
	{"DIRECTION_DOWN📌": 0},
	{listTotHeight: 0},
	{listTotHehight2: 0},
	{"9patchchours": 0},
	{"PARENT_NAME📌": 0},
	{touchyinit: 0},
	{touchspeed: 0},
	{slidepos: 0},
	{slideinitialvelocityu: 0},
	{scrolling: 0},
	{piny: 0},
	{pinylimit: 0},
	{yyy: 0},
	{yyyy: 0},
	{choruspin: 0},
	{Browser: 0},
	{dark2: 0},
	{xx: 0},
	{yy: 0},
	{w: 0},
	{Button: 0},
	{settingsclosebutton: 0},
	{Text3: 0},
	{buttonsettings: 0},
	{closebutton: 0},
	{buttonsettings2: 0},
	{buttonsettings3: 0},
	{exitbutton: 0},
	{translationbutton: 0},
	{Fade: 0},
	{message: 0},
	{type: 0},
	{Sine: 0},
	{chestRewardBG: 0},
	{chestRewardButton: 0},
	{starRewardButton: 0},
	{chestWheelBG: 0},
	{Variable1: 0},
	{name: 0},
	{collectioncollect: 0},
	{wheelicon: 0},
	{WheelParts: 0},
	{WheelReward: 0},
	{Rotate: 0},
	{WheelRotate: 0},
	{spinTicket: 0},
	{RewardImages: 0},
	{skill: 0},
	{Pin: 0},
	{rewardtext: 0},
	{starRewardsIcons: 0},
	{particleConfetti: 0},
	{particleConfettiP: 0},
	{staar: 0},
	{staar2: 0},
	{staar3: 0},
	{Timer: 0},
	{Castle: 0},
	{goldbg: 0},
	{levelbutton: 0},
	{effectbt: 0},
	{levelupef2: 0},
	{backbutton: 0},
	{tutFinger: 0},
	{tapto: 0},
	{Sprite16: 0},
	{Sprite5: 0},
	{ScrollTo: 0},
	{CameraShake: 0},
	{R: 0},
	{RESPONSIVE: 0},
	{giftTXT: 0},
	{giftTXT2: 0},
	{areatext: 0},
	{areatext3: 0},
	{textholdd: 0},
	{areatext5: 0},
	{areatitle2: 0},
	{puzzletitle: 0},
	{puzzletitle2: 0},
	{tutorialtext: 0},
	{reward: 0},
	{starrewardicon: 0},
	{srewards: 0},
	{starrewardtxt: 0},
	{collectionname: 0},
	{collectionbg: 0},
	{playbutton: 0},
	{playbuttontext: 0},
	{collectionbgclosed: 0},
	{leveltxt2: 0},
	{booster: 0},
	{boosterbg: 0},
	{desc: 0},
	{price: 0},
	{frame: 0},
	{addicon: 0},
	{redcircle: 0},
	{redcircletxt: 0},
	{playbuttontext2: 0},
	{leveltxt6: 0},
	{redcircle2: 0},
	{randomquestp1: 0},
	{randomquestp2: 0},
	{collectionchest: 0},
	{randomtaskimg: 0},
	{randomquestp5: 0},
	{collectiongrandprogress: 0},
	{randomquestp7: 0},
	{areafull: 0},
	{collectionrewardimg: 0},
	{collectiontext: 0},
	{collectionprogressbg: 0},
	{collectionprogressbar: 0},
	{collectionprogressbg2: 0},
	{collectionprogressbar2: 0},
	{collectioncardname: 0},
	{areasbar2: 0},
	{areasbartext: 0},
	{LetterHolder: 0},
	{LetterHolder2: 0},
	{LetterHolderL: 0},
	{LetterHolderR: 0},
	{LetterHolder3: 0},
	{n: 0},
	{parts: 0},
	{free: 0},
	{collect: 0},
	{Tile: 0},
	{CollectTile: 0},
	{PickEffect: 0},
	{Index: 0},
	{Snapped: 0},
	{GridBlockUID: 0},
	{DragDrop: 0},
	{Piece: 0},
	{SourceImage: 0},
	{piecestext: 0},
	{puzzletime: 0},
	{areaopen: 0},
	{areaopen2: 0},
	{part: 0},
	{areaopen3: 0},
	{areaopen5: 0},
	{areaopen6: 0},
	{chatPopup: 0},
	{text: 0},
	{uuid: 0},
	{hiddenWord: 0},
	{hiddenLetter: 0},
	{opened: 0},
	{Letters: 0},
	{level: 0},
	{TextInput: 0},
	{Sprite: 0},
	{Particles: 0},
	{h: 0},
	{starparticle: 0},
	{Sprite2: 0},
	{swipetop: 0},
	{swipeleft: 0},
	{swiperight: 0},
	{swipebottom: 0},
	{banner: 0},
	{TrailHeadStar: 0},
	{TrailRenderer: 0},
	{Trail3: 0},
	{texholdp: 0},
	{uitopbottom: 0},
	{uimenu: 0},
	{swipetop2: 0},
	{Sprite6: 0},
	{collectiongreen: 0},
	{collectionpagebg: 0},
	{endbutton: 0},
	{collectionimg: 0},
	{collectionrewimg: 0},
	{collected: 0},
	{collectioncards: 0},
	{CNGRLT: 0},
	{rewardanim: 0},
	{party: 0},
	{Particles2: 0},
	{collectionrewimg2: 0},
	{collectionlock: 0},
	{areas: 0},
	{areasbar: 0},
	{GridBlock: 0},
	{Flash: 0},
	{Frame: 0},
	{Sprite3: 0},
	{piecesbg: 0},
	{Sprite4: 0},
	{flags: 0},
	{Sprite7: 0},
	{spriteText: 0},
	{trailforrewards: 0},
	{trailheadforrewards: 0},
	{spriteTextmessage: 0},
	{end: 0},
	{Sprite8: 0},
	{endlight: 0},
	{fail: 0},
	{endb: 0},
	{Sprite11: 0},
	{newareaopen: 0},
	{cbag: 0},
	{new: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite12: 0},
	{tutorial: 0},
	{LR: 0},
	{"9p_Back": 0},
	{MoveTo: 0},
	{sp_Pin: 0},
	{delete: 0},
	{layer: 0},
	{opacity: 0},
	{ECactive: 0},
	{x: 0},
	{y: 0},
	{height: 0},
	{width: 0},
	{scale: 0},
	{audioName: 0},
	{Loop: 0},
	{v: 0},
	{action: 0},
	{aangle: 0},
	{sine: 0},
	{fxMuted: 0},
	{musicMuted: 0},
	{gold: 0},
	{diamond: 0},
	{chestReward1: 0},
	{chestReward2: 0},
	{chestReward3: 0},
	{chestRewardq1: 0},
	{chestRewardq2: 0},
	{chestRewardq3: 0},
	{rotateWheelAngle: 0},
	{rewardscreen: 0},
	{starReward: 0},
	{animation: 0},
	{valuee: 0},
	{Parameter0: 0},
	{openedstarreward: 0},
	{addorsub: 0},
	{value: 0},
	{lastmy: 0},
	{card1frame: 0},
	{card1cname: 0},
	{card1cardname: 0},
	{card1v: 0},
	{card2frame: 0},
	{card2v: 0},
	{carduid: 0},
	{carduid2: 0},
	{card2cname: 0},
	{card2cardname: 0},
	{dcc: 0},
	{ccardw: 0},
	{d: 0},
	{Grid_size: 0},
	{ScrollYLimit: 0},
	{CurrentNAME: 0},
	{starRewards: 0},
	{tutorialstep: 0},
	{activearea: 0},
	{param1: 0},
	{param2: 0},
	{x2: 0},
	{y2: 0},
	{currentLevel: 0},
	{word: 0},
	{uidd: 0},
	{anglee: 0},
	{uid: 0},
	{wheelticket: 0},
	{cstarty: 0},
	{ccname: 0},
	{choosenRotate: 0},
	{PiecesPerLine: 0},
	{PiecesWidth: 0},
	{PiecesHeight: 0},
	{SpawnMargin: 0},
	{SnapDistance: 0},
	{puzzleactive: 0},
	{Count: 0},
	{CurrentIndex: 0}
];

self.InstanceType = {
	goldicon: class extends self.ISpriteInstance {},
	wheelText: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	ProUI: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	dark: class extends self.ISpriteInstance {},
	_9patchchours: class extends self.IWorldInstance {},
	choruspin: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	dark2: class extends self.ISpriteInstance {},
	settingsclosebutton: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	buttonsettings: class extends self.ISpriteInstance {},
	closebutton: class extends self.ISpriteInstance {},
	buttonsettings2: class extends self.ISpriteInstance {},
	buttonsettings3: class extends self.ISpriteInstance {},
	exitbutton: class extends self.ISpriteInstance {},
	translationbutton: class extends self.ISpriteInstance {},
	message: class extends self.ITextInstance {},
	chestRewardBG: class extends self.ISpriteInstance {},
	chestRewardButton: class extends self.ISpriteInstance {},
	starRewardButton: class extends self.ISpriteInstance {},
	chestWheelBG: class extends self.ISpriteInstance {},
	collectioncollect: class extends self.ISpriteInstance {},
	wheelicon: class extends self.ISpriteInstance {},
	WheelParts: class extends self.ISpriteInstance {},
	WheelReward: class extends self.ISpriteInstance {},
	WheelRotate: class extends self.ISpriteInstance {},
	spinTicket: class extends self.ITextInstance {},
	RewardImages: class extends self.ISpriteInstance {},
	rewardtext: class extends self.ITextInstance {},
	starRewardsIcons: class extends self.ISpriteInstance {},
	particleConfetti: class extends self.ISpriteInstance {},
	particleConfettiP: class extends self.IParticlesInstance {},
	staar: class extends self.IParticlesInstance {},
	staar2: class extends self.IParticlesInstance {},
	staar3: class extends self.IParticlesInstance {},
	Castle: class extends self.ISpriteInstance {},
	goldbg: class extends self.ISpriteInstance {},
	levelbutton: class extends self.ISpriteInstance {},
	effectbt: class extends self.ISpriteInstance {},
	levelupef2: class extends self.ISpriteInstance {},
	backbutton: class extends self.ISpriteInstance {},
	tutFinger: class extends self.ISpriteInstance {},
	tapto: class extends self.ITextInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	CameraShake: class extends self.ISpriteInstance {},
	RESPONSIVE: class extends self.ISpriteInstance {},
	giftTXT: class extends self.ITextInstance {},
	giftTXT2: class extends self.ITextInstance {},
	areatext: class extends self.ITextInstance {},
	areatext3: class extends self.ITextInstance {},
	textholdd: class extends self.ITextInstance {},
	areatext5: class extends self.ITextInstance {},
	areatitle2: class extends self.ITextInstance {},
	puzzletitle: class extends self.ITextInstance {},
	puzzletitle2: class extends self.ITextInstance {},
	tutorialtext: class extends self.ITextInstance {},
	starrewardicon: class extends self.ISpriteInstance {},
	srewards: class extends self.ISpriteInstance {},
	starrewardtxt: class extends self.ITextInstance {},
	collectionname: class extends self.ITextInstance {},
	collectionbg: class extends self.ISpriteInstance {},
	playbutton: class extends self.ISpriteInstance {},
	playbuttontext: class extends self.ITextInstance {},
	collectionbgclosed: class extends self.ISpriteInstance {},
	leveltxt2: class extends self.ITextInstance {},
	boosterbg: class extends self.ISpriteInstance {},
	addicon: class extends self.ISpriteInstance {},
	redcircle: class extends self.ISpriteInstance {},
	redcircletxt: class extends self.ITextInstance {},
	playbuttontext2: class extends self.ITextInstance {},
	leveltxt6: class extends self.ITextInstance {},
	redcircle2: class extends self.ISpriteInstance {},
	randomquestp1: class extends self.ISpriteInstance {},
	randomquestp2: class extends self.ISpriteInstance {},
	collectionchest: class extends self.ISpriteInstance {},
	randomtaskimg: class extends self.ISpriteInstance {},
	randomquestp5: class extends self.ISpriteInstance {},
	collectiongrandprogress: class extends self.ISpriteInstance {},
	randomquestp7: class extends self.ISpriteInstance {},
	areafull: class extends self.ISpriteInstance {},
	collectionrewardimg: class extends self.ISpriteInstance {},
	collectiontext: class extends self.ITextInstance {},
	collectionprogressbg: class extends self.ISpriteInstance {},
	collectionprogressbar: class extends self.ISpriteInstance {},
	collectionprogressbg2: class extends self.ISpriteInstance {},
	collectionprogressbar2: class extends self.ISpriteInstance {},
	collectioncardname: class extends self.ITextInstance {},
	areasbar2: class extends self.ISpriteInstance {},
	areasbartext: class extends self.ITextInstance {},
	LetterHolder: class extends self.ISpriteInstance {},
	LetterHolder2: class extends self.ISpriteInstance {},
	LetterHolderL: class extends self.ISpriteInstance {},
	LetterHolderR: class extends self.ISpriteInstance {},
	LetterHolder3: class extends self.ISpriteInstance {},
	parts: class extends self.ISpriteInstance {},
	Tile: class extends self.ISpriteInstance {},
	CollectTile: class extends self.ISpriteInstance {},
	PickEffect: class extends self.IWorldInstance {},
	Piece: class extends self.IDrawingCanvasInstance {},
	SourceImage: class extends self.ISpriteInstance {},
	piecestext: class extends self.ITextInstance {},
	puzzletime: class extends self.ITextInstance {},
	areaopen: class extends self.ISpriteInstance {},
	areaopen2: class extends self.ISpriteInstance {},
	areaopen3: class extends self.ISpriteInstance {},
	areaopen5: class extends self.ITextInstance {},
	areaopen6: class extends self.ISpriteInstance {},
	chatPopup: class extends self.ISpriteInstance {},
	text: class extends self.ITextInstance {},
	Letters: class extends self.ISpriteInstance {},
	level: class extends self.IArrayInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	starparticle: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	swipetop: class extends self.ISpriteInstance {},
	swipeleft: class extends self.ISpriteInstance {},
	swiperight: class extends self.ISpriteInstance {},
	swipebottom: class extends self.ISpriteInstance {},
	banner: class extends self.ISpriteInstance {},
	TrailHeadStar: class extends self.ISpriteInstance {},
	Trail3: class extends self.ISpriteInstance {},
	texholdp: class extends self.IWorldInstance {},
	uitopbottom: class extends self.ISpriteInstance {},
	uimenu: class extends self.ISpriteInstance {},
	swipetop2: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	collectiongreen: class extends self.ISpriteInstance {},
	collectionpagebg: class extends self.ISpriteInstance {},
	endbutton: class extends self.ISpriteInstance {},
	collectionimg: class extends self.ISpriteInstance {},
	collectionrewimg: class extends self.ISpriteInstance {},
	collectioncards: class extends self.ISpriteInstance {},
	CNGRLT: class extends self.ISpriteInstance {},
	rewardanim: class extends self.ISpriteInstance {},
	party: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	collectionrewimg2: class extends self.ISpriteInstance {},
	collectionlock: class extends self.ISpriteInstance {},
	areas: class extends self.ISpriteInstance {},
	areasbar: class extends self.ISpriteInstance {},
	GridBlock: class extends self.IWorldInstance {},
	Flash: class extends self.ITiledBackgroundInstance {},
	Frame: class extends self.IWorldInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	piecesbg: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	flags: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	spriteText: class extends self.ISpriteFontInstance {},
	trailforrewards: class extends self.ISpriteInstance {},
	trailheadforrewards: class extends self.ISpriteInstance {},
	spriteTextmessage: class extends self.ISpriteFontInstance {},
	end: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	endlight: class extends self.ISpriteInstance {},
	fail: class extends self.ISpriteInstance {},
	endb: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	newareaopen: class extends self.ISpriteInstance {},
	cbag: class extends self.ISpriteInstance {},
	new: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	LR: class extends self.ISpriteInstance {},
	_9p_Back: class extends self.IWorldInstance {},
	sp_Pin: class extends self.ISpriteInstance {}
}