const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width
	];
};
self.C3_JsPropNameTable = [
	{кукла: 0},
	{kukla: 0},
	{gorlovina: 0},
	{podyubka: 0},
	{manchet: 0},
	{yubka: 0},
	{txt_tkan: 0},
	{check_podubnik: 0},
	{Nm: 0},
	{but_tkan: 0},
	{SL1: 0},
	{SL2: 0},
	{SL3: 0},
	{b_home: 0},
	{Тач: 0},
	{vibor_gorlovina: 0},
	{vibor_machet: 0},
	{vibor_yubka: 0},
	{vibor_podyubnik: 0},
	{vibor_cat1: 0},
	{vibor_cat2: 0},
	{vibor_cat3: 0},
	{vibor_cat4: 0},
	{strelka_dalee: 0},
	{strelka_predidush: 0},
	{txt1: 0},
	{txt_tkan2: 0},
	{atlas1_35: 0},
	{barhat2_25: 0},
	{gipur3_28: 0},
	{glyanc_bifleks4_13: 0},
	{matoviy_bifleks5_22: 0},
	{organza6_7: 0},
	{perl_shifon7_5: 0},
	{shifron_zhorzhet8_36: 0},
	{cvet1: 0},
	{cvet2: 0},
	{cvet3: 0},
	{cvet4: 0},
	{Спрайт: 0},
	{txt_cat1: 0},
	{txt_cat2: 0},
	{txt_cat3: 0},
	{txt_cat4: 0},
	{txt_nazvanie_ccveta: 0},
	{txt_obshii: 0},
	{Type: 0},
	{txt_vibor: 0},
	{txt_cat1_obtachka: 0},
	{check_obtachka: 0},
	{check_manzheti: 0},
	{txt_obshii2: 0},
	{txt_cat2_manzhet: 0},
	{kukla_vibrana: 0},
	{manzhet: 0},
	{podyubnik: 0},
	{category: 0},
	{tkan_category: 0},
	{cvet: 0},
	{chek_podubnik: 0},
	{chek_obtachka: 0},
	{chek_manzhet: 0},
	{parametrs2: 0},
	{parametrs3: 0}
];

self.InstanceType = {
	кукла: class extends self.ISpriteInstance {},
	kukla: class extends self.ISpriteInstance {},
	gorlovina: class extends self.ISpriteInstance {},
	podyubka: class extends self.ISpriteInstance {},
	manchet: class extends self.ISpriteInstance {},
	yubka: class extends self.ISpriteInstance {},
	txt_tkan: class extends self.ITextInstance {},
	check_podubnik: class extends self.ISpriteInstance {},
	but_tkan: class extends self.ISpriteInstance {},
	SL1: class extends self.ISpriteInstance {},
	SL2: class extends self.ISpriteInstance {},
	SL3: class extends self.ISpriteInstance {},
	b_home: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	vibor_gorlovina: class extends self.ISpriteInstance {},
	vibor_machet: class extends self.ISpriteInstance {},
	vibor_yubka: class extends self.ISpriteInstance {},
	vibor_podyubnik: class extends self.ISpriteInstance {},
	vibor_cat1: class extends self.ISpriteInstance {},
	vibor_cat2: class extends self.ISpriteInstance {},
	vibor_cat3: class extends self.ISpriteInstance {},
	vibor_cat4: class extends self.ISpriteInstance {},
	strelka_dalee: class extends self.ISpriteInstance {},
	strelka_predidush: class extends self.ISpriteInstance {},
	txt1: class extends self.ITextInstance {},
	txt_tkan2: class extends self.ITextInstance {},
	atlas1_35: class extends self.ISpriteInstance {},
	barhat2_25: class extends self.ISpriteInstance {},
	gipur3_28: class extends self.ISpriteInstance {},
	glyanc_bifleks4_13: class extends self.ISpriteInstance {},
	matoviy_bifleks5_22: class extends self.ISpriteInstance {},
	organza6_7: class extends self.ISpriteInstance {},
	perl_shifon7_5: class extends self.ISpriteInstance {},
	shifron_zhorzhet8_36: class extends self.ISpriteInstance {},
	cvet1: class extends self.ISpriteInstance {},
	cvet2: class extends self.ISpriteInstance {},
	cvet3: class extends self.ISpriteInstance {},
	cvet4: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	txt_cat1: class extends self.ITextInstance {},
	txt_cat2: class extends self.ITextInstance {},
	txt_cat3: class extends self.ITextInstance {},
	txt_cat4: class extends self.ITextInstance {},
	txt_nazvanie_ccveta: class extends self.ITextInstance {},
	txt_obshii: class extends self.ITextInstance {},
	txt_vibor: class extends self.ITextInstance {},
	txt_cat1_obtachka: class extends self.ITextInstance {},
	check_obtachka: class extends self.ISpriteInstance {},
	check_manzheti: class extends self.ISpriteInstance {},
	txt_obshii2: class extends self.ITextInstance {},
	txt_cat2_manzhet: class extends self.ITextInstance {}
}