const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetAnim
	];
};
self.C3_JsPropNameTable = [
	{кукла: 0},
	{kukla: 0},
	{gorlovina: 0},
	{podyubka: 0},
	{manchet: 0},
	{yubka: 0},
	{txt_tkan: 0},
	{Checkmark_cross_on_gray_background_illustration: 0},
	{Nm: 0},
	{but_tkan: 0},
	{SL1: 0},
	{SL2: 0},
	{SL3: 0},
	{b_home: 0},
	{Тач: 0},
	{vibor_gorlovina: 0},
	{vibor_machet: 0},
	{vibor_yubka: 0},
	{vibor_podyubnik: 0},
	{vibor_cat1: 0},
	{vibor_cat2: 0},
	{vibor_cat3: 0},
	{vibor_cat4: 0},
	{strelka_dalee: 0},
	{strelka_predidush: 0},
	{txt1: 0},
	{txt_tkan2: 0},
	{atlas: 0},
	{barhat: 0},
	{gipur: 0},
	{glyanc_bifleks: 0},
	{matoviy_bifleks: 0},
	{organza: 0},
	{perl_shifon: 0},
	{shifron_zhorzhet: 0},
	{cvet1: 0},
	{cvet2: 0},
	{cvet3: 0},
	{cvet4: 0},
	{Спрайт: 0},
	{kukla_vibrana: 0},
	{manzhet: 0},
	{podyubnik: 0},
	{category: 0},
	{tkan_category: 0},
	{cvet: 0}
];

self.InstanceType = {
	кукла: class extends self.ISpriteInstance {},
	kukla: class extends self.ISpriteInstance {},
	gorlovina: class extends self.ISpriteInstance {},
	podyubka: class extends self.ISpriteInstance {},
	manchet: class extends self.ISpriteInstance {},
	yubka: class extends self.ISpriteInstance {},
	txt_tkan: class extends self.ITextInstance {},
	Checkmark_cross_on_gray_background_illustration: class extends self.ISpriteInstance {},
	but_tkan: class extends self.ISpriteInstance {},
	SL1: class extends self.ISpriteInstance {},
	SL2: class extends self.ISpriteInstance {},
	SL3: class extends self.ISpriteInstance {},
	b_home: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	vibor_gorlovina: class extends self.ISpriteInstance {},
	vibor_machet: class extends self.ISpriteInstance {},
	vibor_yubka: class extends self.ISpriteInstance {},
	vibor_podyubnik: class extends self.ISpriteInstance {},
	vibor_cat1: class extends self.ISpriteInstance {},
	vibor_cat2: class extends self.ISpriteInstance {},
	vibor_cat3: class extends self.ISpriteInstance {},
	vibor_cat4: class extends self.ISpriteInstance {},
	strelka_dalee: class extends self.ISpriteInstance {},
	strelka_predidush: class extends self.ISpriteInstance {},
	txt1: class extends self.ITextInstance {},
	txt_tkan2: class extends self.ITextInstance {},
	atlas: class extends self.ISpriteInstance {},
	barhat: class extends self.ISpriteInstance {},
	gipur: class extends self.ISpriteInstance {},
	glyanc_bifleks: class extends self.ISpriteInstance {},
	matoviy_bifleks: class extends self.ISpriteInstance {},
	organza: class extends self.ISpriteInstance {},
	perl_shifon: class extends self.ISpriteInstance {},
	shifron_zhorzhet: class extends self.ISpriteInstance {},
	cvet1: class extends self.ISpriteInstance {},
	cvet2: class extends self.ISpriteInstance {},
	cvet3: class extends self.ISpriteInstance {},
	cvet4: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {}
}