const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Timer,
		C3.Behaviors.Tween,
		C3.Plugins.Keyboard,
		C3.Plugins.gamepad,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Particles.Exps.Timeout,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Timer: 0},
	{Player: 0},
	{Background: 0},
	{Alive: 0},
	{HideTutorial: 0},
	{Tween: 0},
	{Log: 0},
	{Keyboard: 0},
	{Gamepad: 0},
	{Fade: 0},
	{Score: 0},
	{TimeBar: 0},
	{Sine: 0},
	{TargetMarker: 0},
	{Instructions: 0},
	{TimeBarBackground: 0},
	{Shockwave: 0},
	{Dust: 0},
	{Trail: 0},
	{AllowPlayerInput: 0},
	{LastX: 0},
	{LastY: 0},
	{DeadlySide: 0},
	{PickedCount: 0},
	{RandomTime: 0},
	{Side: 0},
	{DepleteBar: 0},
	{SkipDeplete: 0},
	{Bar: 0},
	{PositionX: 0},
	{PositionY: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Log: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Fade: class extends self.ITiledBackgroundInstance {},
	Score: class extends self.ITextInstance {},
	TimeBar: class extends self.ITiledBackgroundInstance {},
	TargetMarker: class extends self.ISpriteInstance {},
	Instructions: class extends self.ITextInstance {},
	TimeBarBackground: class extends self.ISpriteInstance {},
	Shockwave: class extends self.ISpriteInstance {},
	Dust: class extends self.IParticlesInstance {},
	Trail: class extends self.IParticlesInstance {}
}