const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Spritefont2,
		C3.Plugins.NinePatch,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Keyboard.Cnds.OnKey
	];
};
self.C3_JsPropNameTable = [
	{Ground: 0},
	{EnemySpawner: 0},
	{HeathPoints: 0},
	{PlayerBase: 0},
	{Direction: 0},
	{Index: 0},
	{Path: 0},
	{EnemyType: 0},
	{MovementSpeed: 0},
	{TargetIndex: 0},
	{MonetaryValue: 0},
	{ZOrder: 0},
	{Tween: 0},
	{Enemy: 0},
	{Charged: 0},
	{TowerType: 0},
	{CooldownTimer: 0},
	{SightRange: 0},
	{ProjectileDamage: 0},
	{SellingPrice: 0},
	{PiercingRounds: 0},
	{Timer: 0},
	{Tower: 0},
	{Damage: 0},
	{Piercing: 0},
	{MaxDistance: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Projectile: 0},
	{ID: 0},
	{Text: 0},
	{TowerPrice: 0},
	{TowerThumbnail: 0},
	{Cursor: 0},
	{IsOccupied: 0},
	{BuildingSpot: 0},
	{Touch: 0},
	{Hearts: 0},
	{GameManager: 0},
	{HeartsBackground: 0},
	{Explosion: 0},
	{Keyboard: 0},
	{Shadow: 0},
	{Текст: 0},
	{SpawnTime: 0},
	{DificultyMultiplier: 0},
	{Money: 0},
	{NextTowerType: 0},
	{DefeatedEnemies: 0},
	{RoundNumber: 0},
	{MultipleOf: 0},
	{AngleToConvert: 0}
];

self.InstanceType = {
	Ground: class extends self.ISpriteInstance {},
	EnemySpawner: class extends self.ISpriteInstance {},
	PlayerBase: class extends self.ISpriteInstance {},
	Path: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Tower: class extends self.ISpriteInstance {},
	Projectile: class extends self.ISpriteInstance {},
	Text: class extends self.ISpriteFontInstance {},
	TowerThumbnail: class extends self.ISpriteInstance {},
	Cursor: class extends self.IWorldInstance {},
	BuildingSpot: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Hearts: class extends self.ITiledBackgroundInstance {},
	GameManager: class extends self.ISpriteInstance {},
	HeartsBackground: class extends self.ITiledBackgroundInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Shadow: class extends self.ITiledBackgroundInstance {},
	Текст: class extends self.ITextInstance {}
}