const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Behaviors.Fade,
		C3.Behaviors.Flash,
		C3.Behaviors.Anchor,
		C3.Behaviors.Bullet,
		C3.Plugins.NinePatch,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.LocalStorage,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Particles.Acts.SetGrowRate,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Browser.Exps.ExecJS,
		C3.ScriptsInEvents.Common_Event14_Act1,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedPlaying,
		C3.Plugins.Eponesh_GameScore.Acts.PaymentsPurchase,
		C3.Plugins.Eponesh_GameScore.Acts.PaymentsConsume,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPaymentsConsumeSuccessful
	];
};
self.C3_JsPropNameTable = [
	{initialX: 0},
	{TiledBackground: 0},
	{Tween: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{Sprite: 0},
	{Solid: 0},
	{solid: 0},
	{walk: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{hero: 0},
	{isHero: 0},
	{Pin: 0},
	{FadeOut: 0},
	{FadeIn: 0},
	{Flash: 0},
	{enemy: 0},
	{Anchor: 0},
	{bg_live: 0},
	{heart: 0},
	{Bullet: 0},
	{enemy_spawn: 0},
	{"9patch": 0},
	{bg_question: 0},
	{txt_question: 0},
	{answer: 0},
	{bg_answer: 0},
	{txt_answers: 0},
	{ArrayQuestions: 0},
	{AJAX: 0},
	{Browser: 0},
	{Touch: 0},
	{Fade: 0},
	{smoke: 0},
	{Audio: 0},
	{full_screen: 0},
	{Mouse: 0},
	{bg_questions: 0},
	{txt_questions_hud: 0},
	{bg_score: 0},
	{txt_score: 0},
	{btn_sound: 0},
	{LocalStorage: 0},
	{bg_clock: 0},
	{txt_clock: 0},
	{rain: 0},
	{splash: 0},
	{gold: 0},
	{gold_icon_area: 0},
	{GoldParticles: 0},
	{end_game: 0},
	{action: 0},
	{txt_end_game: 0},
	{bg_info: 0},
	{Gold2: 0},
	{Gold3: 0},
	{CoinPack_box: 0},
	{TiledBackground4: 0},
	{FireSparkParticles: 0},
	{Rotate: 0},
	{Sine: 0},
	{rotate_effect: 0},
	{speed_game: 0},
	{btn_retry: 0},
	{btn_ranking: 0},
	{btn_default1: 0},
	{txt_button: 0},
	{txt_feedback: 0},
	{background_feedback: 0},
	{enemyStopTrigger: 0},
	{logo: 0},
	{Якорь: 0},
	{btn_home: 0},
	{freelance: 0},
	{shadow: 0},
	{robot_explosion: 0},
	{explosion_frame: 0},
	{Group: 0},
	{select_hero: 0},
	{select_color: 0},
	{btn_robot: 0},
	{bg_black: 0},
	{rotate: 0},
	{txtRotate: 0},
	{ArrayCharacters: 0},
	{Text: 0},
	{bg: 0},
	{FireParticles: 0},
	{spaceship: 0},
	{JetFire: 0},
	{but_lang: 0},
	{b_dell_AD: 0},
	{txt_ad_sell: 0},
	{btn_default2: 0},
	{txt_button2: 0},
	{nn: 0},
	{txt_level: 0},
	{Угасание: 0},
	{txt_opoveshenie: 0},
	{dec_ad: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Синусоида: 0},
	{fgy3: 0},
	{txt_version: 0},
	{btn_home2: 0},
	{btn_pause: 0},
	{GamePush: 0},
	{background: 0},
	{buttons_hud: 0},
	{correct_awnser: 0},
	{score: 0},
	{highscore: 0},
	{lives: 0},
	{whoAtack: 0},
	{enemyPositionY: 0},
	{sort_question: 0},
	{number_questions: 0},
	{current_question: 0},
	{LSSound: 0},
	{LSHigheScore: 0},
	{clock_timer: 0},
	{clock_counter: 0},
	{CanAnswer: 0},
	{enemyInScreen: 0},
	{index: 0},
	{APIKEY: 0},
	{authDomain: 0},
	{projectId: 0},
	{scoreSubmit: 0},
	{submitSuccess: 0},
	{name: 0},
	{modalOpen: 0},
	{reward_stop_timer: 0},
	{AD_show: 0},
	{pause: 0},
	{answerX1: 0},
	{answerY1: 0},
	{answerX2: 0},
	{answerY2: 0},
	{answerY3: 0},
	{answerX3: 0},
	{answerX4: 0},
	{answerY4: 0},
	{combination: 0},
	{x: 0},
	{y: 0},
	{screen_width: 0},
	{screen_height: 0},
	{AD: 0},
	{SOUND: 0},
	{rezhim: 0},
	{character_opens_umn: 0},
	{character_opens_del: 0},
	{character: 0},
	{lang: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	solid: class extends self.ISpriteInstance {},
	hero: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	bg_live: class extends self.ISpriteInstance {},
	heart: class extends self.ISpriteInstance {},
	enemy_spawn: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	bg_question: class extends self.ISpriteInstance {},
	txt_question: class extends self.ITextInstance {},
	bg_answer: class extends self.ISpriteInstance {},
	txt_answers: class extends self.ITextInstance {},
	ArrayQuestions: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	smoke: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	full_screen: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	bg_questions: class extends self.ISpriteInstance {},
	txt_questions_hud: class extends self.ITextInstance {},
	bg_score: class extends self.ISpriteInstance {},
	txt_score: class extends self.ITextInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	bg_clock: class extends self.ISpriteInstance {},
	txt_clock: class extends self.ITextInstance {},
	rain: class extends self.ISpriteInstance {},
	splash: class extends self.IParticlesInstance {},
	gold: class extends self.ISpriteInstance {},
	gold_icon_area: class extends self.ISpriteInstance {},
	GoldParticles: class extends self.IParticlesInstance {},
	end_game: class extends self.ISpriteInstance {},
	txt_end_game: class extends self.ITextInstance {},
	bg_info: class extends self.ISpriteInstance {},
	Gold2: class extends self.ISpriteInstance {},
	Gold3: class extends self.ISpriteInstance {},
	CoinPack_box: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	FireSparkParticles: class extends self.IParticlesInstance {},
	rotate_effect: class extends self.ISpriteInstance {},
	speed_game: class extends self.ISpriteInstance {},
	btn_retry: class extends self.ISpriteInstance {},
	btn_ranking: class extends self.ISpriteInstance {},
	btn_default1: class extends self.ISpriteInstance {},
	txt_button: class extends self.ITextInstance {},
	txt_feedback: class extends self.ITextInstance {},
	background_feedback: class extends self.ISpriteInstance {},
	enemyStopTrigger: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	freelance: class extends self.ISpriteInstance {},
	shadow: class extends self.ISpriteInstance {},
	robot_explosion: class extends self.ISpriteInstance {},
	explosion_frame: class extends self.ISpriteInstance {},
	Group: class extends self.ISpriteInstance {},
	select_hero: class extends self.ISpriteInstance {},
	select_color: class extends self.ISpriteInstance {},
	btn_robot: class extends self.ISpriteInstance {},
	bg_black: class extends self.ITiledBackgroundInstance {},
	rotate: class extends self.ISpriteInstance {},
	txtRotate: class extends self.ITextInstance {},
	ArrayCharacters: class extends self.IArrayInstance {},
	Text: class extends self.ITextInstance {},
	bg: class extends self.ISpriteInstance {},
	FireParticles: class extends self.IParticlesInstance {},
	spaceship: class extends self.ISpriteInstance {},
	JetFire: class extends self.ISpriteInstance {},
	but_lang: class extends self.ISpriteInstance {},
	b_dell_AD: class extends self.ISpriteInstance {},
	txt_ad_sell: class extends self.ITextInstance {},
	btn_default2: class extends self.ISpriteInstance {},
	txt_button2: class extends self.ITextInstance {},
	txt_level: class extends self.ITextInstance {},
	txt_opoveshenie: class extends self.ITextInstance {},
	dec_ad: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	fgy3: class extends self.ISpriteInstance {},
	txt_version: class extends self.ITextInstance {},
	btn_home2: class extends self.ISpriteInstance {},
	btn_pause: class extends self.ISpriteInstance {},
	GamePush: class extends self.IInstance {},
	background: class extends self.ITiledBackgroundInstance {},
	buttons_hud: class extends self.ISpriteInstance {}
}